import type { Formula } from '../engine/types';

export const FORMULAS: Formula[] = [
  {
    id: 'rel-freq', concept: 'freq-tables', name: 'Relative frequency',
    latex: '\\text{relative frequency} = \\dfrac{f}{n}',
    symbols: [{ sym: 'f', meaning: 'frequency (count) of the class' }, { sym: 'n', meaning: 'total number of observations' }],
    meaning: 'The **proportion** of all observations that fall in a class.',
    whenToUse: 'Building frequency tables or relative-frequency histograms; comparing groups of different sizes.',
    whenNotToUse: 'When you need a running total ("at most…") — use **cumulative** relative frequency instead.',
    memoryTrick: '"Relative" = relative **to the whole**: part ÷ whole.',
    example: { prompt: 'In the Exam #1 review table, 36 of 60 people are in class 0–4.', steps: ['$f = 36$, $n = 60$', '$36 / 60 = 0.6$'], answer: '0.6 (60% of the data)' },
    commonMistake: 'Dividing by the class width or by the previous total instead of the overall n.',
    yourTurn: { prompt: 'Class 10–14 has frequency 8 out of n = 60. Relative frequency?', answer: 8 / 60, tol: 0.002, hint: '$8 \\div 60$' },
    source: { pages: [60, 1], section: '1.3–1.4 Frequency tables' },
  },
  {
    id: 'mean', concept: 'center', name: 'Mean (sample & population)',
    latex: '\\bar{x} = \\dfrac{\\sum x}{n} \\qquad \\mu = \\dfrac{\\sum x}{N}',
    symbols: [{ sym: '\\bar{x}', meaning: 'sample mean (x-bar)' }, { sym: '\\mu', meaning: 'population mean (mu)' }, { sym: '\\sum x', meaning: 'sum of all data values' }, { sym: 'n, N', meaning: 'sample size, population size' }],
    meaning: 'The balance point of the data — the "fair share" each value would get if the total were split evenly.',
    whenToUse: 'Roughly **symmetric** data without outliers.',
    whenNotToUse: 'Strongly **skewed** data or data with outliers — the mean is pulled toward the tail; use the median.',
    memoryTrick: '**x-bar** for the **bar**-sized sample; Greek **μ** for the mighty population.',
    example: { prompt: 'Paint Brand A: 10, 60, 55, 22, 48, 15 months.', steps: ['$\\sum x = 10+60+55+22+48+15 = 210$', '$n = 6$', '$\\bar{x} = 210/6 = 35$'], answer: '$\\bar{x} = 35$ months' },
    commonMistake: 'Dividing by the wrong count, or using μ for a sample.',
    yourTurn: { prompt: 'Brand B: 35, 45, 30, 35, 40, 25. Find x̄.', answer: 35, tol: 0.01, hint: 'Sum is 210; there are 6 cans.' },
    source: { pages: [58], section: '2.1–2.2 Measures of center' },
  },
  {
    id: 'median', concept: 'center', name: 'Median (MD)',
    latex: '\\text{MD} = \\text{value in position } \\dfrac{n+1}{2} \\text{ of the sorted data}',
    symbols: [{ sym: 'n', meaning: 'number of values' }, { sym: '\\text{MD}', meaning: 'median (course notation)' }],
    meaning: 'The middle value: half the data are below it and half above.',
    whenToUse: 'Any quantitative data; the preferred center for **skewed** data or data with outliers (it is **resistant**).',
    whenNotToUse: 'Categorical data.',
    memoryTrick: 'The **median** is in the middle of the road — like a highway median.',
    example: { prompt: 'Chips air %: 14 values sorted … 41, 45, 46, 47 … ', steps: ['n = 14 is even → average the 7th and 8th values', 'Sorted: 19 28 34 39 41 41 **45 46** 47 48 49 50 50 59', '(45 + 46)/2 = 45.5'], answer: 'MD = 45.5%' },
    commonMistake: 'Forgetting to sort first, or picking one value when n is even.',
    yourTurn: { prompt: 'Find the median of 27, 11, 22, 21, 40, 8, 17, 15, 29, 31, 27, 26.', answer: 24, tol: 0.01, hint: 'Sort; n = 12, so average the 6th and 7th values (22 and 26).' },
    source: { pages: [58, 22], section: '2.1–2.2 Measures of center' },
  },
  {
    id: 'midrange', concept: 'center', name: 'Midrange',
    latex: '\\text{midrange} = \\dfrac{\\min + \\max}{2}',
    symbols: [{ sym: '\\min, \\max', meaning: 'smallest and largest values' }],
    meaning: 'Halfway between the extremes.',
    whenToUse: 'A quick, rough center — the course notes it often **fails** to represent the typical value.',
    whenNotToUse: 'Whenever there are outliers (it uses *only* the two most extreme values).',
    memoryTrick: 'Mid-**range**: the middle of the range.',
    example: { prompt: '2002 payroll: min 34, max 126.', steps: ['(34 + 126)/2 = 80'], answer: '$80 million' },
    commonMistake: 'Confusing midrange with median.',
    source: { pages: [58], section: '2.1–2.2 Measures of center' },
  },
  {
    id: 'range', concept: 'range-iqr', name: 'Range',
    latex: '\\text{Range} = \\max - \\min',
    symbols: [{ sym: '\\max, \\min', meaning: 'largest and smallest values' }],
    meaning: 'The total width of the data.',
    whenToUse: 'A quick sense of total spread.',
    whenNotToUse: 'Data with outliers — one extreme value changes it completely.',
    memoryTrick: '"From the **floor** to the **ceiling**."',
    example: { prompt: 'Orange juice prices: min $2.99, max $5.99.', steps: ['5.99 − 2.99 = 3.00'], answer: 'All cartons are within $3 of each other.' },
    commonMistake: 'Reporting "2.99 to 5.99" instead of the single number 3.',
    yourTurn: { prompt: 'Chip air %: min 19, max 59. Range?', answer: 40, tol: 0.01, hint: 'max − min' },
    source: { pages: [50, 17], section: '2.7 Measures of spread' },
  },
  {
    id: 'iqr', concept: 'range-iqr', name: 'Interquartile range (IQR)',
    latex: '\\text{IQR} = Q_3 - Q_1',
    symbols: [{ sym: 'Q_1', meaning: 'first quartile (25th percentile)' }, { sym: 'Q_3', meaning: 'third quartile (75th percentile)' }],
    meaning: 'The spread of the **middle 50%** of the data.',
    whenToUse: 'Skewed data or data with outliers (IQR is **resistant**); boxplots.',
    whenNotToUse: 'When you need a measure that uses every value (SD).',
    memoryTrick: '**I**nside the **Q**uartiles — the width of the box.',
    example: { prompt: 'OJ prices: Q1 = 3.59, Q3 = 4.29.', steps: ['4.29 − 3.59 = 0.70'], answer: 'The middle 50% of cartons are within $0.70 of each other.' },
    commonMistake: 'Using max − min, or Q3 − median.',
    yourTurn: { prompt: 'Chips: Q1 = 39, Q3 = 49. IQR?', answer: 10, tol: 0.01, hint: 'Q3 − Q1' },
    source: { pages: [50, 17], section: '2.7 Measures of spread' },
  },
  {
    id: 'variance', concept: 'std-dev', name: 'Sample variance',
    latex: 's^2 = \\dfrac{\\sum (x - \\bar{x})^2}{n - 1}',
    symbols: [{ sym: 's^2', meaning: 'sample variance' }, { sym: 'x - \\bar{x}', meaning: 'deviation of a value from the mean' }, { sym: 'n - 1', meaning: 'sample size minus one' }],
    meaning: 'The (almost) average **squared** distance of the data from the mean.',
    whenToUse: 'As the step before the standard deviation.',
    whenNotToUse: 'To describe spread in words — variance is in **squared units** (e.g. "squared dollars").',
    memoryTrick: '**D**eviate → **S**quare → **S**um → **D**ivide by n−1. "Dogs Sleep Soundly Daily."',
    example: { prompt: 'Brand B: 35, 45, 30, 35, 40, 25 (x̄ = 35).', steps: ['Deviations: 0, 10, −5, 0, 5, −10', 'Squares: 0, 100, 25, 0, 25, 100 → sum 250', '$s^2 = 250/(6-1) = 50$'], answer: '$s^2 = 50$ months²' },
    commonMistake: 'Dividing by n (population formula) for sample data.',
    yourTurn: { prompt: 'Data 2, 4, 9 (x̄ = 5). Find s².', answer: 13, tol: 0.01, hint: 'Squares: 9, 1, 16 → 26; divide by n − 1 = 2.' },
    source: { pages: [50], section: '2.7 Measures of spread' },
  },
  {
    id: 'sd', concept: 'std-dev', name: 'Sample standard deviation',
    latex: 's = \\sqrt{s^2} = \\sqrt{\\dfrac{\\sum (x - \\bar{x})^2}{n - 1}}',
    symbols: [{ sym: 's', meaning: 'sample standard deviation' }, { sym: '\\sigma', meaning: 'population standard deviation (divides by N)' }],
    meaning: 'The **typical distance** of a data value from the mean, in the original units.',
    whenToUse: 'Roughly symmetric data without outliers; comparing consistency.',
    whenNotToUse: 'Skewed data with outliers — use IQR.',
    memoryTrick: 'SD = "**S**tandard **D**istance from the mean". Square root undoes the squaring.',
    example: { prompt: 'Brand B: $s^2 = 50$.', steps: ['$s = \\sqrt{50} \\approx 7.07$'], answer: 'On average, a can of Brand B lasts about 7.07 months away from the mean of 35 months.' },
    commonMistake: 'Forgetting the square root, or interpreting s as a range.',
    yourTurn: { prompt: 'Brand A has $\\sum(x-\\bar{x})^2 = 2388$ with n = 6. Find s.', answer: Math.sqrt(2388 / 5), tol: 0.01, hint: '$\\sqrt{2388/5}$' },
    source: { pages: [50, 17], section: '2.7 Measures of spread' },
  },
  {
    id: 'fences', concept: 'outliers', name: '1.5 × IQR rule (outlier fences)',
    latex: '\\text{Lower} = Q_1 - 1.5\\,\\text{IQR} \\qquad \\text{Upper} = Q_3 + 1.5\\,\\text{IQR}',
    symbols: [{ sym: 'Q_1, Q_3', meaning: 'quartiles' }, { sym: '\\text{IQR}', meaning: 'Q3 − Q1' }],
    meaning: 'Values beyond the fences are flagged as **outliers**.',
    whenToUse: 'Any quantitative data, especially skewed data; it is how modified boxplots mark outliers.',
    whenNotToUse: '—',
    memoryTrick: '"One and a half boxes out from the box."',
    example: { prompt: 'OJ: Q1 = 3.59, Q3 = 4.29, IQR = 0.70.', steps: ['1.5 × 0.70 = 1.05', 'Lower: 3.59 − 1.05 = 2.54', 'Upper: 4.29 + 1.05 = 5.34'], answer: '$5.99 > 5.34, so $5.99 is an outlier.' },
    commonMistake: 'Subtracting from Q3 for the lower fence, or forgetting the 1.5.',
    yourTurn: { prompt: 'South Branch hours: Q1 = 36, Q3 = 42. Upper fence?', answer: 51, tol: 0.01, hint: 'IQR = 6 → 1.5·6 = 9 → 42 + 9' },
    source: { pages: [51, 17, 15], section: '2.7 Outliers' },
  },
  {
    id: 'two-sd', concept: 'outliers', name: '2 SD rule',
    latex: '\\bar{x} - 2s \\;\\le\\; \\text{typical} \\;\\le\\; \\bar{x} + 2s',
    symbols: [{ sym: '\\bar{x}', meaning: 'mean' }, { sym: 's', meaning: 'standard deviation' }],
    meaning: '"Typical" values lie within two standard deviations of the mean; values outside are outliers.',
    whenToUse: 'Roughly symmetric data.',
    whenNotToUse: 'Strongly skewed data — the mean and SD are themselves distorted.',
    memoryTrick: '"Two steps left, two steps right."',
    example: { prompt: 'OJ: x̄ = 4.035, s = 0.68.', steps: ['4.035 − 2(0.68) = 2.675', '4.035 + 2(0.68) = 5.395'], answer: '$5.99 is outside 2.675–5.395 → outlier.' },
    commonMistake: 'Using one SD, or the median instead of the mean.',
    yourTurn: { prompt: 'Chips: x̄ = 42.571, s = 10.181. Lower 2SD bound?', answer: 42.571 - 2 * 10.181, tol: 0.01, hint: 'x̄ − 2s' },
    source: { pages: [51, 17, 18], section: '2.7 Outliers' },
  },
  {
    id: 'z', concept: 'z-score', name: 'Standard deviations from the mean (z-score)',
    latex: 'z = \\dfrac{x - \\bar{x}}{s}',
    symbols: [{ sym: 'x', meaning: 'the data value' }, { sym: '\\bar{x}', meaning: 'mean' }, { sym: 's', meaning: 'standard deviation' }],
    meaning: 'How many standard deviations a value is above (+) or below (−) the mean.',
    whenToUse: 'Comparing positions in **different** distributions (e.g. Maryland\'s representatives vs. counties).',
    whenNotToUse: '—',
    memoryTrick: '"Distance ÷ ruler": the SD is the ruler you measure distance with.',
    example: { prompt: 'Maryland: 8 representatives, x̄ = 8.7, s = 9.723.', steps: ['8 − 8.7 = −0.7', '−0.7 / 9.723 = −0.072'], answer: 'Maryland is 0.072 SDs below the mean.' },
    commonMistake: 'Dividing by the variance, or dropping the negative sign.',
    yourTurn: { prompt: 'Maryland has 23 counties; counties have x̄ = 62.82, s = 46.421. How many SDs from the mean?', answer: (23 - 62.82) / 46.421, tol: 0.005, hint: '(23 − 62.82) / 46.421' },
    source: { pages: [19, 52], section: '2.7 Practice #3' },
    supporting: true,
  },
  {
    id: 'percentile', concept: 'position', name: 'Percentile (course definition)',
    latex: '\\text{percentile of } x = \\dfrac{\\#\\{\\text{values} < x\\}}{n} \\times 100',
    symbols: [{ sym: 'n', meaning: 'number of values' }],
    meaning: 'The percent of data values **less than** x.',
    whenToUse: 'Describing relative position (test scores, rankings).',
    whenNotToUse: 'Confusing with percent correct.',
    memoryTrick: '"Percent of people **behind** you in line."',
    example: { prompt: 'Maryland has 8 representatives; 29 of 50 states have fewer.', steps: ['29 / 50 = 0.58'], answer: '58th percentile' },
    commonMistake: 'Counting values ≤ x instead of < x (the course uses "lesser value").',
    yourTurn: { prompt: 'A state is at the 52nd percentile of 50 states. How many states have fewer representatives?', answer: 26, tol: 0.01, hint: '0.52 × 50' },
    source: { pages: [54, 19], section: '2.6 Measures of position' },
  },
  {
    id: 'regression-line', concept: 'regression', name: 'Least-squares regression line',
    latex: '\\hat{y} = a + bx',
    symbols: [{ sym: '\\hat{y}', meaning: 'predicted response (y-hat)' }, { sym: 'a', meaning: 'y-intercept: predicted y when x = 0' }, { sym: 'b', meaning: 'slope: predicted change in y for each 1-unit increase in x' }, { sym: 'x', meaning: 'explanatory variable' }],
    meaning: 'The line that makes the **sum of squared residuals** as small as possible.',
    whenToUse: 'A linear pattern in the scatterplot and a random residual plot; predicting **within** the observed x-range.',
    whenNotToUse: 'Curved patterns, or x-values outside the data (**extrapolation**).',
    memoryTrick: '"**a**t the start, **b**y how much it changes."',
    example: { prompt: 'SCUBA: ŷ = 106.3421 − 0.8145x. Predict max dive time at 115 ft.', steps: ['ŷ = 106.3421 − 0.8145(115)', '= 106.3421 − 93.6675 = 12.67'], answer: 'About 12.67 minutes.' },
    commonMistake: 'Calling b the change in x, or treating predictions as guarantees.',
    yourTurn: { prompt: 'Archaeopteryx: ŷ = −3.6596 + 1.1969x. Predict humerus length for a 45 cm femur.', answer: -3.6596 + 1.1969 * 45, tol: 0.02, hint: 'Substitute x = 45.' },
    source: { pages: [43, 44, 10, 11], section: '12.1–12.3 Regression' },
  },
  {
    id: 'residual', concept: 'residuals', name: 'Residual',
    latex: '\\text{residual} = y - \\hat{y} = \\text{observed} - \\text{predicted}',
    symbols: [{ sym: 'y', meaning: 'observed (actual) value' }, { sym: '\\hat{y}', meaning: 'value predicted by the line' }],
    meaning: 'How far the actual point is above (+) or below (−) the regression line.',
    whenToUse: 'Judging prediction error and building residual plots.',
    whenNotToUse: '—',
    memoryTrick: '"**A**ctual **m**inus **p**redicted" — **AP**: like the AP exam, actual comes first.',
    example: { prompt: 'Flowers: ŷ = 180.8 + 15.8x. A flower with 2 tbsp lasted 204 h.', steps: ['ŷ = 180.8 + 15.8(2) = 212.4', 'Residual = 204 − 212.4 = −8.4'], answer: '−8.4 hours: the line **overpredicted** by 8.4 hours.' },
    commonMistake: 'Computing predicted − observed (flips the sign).',
    yourTurn: { prompt: 'A flower with 1 tbsp of sugar lasted 205 h. Residual?', answer: 205 - (180.8 + 15.8), tol: 0.01, hint: 'ŷ = 180.8 + 15.8(1) = 196.6' },
    source: { pages: [44, 12], section: '12.1–12.3 Residuals' },
  },
  {
    id: 'r2', concept: 'r-squared', name: 'Coefficient of determination',
    latex: 'r^2 = (r)^2 \\qquad r = \\pm\\sqrt{r^2}\\;(\\text{sign of the slope})',
    symbols: [{ sym: 'r', meaning: 'correlation coefficient' }, { sym: 'r^2', meaning: 'fraction of variation in y explained by x' }],
    meaning: 'The percent of the variation in the response variable that is **explained by** the variation in the explanatory variable (using the line).',
    whenToUse: 'Judging how useful a regression model is; comparing models.',
    whenNotToUse: 'As proof of causation, or as the % of points on the line.',
    memoryTrick: '"r² **r**eports the **r**eason share: how much of y\'s ups and downs x accounts for."',
    example: { prompt: 'Chocolate vs. Nobel prizes: r = 0.791.', steps: ['0.791² = 0.6257'], answer: 'About 62.6% of the variation in Nobel laureates is explained by chocolate consumption. (The PDF key prints 0.6247.)' },
    commonMistake: 'Forgetting the sign when going from r² back to r.',
    yourTurn: { prompt: 'Tablets: r² = 0.342 and the slope is +0.0068. Find r.', answer: Math.sqrt(0.342), tol: 0.002, hint: '√0.342, positive because the slope is positive.' },
    source: { pages: [44, 10, 12], section: '12.1–12.3 r and r²' },
  },
  {
    id: 'prob-equally', concept: 'prob-basics', name: 'Probability (equally likely outcomes)',
    latex: 'P(A) = \\dfrac{n(A)}{n(S)}',
    symbols: [{ sym: 'n(A)', meaning: 'number of outcomes in event A' }, { sym: 'n(S)', meaning: 'number of outcomes in the sample space' }],
    meaning: 'Favorable outcomes ÷ all possible outcomes — when every outcome is equally likely.',
    whenToUse: 'Dice, coins, cards, random selection from a table.',
    whenNotToUse: 'Outcomes that are not equally likely (e.g. a weighted spinner).',
    memoryTrick: '"What I **want** over what I **could** get."',
    example: { prompt: 'Roll a die. C = rolling a 1.', steps: ['n(C) = 1, n(S) = 6'], answer: 'P(C) = 1/6 ≈ 0.167' },
    commonMistake: 'Using the wrong sample space (e.g. 11 sums instead of 36 outcomes for two dice).',
    yourTurn: { prompt: 'Two dice: P(sum of 7)?', answer: 6 / 36, tol: 0.002, hint: '6 of the 36 outcomes sum to 7.' },
    source: { pages: [31, 36], section: '3.1 Probability basics' },
  },
  {
    id: 'complement', concept: 'prob-rules', name: 'Complement rule',
    latex: 'P(A\') = 1 - P(A)',
    symbols: [{ sym: "A'", meaning: 'complement: "not A"' }],
    meaning: 'The chance something does **not** happen.',
    whenToUse: '"Not", "neither", and especially "**at least one**" problems.',
    whenNotToUse: '—',
    memoryTrick: '"Everything minus the thing."',
    example: { prompt: 'Car rental: P(F or B) = 0.88.', steps: ['P(neither) = 1 − 0.88'], answer: '0.12' },
    commonMistake: 'Forgetting the complement shortcut and doing a long sum instead.',
    yourTurn: { prompt: 'Snow days: P(X ≥ 1) = 0.67. P(X = 0)?', answer: 0.33, tol: 0.001, hint: '1 − 0.67' },
    source: { pages: [31, 3], section: '3.1–3.5 Complement' },
  },
  {
    id: 'addition', concept: 'prob-rules', name: 'Addition rule ("or")',
    latex: 'P(A \\text{ or } B) = P(A) + P(B) - P(A \\text{ and } B)',
    symbols: [{ sym: 'A \\text{ or } B', meaning: 'A, B, or both' }, { sym: 'A \\text{ and } B', meaning: 'both at once (the overlap)' }],
    meaning: 'Add the two events, then remove the overlap you counted twice.',
    whenToUse: 'Any "or" question. If the events are **mutually exclusive**, P(A and B) = 0.',
    whenNotToUse: '—',
    memoryTrick: '"Add, then subtract the **double-counted** middle of the Venn diagram."',
    example: { prompt: 'MHS seniors: 90 play a sport, 140 go to college, 62 both (of 200).', steps: ['90/200 + 140/200 − 62/200', '= 168/200'], answer: '0.84' },
    commonMistake: 'Forgetting to subtract the overlap.',
    yourTurn: { prompt: '300 students: 95 sport, 124 extracurricular, 78 both. P(sport or EC)?', answer: 141 / 300, tol: 0.002, hint: '(95 + 124 − 78)/300' },
    source: { pages: [33, 6], section: '3.1–3.5 Addition rule' },
  },
  {
    id: 'conditional', concept: 'conditional', name: 'Conditional probability',
    latex: 'P(A \\mid B) = \\dfrac{P(A \\text{ and } B)}{P(B)}',
    symbols: [{ sym: 'A \\mid B', meaning: '"A given B" — B has already happened' }],
    meaning: 'The given event **B becomes the new sample space**.',
    whenToUse: '"Given", "of those who", "if…, what is the probability…".',
    whenNotToUse: '—',
    memoryTrick: '"**Given** goes **under** the bar" — the event after | is the denominator.',
    example: { prompt: 'Die: A = {1,2,3,4}, B = {2,4,6}.', steps: ['A and B = {2,4} → 2/6', 'P(B) = 3/6', '(2/6)/(3/6) = 2/3'], answer: 'P(A | B) = 2/3' },
    commonMistake: 'Dividing by P(A) or by the grand total.',
    yourTurn: { prompt: '73% of members play poker AND swim; 82% play poker. P(swim | poker)?', answer: 0.73 / 0.82, tol: 0.002, hint: '0.73 / 0.82' },
    source: { pages: [31, 6], section: '3.1–3.5 Conditional probability' },
  },
  {
    id: 'multiplication', concept: 'independence', name: 'Multiplication rule ("and")',
    latex: 'P(A \\text{ and } B) = P(A)\\cdot P(B \\mid A) \\;\\overset{\\text{indep.}}{=}\\; P(A)\\cdot P(B)',
    symbols: [{ sym: 'P(B \\mid A)', meaning: 'probability of B after A happened' }],
    meaning: 'Chance both happen. If independent, the second probability is unchanged.',
    whenToUse: 'Sequences (draws, trials, tree-diagram paths); checking independence.',
    whenNotToUse: '—',
    memoryTrick: '"**And** means **multiply** — along the tree branch."',
    example: { prompt: 'Two hearts in a row, no replacement.', steps: ['(13/52) · (12/51)', '= 1/17'], answer: '≈ 0.0588 (with replacement: 1/16 = 0.0625)' },
    commonMistake: 'Using P(A)·P(B) when events are dependent (without replacement).',
    yourTurn: { prompt: 'P(Spanish) = 0.75 for each independent student. P(all five are learning Spanish)?', answer: 0.75 ** 5, tol: 0.001, hint: '0.75⁵' },
    source: { pages: [33, 38], section: '3.1–3.5 Independence' },
  },
  {
    id: 'at-least-one', concept: 'independence', name: '"At least one"',
    latex: 'P(\\text{at least one}) = 1 - P(\\text{none})',
    symbols: [{ sym: 'P(\\text{none})', meaning: 'probability the event never happens in all trials' }],
    meaning: 'Everything except "zero times".',
    whenToUse: 'Repeated independent trials asking for "at least one".',
    whenNotToUse: '—',
    memoryTrick: '"At least one" = "**not none**".',
    example: { prompt: '15% chance of a special enemy, 5 independent fights.', steps: ['P(none) = 0.85⁵ = 0.4437', '1 − 0.4437'], answer: '0.5563' },
    commonMistake: 'Computing 5 × 0.15 = 0.75.',
    yourTurn: { prompt: 'P(positive test) = 0.2321 per patient. P(at least one of 4 tests positive)?', answer: 1 - (1 - 0.2321) ** 4, tol: 0.002, hint: '1 − 0.7679⁴' },
    source: { pages: [8], section: '3.1–3.5 Practice #10, #12' },
  },
  {
    id: 'expected-value', concept: 'expected-value', name: 'Expected value (mean of a random variable)',
    latex: '\\mu = E(X) = \\sum x \\cdot P(x)',
    symbols: [{ sym: 'x', meaning: 'each possible value' }, { sym: 'P(x)', meaning: 'its probability' }],
    meaning: 'The **long-run average** outcome — a probability-weighted average.',
    whenToUse: 'Games, insurance, any probability distribution table.',
    whenNotToUse: '—',
    memoryTrick: '"Multiply across, add down."',
    example: { prompt: '$100 on black in roulette: +100 with 18/38, −100 with 20/38.', steps: ['100(18/38) + (−100)(20/38)', '= −200/38'], answer: '≈ −$5.26 per bet in the long run.' },
    commonMistake: 'Averaging the x-values without weighting.',
    yourTurn: { prompt: 'Slot Z: −40 (0.56), 0 (0.38), 40 (0.06). E(Z)?', answer: -20, tol: 0.01, hint: '−40(0.56) + 0 + 40(0.06)' },
    source: { pages: [28, 3, 4], section: '4.1–4.2 Expected value' },
  },
  {
    id: 'rv-variance', concept: 'expected-value', name: 'Variance & SD of a random variable',
    latex: '\\sigma^2 = \\sum x^2 P(x) - \\mu^2 \\qquad \\sigma = \\sqrt{\\sigma^2}',
    symbols: [{ sym: '\\sigma', meaning: 'standard deviation of X' }, { sym: '\\mu', meaning: 'E(X)' }],
    meaning: 'How much the outcomes typically vary from the expected value.',
    whenToUse: 'Comparing risk/consistency of random variables.',
    whenNotToUse: '—',
    memoryTrick: '"Mean of the squares minus square of the mean."',
    example: { prompt: 'Slot Z: −40 (0.56), 0 (0.38), 40 (0.06), μ = −20.', steps: ['Σx²P = 1600(0.56) + 0 + 1600(0.06) = 992', '992 − (−20)² = 592', '√592 = 24.33'], answer: 'σ ≈ $24.33' },
    commonMistake: 'Forgetting to subtract μ².',
    yourTurn: { prompt: 'X: 0 (0.5), 2 (0.5). μ = 1. Find σ².', answer: 1, tol: 0.001, hint: 'Σx²P = 0 + 4(0.5) = 2; 2 − 1² = 1' },
    source: { pages: [3, 4], section: '4.1–4.2 Practice' },
  },
  {
    id: 'binom-mean-sd', concept: 'binomial', name: 'Binomial mean & standard deviation',
    latex: '\\mu = np \\qquad \\sigma^2 = npq \\qquad \\sigma = \\sqrt{npq} \\qquad (q = 1-p)',
    symbols: [{ sym: 'n', meaning: 'number of trials' }, { sym: 'p', meaning: 'probability of success' }, { sym: 'q', meaning: 'probability of failure, 1 − p' }],
    meaning: 'Center and spread of the number of successes.',
    whenToUse: 'X ~ B(n, p): fixed n, two outcomes, independent trials, same p.',
    whenNotToUse: 'Trials that aren\'t independent (e.g. pre-programmed traffic lights).',
    memoryTrick: '"**n**ice **p**eople" for the mean; "**n p q** under the roof" for the SD.',
    example: { prompt: 'Pop quiz: 10 questions, 4 choices each, guessing.', steps: ['p = 0.25, q = 0.75', 'μ = 10(0.25) = 2.5', 'σ = √(10 · 0.25 · 0.75) = √1.875 ≈ 1.369'], answer: 'Expect 2.5 correct, give or take about 1.37.' },
    commonMistake: 'Using √(np) or forgetting the square root.',
    yourTurn: { prompt: 'Soccer: 6 penalty kicks, p = 0.75. Find σ.', answer: Math.sqrt(6 * 0.75 * 0.25), tol: 0.002, hint: '√(6 · 0.75 · 0.25)' },
    source: { pages: [25, 27], section: '4.3 Binomial distributions' },
  },
  {
    id: 'binom-prob', concept: 'binomial', name: 'Binomial probability',
    latex: 'P(X = k) = \\binom{n}{k} p^k q^{\\,n-k}',
    symbols: [{ sym: '\\binom{n}{k}', meaning: 'number of ways to place k successes among n trials' }],
    meaning: 'Probability of exactly k successes. The course computes these with **technology (Stapplet)**; the formula is shown here only so you can see what the technology does.',
    whenToUse: 'Exact binomial probabilities; sum them for "at most / at least".',
    whenNotToUse: 'Non-binomial settings.',
    memoryTrick: '"Ways × successes × failures."',
    example: { prompt: 'Free throws: p = 0.72, n = 3. P(exactly 2 made)?', steps: ['3 ways (MMX, MXM, XMM)', '3 · 0.72² · 0.28 = 0.4355'], answer: '≈ 0.435 (overtime!)' },
    commonMistake: 'Forgetting the number of arrangements.',
    yourTurn: { prompt: 'p = 0.72, n = 3. P(all 3 made)?', answer: 0.72 ** 3, tol: 0.001, hint: '0.72³' },
    source: { pages: [24, 25], section: '4.3 Binomial (technology in course)', note: 'The PDF says the formal formula is beyond the course scope.' },
    supporting: true,
  },
  {
    id: 'uniform', concept: 'prob-dist', name: 'Continuous uniform probability',
    latex: 'P(c < Y < d) = \\dfrac{d - c}{b - a} \\quad \\text{for } Y \\sim U(a, b)',
    symbols: [{ sym: 'a, b', meaning: 'interval endpoints' }, { sym: 'c, d', meaning: 'the part of the interval you want' }],
    meaning: 'Every value in the interval is equally likely, so probability = fraction of the interval.',
    whenToUse: 'A continuous variable equally likely anywhere on an interval (e.g. dismissal time 0–180 min).',
    whenNotToUse: 'Discrete variables.',
    memoryTrick: '"Probability = length of what you want ÷ total length."',
    example: { prompt: 'Y uniform on 0–180 min; P(Y < 75)?', steps: ['75 / 180'], answer: '5/12 ≈ 0.4167' },
    commonMistake: 'Thinking P(Y = exactly 75) is 1/180 — for a continuous variable a single value has probability 0 (the 1/180 is the height of the distribution).',
    yourTurn: { prompt: 'Y uniform 0–180. P(30 < Y < 120)?', answer: 0.5, tol: 0.001, hint: '(120 − 30)/180' },
    source: { pages: [3], section: '4.1–4.2 Practice #1f' },
  },
];

export const FORMULA_BY_ID: Record<string, Formula> = Object.fromEntries(FORMULAS.map((f) => [f.id, f]));
