import type { ConceptId, GlossaryEntry, Source, VisualSpec } from '../engine/types';

type Extra = { formula?: string; mistake?: string; aliases?: string[]; visual?: VisualSpec };

function g(
  id: string, term: string, concept: ConceptId, pages: number[], section: string,
  definition: string, intuition: string, example: string, related: string[], extra: Extra = {},
): GlossaryEntry {
  const source: Source = { pages, section };
  return { id, term, concept, definition, intuition, example, related, source, ...extra };
}

const S11 = '1.1–1.2 Key Terms, Sampling, and Variation';
const S13 = '1.3–1.4 Frequency Tables, Experimental Design, Ethics';
const S21 = '2.1–2.2, 2.5 Graphs & Center';
const S24 = '2.4, 2.6 Shape, Position, Boxplots';
const S27 = '2.7 Measures of Spread';
const S28 = '2.8 Comparing Distributions';
const S12 = '12.1–12.3, 12.5 Two Quantitative Variables';
const S3 = '3.1–3.5 Probability Topics';
const S41 = '4.1–4.2 Probability Distributions';
const S43 = '4.3 Binomial Distributions';

export const GLOSSARY: GlossaryEntry[] = [
  // ---------- Unit 1 ----------
  g('statistics', 'Statistics', 'pop-sample', [64], S11, 'The science of collecting, organizing, summarizing, analyzing, and presenting **data**.', 'Turning a pile of numbers into a trustworthy answer to a question.', 'Surveying 100 Knoll Academy families to estimate average uniform spending.', ['data', 'population', 'sample']),
  g('data', 'Data', 'pop-sample', [64], S11, 'The actual values that a **variable** takes on.', 'The raw answers you wrote down.', 'The amounts $65, $75, and $95 spent by three families.', ['variable'], { mistake: 'Calling the variable ("amount spent") the data.' }),
  g('variable', 'Variable', 'pop-sample', [64], S11, 'A characteristic of each individual that can take different values (often written X).', 'The question you ask every individual.', 'X = amount of money a family spends on uniforms.', ['data', 'categorical', 'quantitative']),
  g('population', 'Population', 'pop-sample', [64], S11, 'The entire group of persons, things, or objects being studied.', 'Everyone you *wish* you could ask.', 'All families with children at Knoll Academy.', ['sample', 'parameter'], { mistake: 'Describing the population as only the people surveyed.' }),
  g('sample', 'Sample', 'pop-sample', [64], S11, 'A subset of the population that is actually studied.', 'The spoonful you taste to judge the whole pot of soup.', 'The 100 surveyed families.', ['population', 'statistic', 'srs']),
  g('statistic', 'Statistic', 'pop-sample', [64], S11, 'A number computed from **sample** data (mean, median, proportion…).', '**S**tatistic ↔ **S**ample.', 'The mean amount spent by the 100 sampled families.', ['parameter', 'sample'], { mistake: 'Calling a sample mean a parameter.' }),
  g('parameter', 'Parameter', 'pop-sample', [64], S11, 'A number describing the whole **population** — usually unknown and estimated by a statistic.', '**P**arameter ↔ **P**opulation.', 'The mean amount spent by *all* Knoll Academy families.', ['statistic', 'population', 'inference']),
  g('categorical', 'Categorical (qualitative) data', 'data-types', [64], S11, 'Data that place individuals into groups or labels.', 'If averaging it is meaningless, it is categorical.', 'Favorite baseball team, brand of toothpaste.', ['quantitative', 'bar-graph', 'pie-chart'], { aliases: ['qualitative'], mistake: 'Calling numeric labels like zip codes quantitative.' }),
  g('quantitative', 'Quantitative data', 'data-types', [64], S11, 'Numerical data that measure or count an attribute.', 'Numbers you can meaningfully add and average.', 'Number of tickets sold, time in line.', ['discrete', 'continuous']),
  g('discrete', 'Discrete data', 'data-types', [64], S11, 'Quantitative data that can take only countable values.', '"Number of…" — you can list the possible values.', 'Number of students enrolled; number of snow days.', ['continuous', 'discrete-rv'], { mistake: 'Calling measurements like time discrete.' }),
  g('continuous', 'Continuous data', 'data-types', [64], S11, 'Quantitative data that can take any value in an interval.', 'Measurements — there is always a value in between.', 'Percent body fat, distance to the theater, age.', ['discrete']),
  g('frequency-table-cat', 'Frequency table (categorical)', 'cat-displays', [64], S11, 'A table listing each category with its count (and often percent).', 'A tally organized neatly.', 'Ethnicity of students: Asian 8,794 (36.1%), …', ['bar-graph', 'pie-chart', 'relative-frequency']),
  g('pie-chart', 'Pie chart', 'cat-displays', [64], S11, 'A circle divided into slices proportional to each category\'s percent of the whole.', 'Best when you care about parts of one whole.', 'Ethnicity of Students pie chart.', ['bar-graph', 'pareto'], { mistake: 'Using a pie chart when categories don\'t add to 100%.' }),
  g('bar-graph', 'Bar graph', 'cat-displays', [64], S11, 'Separated bars whose heights show the count or percent for each category.', 'Categories on the axis, gaps between bars.', 'Ethnicity of Students bar graph.', ['pareto', 'histogram'], { mistake: 'Confusing a bar graph with a histogram.' }),
  g('pareto', 'Pareto chart', 'cat-displays', [64], S11, 'A bar graph with bars sorted from tallest to shortest.', 'Biggest categories first, so you see what matters most.', 'Asian 36.1%, White 24.5%, Hispanic 17.1%, …', ['bar-graph']),
  g('sampling-bias', 'Sampling bias', 'sampling', [65], S11, 'When a sampling method systematically produces statistics that over- or underestimate the true parameter.', 'A scale that always reads 5 lb heavy.', 'Counting ducks only in the 15 squares next to the park entrance.', ['random-sampling', 'convenience']),
  g('random-sampling', 'Random sampling', 'sampling', [65], S11, 'Using chance to choose the sample, which minimizes bias.', 'Let a lottery machine pick, not you.', 'Using a random number generator to choose 18 grocery stores.', ['srs', 'systematic', 'stratified', 'cluster']),
  g('srs', 'Simple random sample (SRS)', 'sampling', [65, 66], S11, 'Every group of n individuals has the same chance of being chosen.', 'Names in a hat.', 'Calling 1,200 randomly selected phone numbers.', ['systematic', 'stratified', 'cluster'], { aliases: ['simple random sampling'] }),
  g('systematic', 'Systematic sampling', 'sampling', [65, 66], S11, 'Choose a random starting point, then select every k-th individual from a list.', 'Every 4th person through the door.', 'A librarian records every fourth patron who checks out books.', ['srs']),
  g('stratified', 'Stratified sampling', 'sampling', [65, 66], S11, 'Split the population into groups (strata) and take a random sample **from each** group.', 'A little from every group so none is left out.', '100 random customers at **each** store location.', ['cluster'], { mistake: 'Confusing with cluster sampling.' }),
  g('cluster', 'Cluster sampling', 'sampling', [65, 66], S11, 'Split the population into groups (clusters), randomly choose **entire clusters**, and use everyone in them.', 'Pick whole buses of students, not students from every bus.', 'A teacher randomly picks rows 2 and 5 and calls on every student in them.', ['stratified']),
  g('convenience', 'Convenience sampling', 'sampling', [65, 66], S11, 'Choosing whoever is easiest to reach — not random, usually biased.', '"Whoever is standing nearby."', 'Asking travelers sitting near the gate who are not busy.', ['sampling-bias']),
  g('frequency', 'Frequency', 'freq-tables', [60], S13, 'The number of times a value or class occurs.', 'A count.', '36 people missed 0–4 days.', ['relative-frequency', 'cumulative-frequency']),
  g('relative-frequency', 'Relative frequency', 'freq-tables', [60], S13, 'A class frequency divided by the total number of observations.', 'The fraction of the whole.', '36/60 = 0.6.', ['frequency', 'cumulative-frequency'], { formula: 'rel-freq' }),
  g('cumulative-frequency', 'Cumulative (relative) frequency', 'freq-tables', [60], S13, 'The running total of frequencies (or relative frequencies) up to and including a class.', '"How many so far?"', 'Cumulative relative frequency 0.8 at class 10–14 means 80% missed 14 or fewer days.', ['relative-frequency'], { mistake: 'Reading a single class when the question says "at most".' }),
  g('explanatory', 'Explanatory variable', 'experiments', [60], S13, 'The variable that may cause or explain a change in another variable (x).', 'The "input" or the knob you turn.', 'Premium vs. free access (Spotify study).', ['response', 'treatment'], { mistake: 'Swapping explanatory and response.' }),
  g('response', 'Response variable', 'experiments', [60], S13, 'The outcome measured to see the effect of the explanatory variable (y).', 'The "output" you watch.', 'Daily listening time.', ['explanatory']),
  g('treatment', 'Treatment', 'experiments', [60], S13, 'The manipulation of the explanatory variable applied to experimental units.', 'What the researcher *does* to subjects.', 'Giving one group premium access.', ['experimental-units', 'control-group']),
  g('experimental-units', 'Experimental units', 'experiments', [60], S13, 'The individuals (people, animals, objects) to which treatments are applied and measured.', 'Who or what gets the treatment.', 'The 155 app users; 12 carnations.', ['treatment']),
  g('lurking', 'Lurking variable', 'experiments', [60], S13, 'An unmeasured factor, not part of the study, that affects the variables being examined.', 'A hidden third player.', 'Family income behind both marshmallow patience and later success.', ['confounding']),
  g('confounding', 'Confounding variable', 'experiments', [60, 1], S13, 'A known factor associated with the explanatory variable that also influences the response, making effects hard to separate.', 'Two causes tangled together.', 'Time spent on homework confounds video games and flunking out.', ['lurking']),
  g('randomization', 'Randomization', 'experiments', [60], S13, 'Using chance to assign experimental units to treatments.', 'Balances out hidden differences between groups.', 'Randomly assigning carnations to sugar levels.', ['control-group']),
  g('control-group', 'Control group', 'experiments', [60], S13, 'A group that receives no treatment (or a placebo) for comparison.', 'The baseline.', 'The "alone" group in the heart-rate study.', ['placebo', 'blinding']),
  g('blinding', 'Blinding (single/double)', 'experiments', [60], S13, 'Keeping subjects (single) or both subjects and researchers (double) unaware of who gets which treatment.', 'Nobody\'s expectations can tilt the results.', 'Neither patients nor doctors know who got the real drug.', ['placebo']),
  g('placebo', 'Placebo', 'experiments', [60, 1], S13, 'A fake treatment that looks like the real one; the "placebo effect" is improvement from expectations alone.', 'A sugar pill.', 'Subjects told about the placebo effect may change their behavior.', ['blinding']),
  g('response-bias', 'Response bias', 'bias', [60, 61, 1], S13, 'Collecting data or asking questions in a way that influences the response (leading wording, threats, intimidation).', 'The question pushes the answer.', '"Given that ChatGPT violates the academic honesty policy…, have you ever used it?"', ['nonresponse', 'voluntary-response', 'undercoverage']),
  g('undercoverage', 'Undercoverage', 'bias', [60, 61], S13, 'Part of the population is left out of the selection process and can\'t be in the sample.', 'They never got an invitation.', 'Surveying only Whole Foods customers about grocery shopping.', ['nonresponse']),
  g('nonresponse', 'Nonresponse bias', 'bias', [60, 61, 1], S13, 'People selected for the sample are unable or refuse to respond.', 'Invited, but didn\'t show up.', 'Only 10% of phone calls answered.', ['voluntary-response', 'undercoverage'], { mistake: 'Confusing with voluntary response.' }),
  g('voluntary-response', 'Voluntary response bias', 'bias', [60, 61], S13, 'Individuals decide for themselves whether to be in the sample — usually those with strong opinions.', 'Self-invited guests.', 'A social media poll; letters to the newspaper.', ['nonresponse']),
  g('inference', 'Inference', 'investigative', [60], S13, 'Using sample data to estimate an unknown parameter or evaluate a claim, and generalize to a population.', 'From the spoonful to the whole pot.', 'Estimating the proportion of Michigan students who drive to school.', ['investigative-question', 'parameter']),
  g('investigative-question', 'Investigative question', 'investigative', [60, 62, 63], S13, 'A question posed before data collection that names the **variable of interest**, the **inference goal** (estimate or test), and the **scope of inference** (population).', 'The mission statement of a study.', '"What proportion of all Michigan high school students drive their own car to school?"', ['inference']),
  // ---------- Unit 2 ----------
  g('stem-leaf', 'Stem-and-leaf plot', 'quant-graphs', [57, 22], S21, 'A display splitting each value into a stem (leading digits) and leaf (last digit), with a key.', 'A histogram you can still read the numbers from.', 'Actor ages; key 7|7 = 77.', ['dotplot', 'histogram'], { visual: { type: 'stemleaf', keyText: '7|7 = 77', rows: [{ stem: 1, leaves: [8] }, { stem: 2, leaves: [1, 2, 5, 6, 7, 9] }, { stem: 3, leaves: [0, 1, 3, 6, 7] }, { stem: 4, leaves: [1, 2, 7] }, { stem: 5, leaves: [2, 5, 7, 8] }, { stem: 6, leaves: [2, 4, 7, 9] }, { stem: 7, leaves: [1, 2, 3, 4, 6, 7] }] } }),
  g('dotplot', 'Dotplot', 'quant-graphs', [57], S21, 'Each data value is a dot above a number line.', 'Great for small data sets; crowded for large ones.', 'Chip air percentages.', ['stem-leaf', 'histogram'], { visual: { type: 'dotplot', data: [46, 59, 48, 19, 47, 41, 39, 45, 28, 50, 50, 41, 49, 34], xLabel: 'Percent of air' } }),
  g('histogram', 'Histogram', 'quant-graphs', [58], S21, 'Touching bars over equal intervals of a quantitative variable; bar heights show frequency (or relative frequency).', 'A dotplot with the dots stacked into bins.', '2003 MLB payroll histogram.', ['bar-graph', 'shape-symmetric'], { mistake: 'Leaving gaps or treating it like a bar graph.', visual: { type: 'histogram', xLabel: '2003 Payroll ($ millions)', bins: [{ lo: 20, hi: 40, count: 1 }, { lo: 40, hi: 60, count: 13 }, { lo: 60, hi: 80, count: 5 }, { lo: 80, hi: 100, count: 5 }, { lo: 100, hi: 120, count: 5 }, { lo: 120, hi: 140, count: 0 }, { lo: 140, hi: 160, count: 1 }] } }),
  g('summary-statistics', 'Summary statistics', 'center', [58], S21, 'Numbers that describe a data set (n, mean, min, median, max, SD, quartiles…).', 'The data set\'s ID card.', 'n = 30, μ = 71.067, min 20, MD 69, max 153.', ['mean', 'five-number']),
  g('mean', 'Mean (x̄, μ)', 'center', [58], S21, 'The arithmetic average: sum of values ÷ number of values. x̄ for a sample, μ for a population.', 'The balance point of the data.', 'Chip air: x̄ = 42.571%.', ['median', 'resistant'], { formula: 'mean', aliases: ['average', 'x-bar', 'mu'], mistake: 'Using the mean for strongly skewed data.' }),
  g('median', 'Median (MD)', 'center', [58], S21, 'The middle value of sorted data; average of the two middle values if n is even.', 'Half above, half below.', 'Chip air: MD = 45.5%.', ['mean', 'resistant', 'quartile'], { formula: 'median', mistake: 'Not sorting first.' }),
  g('mode', 'Mode', 'center', [58, 1], S21, 'The most frequently occurring value (there can be more than one).', 'The most popular value.', 'Medical school GPAs: modes 3.70 and 3.74.', ['mean', 'median']),
  g('midrange', 'Midrange', 'center', [58], S21, 'The mean of the minimum and maximum values.', 'Halfway between the extremes.', '(34 + 126)/2 = 80.', ['range'], { formula: 'midrange' }),
  g('resistant', 'Resistant measure', 'outliers', [59, 18], S27, 'A statistic that is not strongly affected by outliers or skew (median, IQR).', 'Doesn\'t flinch when one extreme value shows up.', 'Adding Helium Chips (78%) moved the mean 42.571→44.933 but the median only 45.5→46.', ['median', 'iqr', 'outlier']),
  g('shape-symmetric', 'Symmetric distribution', 'shape', [53], S24, 'Data spread about equally on both sides of the center; mean ≈ median ≈ mode.', 'A mirror image.', 'Professor Epsilon: μ = 66.8, MD = 67.', ['skewed-right', 'skewed-left'], { visual: { type: 'shape', shape: 'symmetric' } }),
  g('skewed-right', 'Skewed right (positively skewed)', 'shape', [53, 20], S24, 'A long tail to the right; most data fall below the mean; mode < median < mean.', 'The tail points to the **right**, like a few very high salaries.', 'Professor Delta: μ = 75.7 > MD = 68.', ['skewed-left', 'mean'], { visual: { type: 'shape', shape: 'right' }, mistake: 'Naming skew by the peak instead of the tail.' }),
  g('skewed-left', 'Skewed left (negatively skewed)', 'shape', [53, 20], S24, 'A long tail to the left; mean < median < mode.', 'A few very low values drag the mean down.', 'Professor Gamma: μ = 67.3 < MD = 72.', ['skewed-right'], { visual: { type: 'shape', shape: 'left' } }),
  g('uniform-shape', 'Uniform (shape)', 'shape', [53], S24, 'Data values are spread evenly over the whole range — no clear peak.', 'A flat histogram.', 'Marine Corps group with scores spread across all levels.', ['bimodal'], { visual: { type: 'shape', shape: 'uniform' } }),
  g('bimodal', 'Bimodal', 'shape', [53], S24, 'Two distinct peaks (modes) — usually a sign that two groups are mixed and the data should be separated.', 'Two humps, two crowds.', 'Fitness scores mixing 6th graders and 12th graders.', ['uniform-shape'], { visual: { type: 'shape', shape: 'bimodal' } }),
  g('outlier', 'Outlier', 'outliers', [51, 17], S27, 'A value unusually far from the rest of the data, identified with the 1.5×IQR rule or the 2 SD rule.', 'The one that doesn\'t fit.', 'Fritos at 19% air.', ['iqr-rule', 'two-sd-rule', 'resistant']),
  g('percentile', 'Percentile', 'position', [54, 19], S24, 'The percent of data values less than a given value.', 'The share of people behind you in line.', 'Maryland\'s 8 representatives is the 58th percentile.', ['quartile'], { formula: 'percentile', mistake: 'Confusing percentile with percent correct.' }),
  g('quartile', 'Quartiles (Q1, Q3)', 'position', [54], S24, 'Values splitting sorted data into four parts: Q1 = 25th percentile (median of lower half), Q3 = 75th percentile (median of upper half).', 'The medians of each half.', 'Northbound speeds: Q1 = 63, Q3 = 66.', ['median', 'iqr', 'five-number']),
  g('five-number', 'Five-number summary', 'position', [54], S24, 'Min, Q1, median, Q3, max.', 'The skeleton of a boxplot.', 'Northbound speeds: 60, 63, 65, 66, 83.', ['boxplot', 'quartile']),
  g('boxplot', 'Boxplot', 'boxplots', [54, 55], S24, 'A graph of the five-number summary: a box from Q1 to Q3 with a median line and whiskers to the min/max (outliers may be shown as dots).', 'Each of the four parts holds about 25% of the data.', 'Comparative boxplots of male vs. female hurricane deaths.', ['five-number', 'iqr'], { visual: { type: 'boxplot', groups: [{ label: 'Northbound', min: 60, q1: 63, median: 65, q3: 66, max: 70, outliers: [83] }], xLabel: 'Speed (mph)' }, mistake: 'Thinking a longer section contains more data.' }),
  g('range', 'Range', 'range-iqr', [50], S27, 'Maximum − minimum.', 'Total width of the data.', 'OJ: 5.99 − 2.99 = $3.', ['iqr'], { formula: 'range' }),
  g('iqr', 'Interquartile range (IQR)', 'range-iqr', [50], S27, 'Q3 − Q1: the spread of the middle 50% of the data.', 'The width of the box.', 'OJ: 4.29 − 3.59 = $0.70.', ['range', 'quartile', 'resistant'], { formula: 'iqr' }),
  g('variance', 'Variance', 'std-dev', [50], S27, 'The average squared distance of data values from the mean (sample: divide by n − 1).', 'Spread measured in squared units.', 'Chip air: s² = 103.652.', ['standard-deviation'], { formula: 'variance' }),
  g('standard-deviation', 'Standard deviation', 'std-dev', [50], S27, 'The square root of the variance: the typical distance of a data value from the mean.', 'How far your darts usually land from the bullseye.', 'OJ: s = $0.68 — prices are typically about 68¢ from the mean.', ['variance', 'z-score'], { formula: 'sd', aliases: ['SD', 's', 'sigma'], mistake: 'Dividing by n for sample data.' }),
  g('iqr-rule', '1.5 × IQR rule', 'outliers', [51, 17], S27, 'Values below Q1 − 1.5·IQR or above Q3 + 1.5·IQR are outliers.', 'Fences one-and-a-half boxes out.', 'OJ fences $2.54 and $5.34.', ['outlier', 'two-sd-rule'], { formula: 'fences' }),
  g('two-sd-rule', '2 SD rule', 'outliers', [51, 17], S27, 'Values more than two standard deviations from the mean are outliers.', 'Two steps left, two steps right.', 'OJ: 2.675 to 5.395.', ['outlier', 'iqr-rule'], { formula: 'two-sd' }),
  g('z-score', 'Standardized score (z-score)', 'z-score', [19], S27, 'The number of standard deviations a value is from the mean: (x − x̄)/s.', 'Distance measured with an SD ruler.', 'Maryland counties: (23 − 62.82)/46.421 = −0.858.', ['standard-deviation', 'percentile'], { formula: 'z' }),
  g('center-shape-spread', 'Center, shape, and spread', 'compare', [48], S28, 'The three features always described (in context) when comparing distributions, plus outliers.', 'Where is it, what does it look like, how spread out is it?', 'Pets lowered median heart rate and gave the most consistent results (smallest IQR).', ['median', 'iqr', 'shape-symmetric']),
  // ---------- Unit 3 ----------
  g('bivariate', 'Bivariate data', 'scatter', [43], S12, 'Data on two variables for each individual.', 'Pairs (x, y).', 'Depth and max dive time for each dive.', ['scatterplot']),
  g('scatterplot', 'Scatterplot', 'scatter', [43], S12, 'A graph of bivariate quantitative data: explanatory variable on the x-axis, response on the y-axis.', 'One dot per individual.', 'Femur vs. humerus length.', ['correlation-coefficient', 'regression-line'], { visual: { type: 'scatter', points: [[38, 41], [56, 63], [59, 70], [64, 72], [74, 84]], xLabel: 'Femur (cm)', yLabel: 'Humerus (cm)' } }),
  g('direction', 'Direction (of association)', 'scatter', [43], S12, 'Positive (y tends to increase as x increases) or negative (y tends to decrease).', 'Uphill or downhill.', 'SCUBA: negative — deeper dives allow less time.', ['strength']),
  g('strength', 'Strength (of association)', 'scatter', [43, 44], S12, 'How closely the points follow a line (or curve).', 'Tight band = strong; cloud = weak.', 'Femur/humerus r = 0.9941 — very strong.', ['direction', 'correlation-coefficient']),
  g('correlation-coefficient', 'Correlation coefficient (r)', 'correlation', [44], S12, 'A number from −1 to 1 measuring the strength and direction of a **linear** relationship.', 'Sign = direction, size = strength.', 'Chocolate vs. Nobel prizes: r = 0.791.', ['r2', 'direction'], { aliases: ['r', 'correlation'], mistake: 'Treating correlation as causation.' }),
  g('linear-regression', 'Linear regression', 'regression', [43], S12, 'The process of finding the line of best fit for bivariate data.', 'Drawing the best straight-line summary.', 'Stapplet\'s "Two Quantitative Variables" applet.', ['regression-line']),
  g('regression-line', 'Least-squares regression line', 'regression', [43, 44], S12, 'The line ŷ = a + bx that minimizes the sum of squared residuals.', 'The line that keeps total squared misses smallest.', 'SCUBA: ŷ = 106.3421 − 0.8145x.', ['slope', 'y-intercept', 'residual'], { formula: 'regression-line', aliases: ['line of best fit', 'LSRL'] }),
  g('slope', 'Slope (b)', 'regression', [43], S12, 'The predicted change in y for each one-unit increase in x.', 'Rise per run of the prediction line.', 'For every extra cm of femur, the predicted humerus increases 1.1969 cm.', ['y-intercept'], { mistake: 'Describing a guaranteed change rather than a predicted one.' }),
  g('y-intercept', 'y-intercept (a)', 'regression', [43, 2], S12, 'The predicted y when x = 0 (may be meaningless if x = 0 is outside the data).', 'Where the line starts.', 'A 0-letter word predicts −5.4141 spider deaths — nonsense, because 0 letters is outside the data.', ['slope', 'extrapolation']),
  g('extrapolation', 'Extrapolation', 'regression', [43, 12], S12, 'Using a regression line to predict for x-values outside the observed domain — unreliable.', 'Driving off the edge of the map.', 'Predicting freshness for 10 tablespoons of sugar when data only go to 3.', ['regression-line']),
  g('r2', 'Coefficient of determination (r²)', 'r-squared', [44], S12, 'The percent of variation in the response variable explained by the variation in the explanatory variable using the regression line.', 'How much of y\'s up-and-down x accounts for.', 'r² = 0.9883: 98.83% of the variation in humerus length is explained by femur length.', ['correlation-coefficient'], { formula: 'r2', mistake: 'Calling r² the percent of points on the line.' }),
  g('residual', 'Residual', 'residuals', [44], S12, 'Observed y − predicted ŷ: the vertical distance from a point to the line.', 'How much the line missed by.', 'Flower: 204 − 212.4 = −8.4 hours (overpredicted).', ['residual-plot'], { formula: 'residual', mistake: 'Calculating predicted − observed.' }),
  g('residual-plot', 'Residual plot', 'residuals', [44, 12], S12, 'A scatterplot of residuals against x; a random scatter supports a linear model, a curve means a linear model is not appropriate.', 'Leftovers after the line — they should look like noise.', 'iPhone sales: curved residuals → linear fit not best.', ['residual'], { visual: { type: 'residual', points: [[0, 1.9], [1, 0.8], [2, -0.8], [3, -1.7], [4, -1.0], [5, -1.6], [6, 0.8], [7, 0.2], [8, 1.6]], xLabel: 'Years since 2007' } }),
  g('s-residuals', 'Standard deviation of the residuals (s)', 'residuals', [13, 14], S12, 'The typical size of a prediction error for a regression model.', 'How far off predictions usually are.', 'Quadratic iPhone model: s = 0.6761 million units.', ['residual', 'r2']),
  // ---------- Unit 4 ----------
  g('probability-experiment', 'Probability experiment', 'prob-basics', [31, 36], S3, 'A chance process with well-defined outcomes.', 'Something random you can repeat.', 'Tossing two coins.', ['outcome', 'sample-space']),
  g('outcome', 'Outcome', 'prob-basics', [31], S3, 'A single possible result of a probability experiment.', 'One way it could turn out.', 'HT when tossing two coins.', ['sample-space', 'event']),
  g('sample-space', 'Sample space (S)', 'prob-basics', [31], S3, 'The set of all possible outcomes.', 'The full menu of results.', 'Two coins: S = {HH, HT, TH, TT}.', ['event']),
  g('event', 'Event', 'prob-basics', [31], S3, 'A set of outcomes from the sample space meeting some condition.', 'The outcomes you care about.', 'A = rolling less than 5 = {1, 2, 3, 4}.', ['sample-space', 'complement-term']),
  g('probability', 'Probability', 'prob-basics', [31], S3, 'The long-term relative frequency of an event; a value between 0 and 1.', 'How often it happens in the long run.', 'P(rolling a 1) = 1/6.', ['experimental-prob', 'theoretical-prob'], { formula: 'prob-equally' }),
  g('experimental-prob', 'Experimental (empirical) probability', 'prob-basics', [31], S3, 'Probability estimated from the results of repeated trials.', 'What actually happened when you tried.', '27 heads in 50 flips → 0.54.', ['theoretical-prob']),
  g('theoretical-prob', 'Theoretical (classical) probability', 'prob-basics', [31], S3, 'Probability found from the sample space before any trials. With more trials, experimental probability gets closer to it.', 'What *should* happen.', 'P(heads) = 1/2.', ['experimental-prob']),
  g('complement-term', 'Complement (A′)', 'prob-rules', [31], S3, 'All outcomes in the sample space not in event A; P(A′) = 1 − P(A).', '"Everything else."', 'C = {1} → C′ = {2,3,4,5,6}, P(C′) = 5/6.', ['event'], { formula: 'complement' }),
  g('and-event', '"A and B"', 'prob-rules', [31], S3, 'Outcomes in both A and B (the overlap).', 'The middle of the Venn diagram.', 'A = {1,2,3,4}, B = {2,4,6} → {2,4}.', ['or-event', 'mutually-exclusive']),
  g('or-event', '"A or B"', 'prob-rules', [31], S3, 'Outcomes in A, in B, or in both.', 'Either circle, overlap counted once.', 'A or B = {1,2,3,4,6}.', ['and-event'], { formula: 'addition' }),
  g('mutually-exclusive', 'Mutually exclusive events', 'prob-rules', [32], S3, 'Events that cannot happen at the same time: P(A and B) = 0, so P(A or B) = P(A) + P(B).', 'Can\'t be in both circles.', 'Enrolling in college vs. planning to work (MHS seniors).', ['independent', 'or-event'], { mistake: 'Thinking mutually exclusive means independent.' }),
  g('conditional-probability', 'Conditional probability', 'conditional', [31], S3, 'P(A | B): the probability of A given that B has occurred; = P(A and B)/P(B).', 'Shrink the world to B, then look for A.', 'P(Math | non-senior) = 11/25.', ['contingency-table'], { formula: 'conditional', mistake: 'Dividing by the grand total.' }),
  g('independent', 'Independent events', 'independence', [32], S3, 'The occurrence of one event does not affect the probability of the other: P(A) = P(A | B), equivalently P(A and B) = P(A)·P(B).', 'Coins don\'t remember.', 'Spanish and German: 0.75 × 0.2 = 0.15 = P(S and G).', ['mutually-exclusive'], { formula: 'multiplication' }),
  g('replacement', 'With / without replacement', 'independence', [33], S3, 'With replacement, draws are independent; without replacement, later probabilities change (dependent).', 'Putting the card back resets the deck.', 'Two hearts: 1/16 with, 1/17 without.', ['independent']),
  g('tree-diagram', 'Tree diagram', 'trees-venn', [34], S3, 'Branches show sequential outcomes with probabilities; multiply along a path and add across paths.', 'A map of every route the chance process can take.', 'Duck pools: P(gold) = 2/15 + 7/30 = 11/30.', ['venn-diagram'], { visual: { type: 'tree', root: { label: 'Start', children: [{ label: 'Pool 1', p: '2/3', children: [{ label: 'Red', p: '8/10' }, { label: 'Gold', p: '2/10' }] }, { label: 'Pool 2', p: '1/3', children: [{ label: 'Red', p: '3/10' }, { label: 'Gold', p: '7/10' }] }] } } }),
  g('venn-diagram', 'Venn diagram', 'trees-venn', [35], S3, 'Overlapping circles inside a rectangle showing events, their overlap, and outcomes in neither.', 'Picture of who is in which club.', 'Car rental: F only .11, both .31, B only .46, neither .12.', ['tree-diagram', 'and-event'], { visual: { type: 'venn', labels: ['F (sedan)', 'B (Bluetooth)'], onlyA: '.11', both: '.31', onlyB: '.46', neither: '.12' } }),
  g('contingency-table', 'Contingency (two-way) table', 'conditional', [35], S3, 'A table of counts for two categorical variables; great for conditional probabilities.', 'Rows × columns of who is who.', 'Superhero favorites by grade.', ['conditional-probability']),
  g('dot-array', 'Dot array', 'trees-venn', [33], S3, 'A grid showing all outcomes of two dice (6 × 6 = 36).', 'Every possible pair, one dot each.', 'Six dots on the diagonal give sum 7 → 6/36.', ['sample-space']),
  // ---------- Unit 5 ----------
  g('random-variable', 'Random variable', 'prob-dist', [28], S41, 'A variable whose value is a numerical outcome of a chance process (X).', 'A number decided by chance.', 'X = number of snow days in a school year.', ['discrete-rv', 'probability-distribution']),
  g('discrete-rv', 'Discrete random variable', 'prob-dist', [28, 3], S41, 'A random variable with countable values (typically whole numbers).', 'You can list the values.', 'X = number of Pirates movies seen (0–5).', ['random-variable', 'continuous-uniform']),
  g('probability-distribution', 'Probability distribution (PDF)', 'prob-dist', [28], S41, 'A table/graph listing each value of a random variable with its probability; every P(x) is between 0 and 1 and they sum to 1.', 'The full menu of outcomes with their odds.', 'Snow days distribution with P(0) = 0.33.', ['expected-value-term'], { mistake: 'Probabilities that don\'t add to 1.' }),
  g('expected-value-term', 'Expected value E(X)', 'expected-value', [28], S41, 'The mean of a random variable: Σ x·P(x) — the long-run average outcome.', 'What you average per play over a lifetime of plays.', 'Roulette: E(X) = −$5.26 per $100 bet.', ['probability-distribution', 'fair-game'], { formula: 'expected-value', aliases: ['expected value', 'mean of a random variable'] }),
  g('fair-game', 'Fair game', 'expected-value', [4], S41, 'A game with expected value 0: neither the player nor the house has an advantage.', 'Break-even in the long run.', 'Spinner grand prize of $20 makes E(X) = 0.', ['expected-value-term']),
  g('rv-sd', 'Standard deviation of a random variable (σ)', 'expected-value', [29, 3], S41, '√(Σx²P(x) − μ²): how much outcomes typically vary from the expected value.', 'Risk.', 'Roulette $100 bet: σ ≈ $99.86.', ['expected-value-term'], { formula: 'rv-variance' }),
  g('linear-transformation', 'Adding / multiplying constants', 'transform', [30], S41, 'Adding a constant shifts the center only; multiplying by a constant scales the center and the SD (variance by the square). Shape doesn\'t change.', 'Sliding vs. stretching the distribution.', 'A $5 fee lowers E(X) by $5 but leaves σ unchanged.', ['expected-value-term']),
  g('binomial-experiment', 'Binomial experiment', 'binomial', [25], S43, 'Two outcomes per trial (success/failure), a fixed number of trials n, independent trials, and the same probability of success p each trial.', 'Repeat the same yes/no gamble n times.', '10 multiple-choice questions answered by guessing.', ['binomial-distribution']),
  g('binomial-distribution', 'Binomial distribution', 'binomial', [25], S43, 'X ~ B(n, p): the number of successes in n binomial trials; μ = np, σ = √(npq).', 'How many heads in n flips — generalized.', 'X ~ B(10, 0.25) for the pop quiz.', ['binomial-experiment'], { formula: 'binom-mean-sd' }),
  g('success', 'Success / failure (p, q)', 'binomial', [25], S43, 'p = probability of the outcome being counted ("success"); q = 1 − p.', '"Success" just means "the thing we count" — even a red light.', 'Traffic lights: success = stopped, p = 0.30.', ['binomial-distribution']),
  g('continuous-uniform', 'Continuous uniform distribution', 'prob-dist', [3], S41, 'A continuous random variable equally likely anywhere on an interval [a, b].', 'Probability = fraction of the interval.', 'Y uniform 0–180: P(Y < 75) = 75/180.', ['discrete-rv'], { formula: 'uniform' }),
];

export const GLOSSARY_BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(GLOSSARY.map((e) => [e.id, e]));
