import type { Concept } from '../../engine/types';

const S3 = { pages: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 5, 6, 7, 8, 9], section: '3.1–3.5 Probability Topics' };

export const UNIT4: Concept[] = [
  {
    id: 'prob-basics', unit: 'u4', section: '3.1', title: 'Probability Basics',
    short: 'Experiments, sample spaces, events, and long-run relative frequency.',
    source: { ...S3, pages: [31, 36] }, prereqs: ['freq-tables'], related: ['prob-rules', 'prob-dist'],
    confusedWith: [{ id: 'freq-tables', why: 'Probability is a long-run relative frequency.' }],
    difficulty: 1, importance: 4, minutes: 12, dims: ['recognize', 'calculate', 'interpret', 'explain'],
    know: ['Probability experiment, outcome, sample space, event', 'Experimental vs. theoretical probability'], understand: ['Probability = long-run relative frequency; experimental → theoretical as trials increase'],
    calculate: ['P(A) = n(A)/n(S) for equally likely outcomes'], interpret: ['List a sample space; explain a probability in context'],
    misconceptions: ['prob-range', 'lln-gamblers'],
    why: { analogy: 'Flip a coin 10 times and you might get 7 heads. Flip it 10,000 times and you\'ll be very close to 50%. Probability describes the long run — like a basketball player\'s season free-throw percentage, not one game.', body: 'Individual random outcomes are unpredictable, but their long-run proportion settles down. That stable long-run proportion is what probability measures, and it\'s why casinos always win in the long run even though any single bet is uncertain.' },
    memoryTrick: 'P(A) = **want** ÷ **could**. Always between **0** (never) and **1** (certain).',
    lesson: [
      { kind: 'hook', title: 'Is the coin fair?', body: 'You flip a coin 10 times and get 7 heads. Is the coin unfair? What if you flipped it 1,000 times and got 700 heads?' },
      { kind: 'explain', title: 'The vocabulary', body: 'A **probability experiment** is a chance process with well-defined **outcomes**. The set of all outcomes is the **sample space** (S). An **event** is a set of outcomes meeting a condition. The **probability** of an event is its **long-term relative frequency** — always a fraction/decimal between **0 and 1**.\n\nWhen outcomes are equally likely: $P(A) = \\dfrac{\\text{outcomes in } A}{\\text{outcomes in } S}$.', source: { pages: [31, 36], section: S3.section } },
      { kind: 'check', prompt: 'Asking four people their favorite color and **counting how many say "red"**. What is the sample space?', input: { type: 'mc', options: [
        { id: 'a', text: '{0, 1, 2, 3, 4}', correct: true, why: 'We are counting reds among 4 people.' },
        { id: 'b', text: '{red, blue, green, …}', why: 'The outcome is a count of "red" answers, not a color.' },
        { id: 'c', text: '{1, 2, 3, 4}', why: 'Zero people could say red.' },
      ] }, explain: 'Define the outcome carefully: here it is a count, 0 through 4.' },
      { kind: 'explain', title: 'Experimental vs. theoretical', body: '**Experimental (empirical)** probability comes from running trials. **Theoretical (classical)** probability comes from the sample space before anything happens.\n\nAs the number of trials increases, the experimental probability gets **closer to the theoretical** probability (Lab #3).', source: { pages: [31], section: '3.1 (handwritten note)' } },
      { kind: 'interact', title: 'See it happen', widget: 'lln', prompt: 'Flip 10, then 100, then 1,000 coins (or roll dice). Watch the running proportion.', takeaway: 'Short runs bounce around; the long run settles near the theoretical probability.' },
      { kind: 'worked', title: 'Example 2 — one die', problem: 'S = {1, 2, 3, 4, 5, 6}. A = less than 5, B = even, C = rolling a 1.', steps: [
        { label: 'Events', body: 'A = {1, 2, 3, 4}, B = {2, 4, 6}, C = {1}.' },
        { label: 'P(C)', body: 'n(C)/n(S) = 1/6 ≈ 0.167.' },
      ], answer: 'P(C) = 1/6', source: { pages: [31], section: '3.1 Example 2' } },
      { kind: 'check', prompt: 'Two dice are rolled (36 equally likely outcomes). What is P(sum of 7)?', input: { type: 'number', answer: 6 / 36, tol: 0.002 }, explain: 'Six outcomes sum to 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) → 6/36 = **1/6**.' },
      { kind: 'summary', points: ['Sample space = all outcomes; event = outcomes you care about.', 'P(A) = n(A)/n(S) when equally likely; 0 ≤ P ≤ 1.', 'Experimental probability → theoretical as trials increase.'] },
    ],
    recall: [{ prompt: 'List the sample space for tossing two coins.', answer: 'S = {HH, HT, TH, TT}.' }],
    teach: {
      prompt: 'Explain what probability means, including sample spaces, events, and the difference between experimental and theoretical probability.',
      items: [
        { id: 'ss', idea: 'Sample space = all possible outcomes', patterns: ['sample space.{0,60}(all|every|possible)'], weight: 1 },
        { id: 'ev', idea: 'Event = set of outcomes', patterns: ['event.{0,60}(outcome|set|some)'], weight: 1 },
        { id: 'range', idea: 'Probability between 0 and 1', patterns: ['0.{0,20}1|zero.{0,20}one'], weight: 1 },
        { id: 'lr', idea: 'Long-run relative frequency', patterns: ['long.?(run|term)|many (trials|times)|repeat'], weight: 1 },
        { id: 'et', idea: 'Experimental vs. theoretical; experimental approaches theoretical', patterns: ['experimental.{0,120}theoretical|theoretical.{0,120}experimental'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['(balance|even) out', 'due for'], message: 'Chance has no memory — results don\'t "balance out" in the short run; only long-run proportions settle down.' }],
      model: 'A probability experiment is a chance process; its sample space is the set of all possible outcomes, and an event is a set of outcomes we care about. The probability of an event is its long-run relative frequency, a number between 0 and 1; with equally likely outcomes it is the number of outcomes in the event divided by the number in the sample space. Experimental probability comes from actual trials and theoretical probability from the sample space; as the number of trials increases, the experimental probability gets closer to the theoretical one.',
    },
    formulas: ['prob-equally'], glossary: ['probability-experiment', 'outcome', 'sample-space', 'event', 'probability', 'experimental-prob', 'theoretical-prob'],
  },
  {
    id: 'prob-rules', unit: 'u4', section: '3.1–3.3', title: 'Complement, "Or", "And"',
    short: 'The complement rule, the addition rule, and mutually exclusive events.',
    source: { ...S3, pages: [31, 32, 33, 35, 36, 37, 38, 6, 7] }, prereqs: ['prob-basics'], related: ['conditional', 'independence', 'trees-venn'],
    confusedWith: [{ id: 'independence', why: 'Mutually exclusive and independent are different ideas.' }],
    difficulty: 2, importance: 5, minutes: 14, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['P(A′) = 1 − P(A)', 'P(A or B) = P(A) + P(B) − P(A and B)', 'Mutually exclusive: P(A and B) = 0'], understand: ['"Or" double counts the overlap'],
    calculate: ['Complements, unions, intersections from lists, tables, and percentages'], interpret: ['Describe events like "O or H′" in words'],
    misconceptions: ['or-double-count', 'complement', 'indep-vs-mutex', 'prob-range'],
    why: { analogy: 'Counting people at a party who like pizza OR tacos: if you add the pizza lovers and the taco lovers, everyone who loves both got counted twice — so subtract them once.', body: 'P(A) + P(B) counts the overlap (A and B) twice. Subtracting P(A and B) fixes the double count. When events can\'t overlap (mutually exclusive), there is nothing to subtract.' },
    memoryTrick: '"**Or** → add, then subtract the double-counted middle." "**Not** → 1 minus."',
    lesson: [
      { kind: 'hook', title: 'Sports or extracurriculars?', body: 'A school has 300 students: 95 play a sport, 124 do an extracurricular, and 78 do both. A student is picked at random. What\'s the chance they do a sport **or** an extracurricular?' },
      { kind: 'predict', prompt: 'Someone answers (95 + 124)/300 = 0.73. What went wrong?', input: { type: 'mc', options: [
        { id: 'a', text: 'The 78 students who do both were counted twice', correct: true, why: 'Exactly — they are in both the 95 and the 124.' },
        { id: 'b', text: 'Nothing — "or" means add', why: '"Or" means add *and then subtract the overlap*.', misconception: 'or-double-count' },
      ] }, reveal: 'P(Sport or EC) = 95/300 + 124/300 − 78/300 = 141/300 = **0.47**.' },
      { kind: 'explain', title: 'The rules', body: '- **Complement**: $P(A\') = 1 - P(A)$ — everything not in A.\n- **A and B**: outcomes in **both** events.\n- **A or B**: outcomes in A, B, or both → $P(A \\text{ or } B) = P(A) + P(B) - P(A \\text{ and } B)$.\n- **Mutually exclusive** events cannot happen together: $P(A \\text{ and } B) = 0$, so $P(A \\text{ or } B) = P(A) + P(B)$.', source: { pages: [31, 32, 33], section: S3.section } },
      { kind: 'formula', formulaId: 'addition' },
      { kind: 'interact', title: 'Venn diagram sliders', widget: 'venn', prompt: 'Set P(A), P(B), and P(A and B). Watch each region, P(A or B), and P(neither). Try making the events mutually exclusive.', takeaway: 'The overlap is counted once. Mutually exclusive = no overlap.' },
      { kind: 'worked', title: 'Example 6 — MHS seniors', problem: '200 seniors: 140 plan college, 40 plan to work; 90 play a sport, 62 play a sport and plan college.', steps: [
        { label: 'College or work', body: 'Can\'t do both (as planned) → mutually exclusive → 140/200 + 40/200 = 180/200 = **0.9**.' },
        { label: 'Sport or college', body: 'Overlap of 62 → 90/200 + 140/200 − 62/200 = 168/200 = **0.84**.' },
      ], answer: 'Mutually exclusive: just add. Not mutually exclusive: subtract the overlap.', source: { pages: [33], section: '3.1–3.5 Example 6' } },
      { kind: 'check', prompt: 'Car rental: P(F) = 0.42, P(B) = 0.77, P(F and B) = 0.31. Find P(neither F nor B).', input: { type: 'number', answer: 0.12, tol: 0.001 }, explain: 'P(F or B) = 0.42 + 0.77 − 0.31 = 0.88 → P(neither) = 1 − 0.88 = **0.12**.' },
      { kind: 'check', prompt: 'Baseball: O = outfielder, H = great hitter. What does "O or H′" mean?', input: { type: 'mc', options: [
        { id: 'a', text: 'Selecting a player who is an outfielder or is not a great hitter', correct: true, why: 'H′ = not H; "or" = either one.' },
        { id: 'b', text: 'Selecting an outfielder who is not a great hitter', why: 'That is "O and H′".' },
        { id: 'c', text: 'Selecting an outfielder, given they are a great hitter', why: 'That is "O | H".' },
      ] }, explain: 'Read the symbols carefully: ′ = not, or = either, and = both, | = given.' },
      { kind: 'summary', points: ['P(A′) = 1 − P(A).', 'P(A or B) = P(A) + P(B) − P(A and B).', 'Mutually exclusive → P(A and B) = 0.'] },
    ],
    recall: [{ prompt: 'Write the addition rule and say when the last term is zero.', answer: 'P(A or B) = P(A) + P(B) − P(A and B); the last term is 0 when A and B are mutually exclusive.' }],
    teach: {
      prompt: 'Explain the complement rule and the addition rule, and what "mutually exclusive" means.',
      items: [
        { id: 'comp', idea: 'P(not A) = 1 − P(A)', patterns: ['1 ?(-|−|minus) ?p|one minus'], weight: 1 },
        { id: 'add', idea: 'Add then subtract the overlap', patterns: ['subtract|minus.{0,40}(both|and|overlap)|double'], weight: 1.5 },
        { id: 'me', idea: 'Mutually exclusive = can\'t happen together, overlap 0', patterns: ['mutually exclusive.{0,100}(can.t|cannot|not.{0,20}same time|no overlap|zero|0)'], weight: 1.5 },
      ],
      misconceptions: [{ patterns: ['mutually exclusive.{0,40}independent'], message: 'Mutually exclusive is not the same as independent.' }],
      model: 'The complement rule says P(not A) = 1 − P(A). The addition rule says P(A or B) = P(A) + P(B) − P(A and B): adding P(A) and P(B) counts the outcomes in both events twice, so we subtract the overlap once. Events are mutually exclusive if they can\'t happen at the same time; then P(A and B) = 0 and P(A or B) is simply P(A) + P(B).',
    },
    formulas: ['complement', 'addition'], glossary: ['complement-term', 'and-event', 'or-event', 'mutually-exclusive'],
  },
  {
    id: 'conditional', unit: 'u4', section: '3.2–3.3', title: 'Conditional Probability',
    short: 'P(A | B): the given event becomes the new sample space.',
    source: { ...S3, pages: [31, 32, 35, 37, 40, 5, 6, 8, 9] }, prereqs: ['prob-rules'], related: ['independence', 'trees-venn'],
    confusedWith: [{ id: 'trees-venn', why: 'Reverse conditional probabilities often come from tree diagrams.' }],
    difficulty: 3, importance: 5, minutes: 14, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['P(A | B) = P(A and B)/P(B)'], understand: ['Conditioning shrinks the sample space to the given event'],
    calculate: ['Conditional probabilities from contingency tables and percentages'], interpret: ['Describe "O | H" in words; interpret P(C | S) in context'],
    misconceptions: ['cond-reversed', 'cond-grand-total'],
    why: { analogy: 'Of all students, 30/84 like Spiderman. But **of the 10th graders**, 8/22 do. "Given 10th grade" means you stop looking at the whole school and only look inside the 10th-grade row.', body: 'Knowing B happened rules out every outcome outside B. The only outcomes left are those in B, so B\'s total becomes the denominator, and only the part of A inside B counts in the numerator.' },
    memoryTrick: '"**Given** goes **under**." The event after the bar | is your new denominator.',
    lesson: [
      { kind: 'hook', title: 'Favorite subjects', body: 'Mr. Halter\'s students named their favorite subject. If you know a student is a **non-senior**, what\'s the chance their favorite is Math?', visual: { type: 'table', headers: ['', 'Seniors', 'Non-Seniors', 'Total'], rows: [['English', 13, 5, 18], ['Math', 8, 11, 19], ['Science', 15, 2, 17], ['Soc. Studies', 14, 7, 21], ['Total', 50, 25, 75]], rowHeaders: true, caption: 'p.32 Example 3' } },
      { kind: 'predict', prompt: 'P(Math | non-senior) = ?', input: { type: 'mc', options: [
        { id: 'a', text: '11/25', correct: true, why: 'Only the 25 non-seniors count; 11 of them chose Math.' },
        { id: 'b', text: '11/75', why: 'That is P(Math and non-senior) — the grand total is the wrong denominator.', misconception: 'cond-grand-total' },
        { id: 'c', text: '11/19', why: 'That is P(non-senior | Math) — the condition is reversed.', misconception: 'cond-reversed' },
      ] }, reveal: '"Given non-senior" → change the sample space to the 25 non-seniors → **11/25**.' },
      { kind: 'explain', title: 'Conditional probability', body: 'The probability of A **given** that B has already occurred:\n$$P(A \\mid B) = \\frac{P(A \\text{ and } B)}{P(B)}$$\nA conditional probability **reduces the sample space** to only the outcomes in the "given" event.', source: { pages: [31], section: S3.section } },
      { kind: 'interact', title: 'Condition on a row or column', widget: 'contingency', props: { table: 'superheroes' }, prompt: 'Click a row or column to "give" it. Watch the sample space shrink and the conditional probabilities update.', takeaway: 'Conditioning = zooming into one row or column.' },
      { kind: 'check', prompt: 'Olympic medals: Japan won 58 medals, 14 of them silver. P(silver | Japan)?', input: { type: 'number', answer: 14 / 58, tol: 0.002 }, explain: '14/58 = 7/29 ≈ **0.2414**.' },
      { kind: 'check', prompt: '73% of club members play poker AND swim; 82% play poker. P(swim | poker)?', input: { type: 'number', answer: 0.73 / 0.82, tol: 0.002 }, explain: '0.73/0.82 ≈ **0.8902**.' },
      { kind: 'worked', title: 'Practice #13 — Pew mothers', problem: 'Mothers surveyed in 1976, 1994, 2014 (100 each). 4+ children: 40, 13, 13.', steps: [
        { label: 'P(4+ | 2014)', body: 'Only the 100 mothers from 2014 count → 13/100 = 0.13.' },
        { label: 'Interpret', body: 'There is a 0.13 chance of selecting a mother with four or more children, **given** she was surveyed in 2014.' },
        { label: 'P(4+ | not 1976)', body: 'New sample space: 1994 or 2014 (200 mothers) → (13 + 13)/200 = 0.13.' },
      ], answer: 'Identify the given event, then divide by its total.', source: { pages: [8, 9], section: '3.1–3.5 Practice #13' } },
      { kind: 'summary', points: ['P(A | B) = P(A and B)/P(B).', 'Given event = new sample space (denominator).', 'P(A | B) ≠ P(B | A) in general.'] },
    ],
    recall: [{ prompt: 'In P(A | B), which event is the denominator, and why?', answer: 'B — knowing B occurred shrinks the sample space to B.' }],
    teach: {
      prompt: 'Explain conditional probability, how to compute it from a two-way table, and a common mistake.',
      items: [
        { id: 'def', idea: 'Probability of A given B occurred', patterns: ['given|already (happened|occurred)'], weight: 1 },
        { id: 'formula', idea: 'P(A and B)/P(B)', patterns: ['and.{0,30}(divid|over|÷|\\/).{0,30}p ?\\(?b|both.{0,40}divid'], weight: 1 },
        { id: 'space', idea: 'Given event becomes the sample space / denominator', patterns: ['sample space|denominator|only (look|consider)|row total|column total|shrink|reduc'], weight: 1.5 },
        { id: 'mistake', idea: 'Common mistake: dividing by the grand total or reversing', patterns: ['grand total|reverse|wrong total|backwards|not the same as'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['divid.{0,30}(by )?(the )?(grand )?total of (everyone|all)'], message: 'For a conditional probability, divide by the given event\'s total — not the grand total.' }],
      model: 'A conditional probability P(A | B) is the probability of A given that B has already happened. It equals P(A and B) ÷ P(B). Knowing B happened shrinks the sample space to B, so in a two-way table you go to B\'s row or column, and divide the count in both A and B by B\'s total. A common mistake is dividing by the grand total, or reversing the condition — P(A | B) is usually not the same as P(B | A).',
    },
    formulas: ['conditional'], glossary: ['conditional-probability', 'contingency-table'],
  },
  {
    id: 'independence', unit: 'u4', section: '3.2–3.3', title: 'Independence & the Multiplication Rule',
    short: 'P(A and B), with and without replacement, and "at least one".',
    source: { ...S3, pages: [32, 33, 35, 37, 38, 5, 6, 7, 8] }, prereqs: ['conditional'], related: ['trees-venn', 'binomial', 'prob-rules'],
    confusedWith: [{ id: 'prob-rules', why: 'Independent ≠ mutually exclusive.' }],
    difficulty: 3, importance: 5, minutes: 16, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['Independent: P(A) = P(A | B) ⇔ P(A and B) = P(A)·P(B)', 'Dependent: P(A and B) = P(A)·P(B | A)'], understand: ['With replacement → independent; without → dependent', 'Independent ≠ mutually exclusive'],
    calculate: ['Repeated independent trials; at least one = 1 − P(none); test independence in a table'], interpret: ['Justify independence with a calculation'],
    misconceptions: ['indep-vs-mutex', 'without-replacement', 'at-least-one'],
    why: { analogy: 'A coin has no memory: getting heads doesn\'t change the next flip. But drawing cards *without putting them back* does change the deck — one fewer heart left makes the next heart less likely.', body: 'Independence means learning that B happened gives no information about A, so P(A | B) = P(A). Then the multiplication rule simplifies to P(A)·P(B). "At least one" is easiest through the complement, because "none" is a single path of all failures.' },
    memoryTrick: '"**And → multiply.** At least one → **1 − none**." Independent: "**knowing doesn\'t change**."',
    lesson: [
      { kind: 'hook', title: 'Two hearts in a row', body: 'Draw two cards from a standard deck. What\'s the probability both are hearts — and does it matter whether you put the first card back?' },
      { kind: 'explain', title: 'Independent vs. dependent', body: 'Events are **independent** if the probability of one does not affect the probability of the other.\n\n> If A and B are independent, then **P(A) = P(A | B)**, since **P(A and B) = P(A)·P(B)**.\n\nIn general (dependent events): $P(A \\text{ and } B) = P(A)\\cdot P(B \\mid A)$.', source: { pages: [32, 33], section: S3.section } },
      { kind: 'worked', title: 'Example 5 — hearts', problem: 'A = heart on 1st card, B = heart on 2nd card.', steps: [
        { label: 'With replacement', body: 'Independent: (13/52)(13/52) = 1/16 = **0.0625**.' },
        { label: 'Without replacement', body: 'Dependent: (13/52)(12/51) = 1/17 ≈ **0.0588** — one fewer heart and one fewer card.' },
      ], answer: 'Replacement keeps draws independent.', source: { pages: [33], section: '3.1–3.5 Example 5' } },
      { kind: 'check', prompt: 'P(Spanish) = 0.75, P(German) = 0.2, P(Spanish and German) = 0.15. Are S and G independent?', input: { type: 'mc', options: [
        { id: 'a', text: 'Yes, because 0.75 × 0.2 = 0.15 = P(S and G)', correct: true, why: 'The multiplication rule holds exactly.' },
        { id: 'b', text: 'No, because students can learn both languages', why: 'Overlapping events can still be independent — that\'s the mutually exclusive idea, not independence.', misconception: 'indep-vs-mutex' },
      ] }, explain: 'Check P(A)·P(B) = P(A and B). Equivalently P(G | S) = 0.15/0.75 = 0.2 = P(G).' },
      { kind: 'explain', title: '"At least one"', body: 'For repeated independent trials:\n$$P(\\text{at least one}) = 1 - P(\\text{none})$$\nVideo game: 15% chance per fight of a special enemy, 5 independent fights → P(at least one) = 1 − 0.85⁵ = **0.5563**.', source: { pages: [8], section: '3.1–3.5 Practice #10' } },
      { kind: 'check', prompt: '60% of PhD students have a TA role. Select 5 at random. P(**none** have a TA role)?', input: { type: 'number', answer: 0.4 ** 5, tol: 0.0005 }, explain: '(0.40)⁵ = **0.01024**.' },
      { kind: 'check', prompt: 'Superheroes: P(Spiderman) = 30/84 ≈ 0.357, P(Spiderman | 10th) = 8/22 ≈ 0.364. Are favorite hero and grade independent?', input: { type: 'mc', options: [
        { id: 'a', text: 'No — P(A) ≠ P(A | B), so they are dependent', correct: true, why: 'The course\'s test: compare P(A) with P(A | B).' },
        { id: 'b', text: 'Yes — the numbers are close', why: 'For the course, unequal means dependent.' },
      ] }, explain: 'Compare P(A) and P(A | B): unequal → dependent.' },
      { kind: 'interact', title: 'Dice dot array', widget: 'dice', prompt: 'Select events on the 6×6 dot array. Check independence of "first die is even" and "sum is 7".', takeaway: 'Two dice are independent; some events built from them are too.' },
      { kind: 'summary', points: ['Independent: P(A | B) = P(A) ⇔ P(A and B) = P(A)P(B).', 'Without replacement → dependent.', 'At least one = 1 − P(none).', 'Mutually exclusive events (with P > 0) are dependent.'] },
    ],
    recall: [{ prompt: 'Explain why mutually exclusive events (with nonzero probabilities) can\'t be independent.', answer: 'If one happens, the other can\'t — so knowing A happened changes P(B) to 0. That is dependence.' }],
    teach: {
      prompt: 'Explain what independent events are, how to check independence, and how independence differs from mutually exclusive.',
      items: [
        { id: 'def', idea: 'One event doesn\'t affect the other\'s probability', patterns: ['(doesn.t|does not|not) (affect|change|influence)'], weight: 1 },
        { id: 'check', idea: 'Check P(A) = P(A | B) or P(A and B) = P(A)P(B)', patterns: ['p ?\\(?a ?\\)? ?= ?p ?\\(?a ?(\\||given)|multipl|times|×|\\*'], weight: 1.5 },
        { id: 'me', idea: 'Different from mutually exclusive (can\'t happen together)', patterns: ['mutually exclusive.{0,100}(different|not the same|can.t|cannot|dependent)'], weight: 1.5 },
        { id: 'rep', idea: 'With vs. without replacement', patterns: ['replace'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['independent.{0,40}(means|=).{0,20}(can.t|cannot) happen'], message: 'Can\'t-happen-together is mutually exclusive, not independent.' }],
      model: 'Two events are independent if one happening does not change the probability of the other. To check, compare P(A) with P(A | B) — or check whether P(A and B) = P(A)·P(B). Mutually exclusive is different: those events can\'t happen at the same time, so P(A and B) = 0. In fact, mutually exclusive events with nonzero probabilities are dependent, because if one happens the other becomes impossible. Drawing with replacement keeps draws independent; without replacement makes them dependent.',
    },
    formulas: ['multiplication', 'at-least-one'], glossary: ['independent', 'replacement'],
  },
  {
    id: 'trees-venn', unit: 'u4', section: '3.4–3.5', title: 'Tree Diagrams & Venn Diagrams',
    short: 'Visualizing sample spaces: multiply along branches, add across paths.',
    source: { ...S3, pages: [33, 34, 35, 38, 39, 40, 6, 7, 8] }, prereqs: ['conditional', 'independence'], related: ['binomial', 'prob-rules'],
    confusedWith: [{ id: 'conditional', why: '"Given the result, which branch?" is a reverse conditional.' }],
    difficulty: 4, importance: 4, minutes: 18, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['Tree branches multiply; paths add', 'Venn regions: only A, both, only B, neither', 'Dot arrays for two dice'], understand: ['Total probability and "reverse" conditional probability from a tree'],
    calculate: ['Path probabilities, total probability, P(first stage | second stage)'], interpret: ['Build a tree or Venn diagram from a description or table'],
    misconceptions: ['tree-add-along', 'venn-only', 'cond-reversed'],
    why: { analogy: 'A tree diagram is a choose-your-own-adventure map. Each route\'s probability is the product of its turns. To find "ended up late", add up every route that ends in "late".', body: 'Multiplying along a path applies the multiplication rule step by step; adding paths applies the addition rule to outcomes that can\'t happen together (different paths are mutually exclusive). A reverse question ("given late, which mode?") divides one path by the total of all matching paths.' },
    memoryTrick: '**Multiply down, add across.** Reverse question → **path ÷ total of matching paths**.',
    lesson: [
      { kind: 'hook', title: 'The flu test', body: '22% of urgent-care patients have the flu. A rapid test misses 3.7% of flu cases and falsely flags 2.6% of healthy patients.\n\nYou test **positive**. How likely is it you actually have the flu?' },
      { kind: 'predict', prompt: 'Guess P(flu | positive test).', input: { type: 'slider', min: 0, max: 1, step: 0.01, answer: 0.9126, tol: 0.1, label: 'probability' }, reveal: 'It\'s about **0.913** — high, but not 0.963. Some positives come from the large healthy group. A tree diagram shows why.' },
      { kind: 'explain', title: 'Tree diagrams', body: 'Each branch shows a probability; branches from one point add to 1.\n- **Multiply along** a path → probability of that sequence.\n- **Add across** paths that satisfy the event.', visual: { type: 'tree', root: { label: 'Patient', children: [{ label: 'Flu', p: '0.22', children: [{ label: 'Test +', p: '0.963' }, { label: 'Test −', p: '0.037' }] }, { label: 'No flu', p: '0.78', children: [{ label: 'Test +', p: '0.026' }, { label: 'Test −', p: '0.974' }] }] } }, source: { pages: [34, 8], section: S3.section } },
      { kind: 'interact', title: 'Work the tree', widget: 'tree', props: { preset: 'flu' }, prompt: 'Click any leaf to see its path probability. Pick an event (e.g. "Test +") to add matching paths, then condition on it.', takeaway: 'P(+) = 0.22(0.963) + 0.78(0.026) = 0.2321; P(flu | +) = 0.2119/0.2321 ≈ 0.913.' },
      { kind: 'worked', title: 'Practice #9 — Jed\'s commute', problem: 'Car 0.30 (late 0.03), walk 0.30 (late 0.10), bus 0.40 (late 0.07).', steps: [
        { label: 'Car and late', body: '(0.30)(0.03) = 0.009.' },
        { label: 'Late (total)', body: '0.009 + (0.30)(0.10) + (0.40)(0.07) = 0.067.' },
        { label: 'Bus | late', body: '(0.40)(0.07)/0.067 = 0.028/0.067 ≈ 0.4179.' },
        { label: 'Walk | on time', body: '(0.30)(0.90)/(1 − 0.067) ≈ 0.2894.' },
      ], answer: 'Multiply down, add across, divide for reverse questions.', source: { pages: [7], section: '3.1–3.5 Practice #9' } },
      { kind: 'check', prompt: 'Duck pools: roll 1–4 → Pool 1 (8 red, 2 gold); roll 5–6 → Pool 2 (3 red, 7 gold). P(gold)?', input: { type: 'number', answer: 11 / 30, tol: 0.002 }, explain: '(2/3)(2/10) + (1/3)(7/10) = 4/30 + 7/30 = **11/30 ≈ 0.367**.' },
      { kind: 'explain', title: 'Venn diagrams', body: 'For overlapping events, a Venn diagram splits the rectangle into: **only A**, **A and B**, **only B**, **neither**.\n\nCar rental: P(F) = .42, P(B) = .77, P(F and B) = .31 → only F = .11, both = .31, only B = .46, neither = .12.', visual: { type: 'venn', labels: ['F (4-door sedan)', 'B (Bluetooth)'], onlyA: '.11', both: '.31', onlyB: '.46', neither: '.12' }, source: { pages: [35], section: S3.section } },
      { kind: 'check', prompt: 'AP survey (116 students): 58 take AP and procrastinate, 12 take AP only, 24 procrastinate only, 22 neither. P(takes AP and does **not** procrastinate)?', input: { type: 'number', answer: 12 / 116, tol: 0.002 }, explain: 'That\'s the "only X" region: 12/116 = 3/29 ≈ **0.1034**.' },
      { kind: 'summary', points: ['Trees: multiply along, add across.', 'Reverse conditional = path ÷ sum of matching paths.', 'Venn: only A, both, only B, neither (sum to 1).'] },
    ],
    recall: [{ prompt: 'On a tree diagram, when do you multiply and when do you add?', answer: 'Multiply along a branch path (and); add the probabilities of different paths that satisfy the event (or).' }],
    teach: {
      prompt: 'Explain how to use a tree diagram to find (a) the probability of an outcome that can happen several ways and (b) a "reverse" conditional probability.',
      items: [
        { id: 'mult', idea: 'Multiply along branches', patterns: ['multipl.{0,60}(along|branch|path)'], weight: 1.5 },
        { id: 'add', idea: 'Add the matching paths', patterns: ['add.{0,60}(path|branch|ways)'], weight: 1.5 },
        { id: 'rev', idea: 'Reverse conditional = path ÷ total of matching paths', patterns: ['divid|over|÷'], weight: 1 },
        { id: 'sum1', idea: 'Branches from a point sum to 1', patterns: ['(add|sum).{0,30}(to )?(1|one)'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['add.{0,40}along'], message: 'Probabilities are multiplied along a path, not added.' }],
      model: 'In a tree diagram, each branch shows a probability, and the branches from one point add to 1. To find the probability of one route, multiply the probabilities along its branches. If an event can happen several ways (like testing positive with or without the flu), add the probabilities of all the paths that end in that event. For a reverse conditional — like P(flu | positive) — divide the probability of the path you care about by the total probability of all paths that match the given result.',
    },
    formulas: ['conditional', 'multiplication'], glossary: ['tree-diagram', 'venn-diagram', 'dot-array'],
  },
];
