import type { Concept } from '../../engine/types';

const S11 = { pages: [64, 65, 66], section: '1.1–1.2 Key Terms, Sampling, and Variation' };
const S13 = { pages: [60, 61, 62, 63], section: '1.3–1.4 Frequency Tables, Experimental Design, Ethics' };

export const UNIT1: Concept[] = [
  {
    id: 'pop-sample', unit: 'u1', section: '1.1–1.2', title: 'Population, Sample, Parameter & Statistic',
    short: 'The six words every statistics problem starts with.',
    source: { ...S11, pages: [64, 66, 1] },
    prereqs: [], related: ['data-types', 'sampling', 'investigative'],
    confusedWith: [{ id: 'sampling', why: 'Knowing *what* a sample is differs from knowing *how* to choose one.' }],
    difficulty: 1, importance: 5, minutes: 10, dims: ['recognize', 'interpret', 'apply', 'explain'],
    know: ['Definitions of statistics, data, variable, population, sample, statistic, parameter'],
    understand: ['We compute statistics from samples to estimate unknown population parameters'],
    calculate: [],
    interpret: ['Identify all six terms in a real scenario'],
    misconceptions: ['param-vs-stat', 'variable-vs-data', 'sample-is-population'],
    why: {
      analogy: 'Tasting soup: you don\'t drink the whole pot (population) — you taste a spoonful (sample). How salty that spoonful is (statistic) is your best guess for how salty the whole pot is (parameter).',
      body: 'Studying an entire population is usually too costly, slow, or impossible. A well-chosen sample lets us compute a **statistic** that estimates the unknown **parameter**. That is the whole game of statistics: learn about the many from the few.',
    },
    memoryTrick: '**P**opulation → **P**arameter. **S**ample → **S**tatistic. The letters match.',
    lesson: [
      { kind: 'hook', title: 'How much do families spend on uniforms?', body: 'Knoll Academy wants to know the **average amount families spend on school uniforms each year**. There are hundreds of families. Nobody has time to ask all of them.\n\nSo they randomly survey **100 families**. Three of them spent $65, $75, and $95.\n\nWhat can 100 families tell us about *all* of them?' },
      { kind: 'predict', prompt: 'The school computes the average of the 100 surveyed families. Is that number the true average for **every** Knoll Academy family?', input: { type: 'mc', options: [
        { id: 'a', text: 'Yes — it is the exact average for all families', why: 'Only the families who were surveyed went into the calculation. Other families might spend more or less.', misconception: 'param-vs-stat' },
        { id: 'b', text: 'No — it is an estimate of the average for all families', correct: true, why: 'Right. It comes from a sample, so it estimates the population value.' },
        { id: 'c', text: 'It can\'t tell us anything about other families', why: 'A random sample is exactly what lets us estimate things about the whole group.' },
      ] }, reveal: 'A number from a **sample** is our best **estimate** of the number for the whole **population**. Statisticians have special words for each piece.' },
      { kind: 'explain', title: 'The six key words', body: '**Statistics** is the science of collecting, organizing, summarizing, analyzing, and presenting **data**.\n\n- **Population**: the *entire* group we want to know about → all Knoll Academy families.\n- **Sample**: the subset we actually study → the 100 surveyed families.\n- **Variable**: the characteristic measured on each one → *amount spent on uniforms*.\n- **Data**: the actual values → $65, $75, $95, …\n- **Statistic**: a number computed from the **sample** → the mean of the 100 families.\n- **Parameter**: the matching number for the **population** → the mean for *all* families (unknown).', source: { pages: [64], section: S11.section } },
      { kind: 'check', prompt: 'A cardiologist is interested in the mean recovery period of her patients who have had heart attacks. She reviews 40 of their records. What is the **parameter**?', input: { type: 'mc', options: [
        { id: 'a', text: 'The mean recovery period of all her heart-attack patients', correct: true, why: 'A parameter describes the whole population.' },
        { id: 'b', text: 'The mean recovery period of the 40 reviewed patients', why: 'That is computed from the sample, so it is a statistic.', misconception: 'param-vs-stat' },
        { id: 'c', text: 'The recovery period of one patient', why: 'That is a single data value.', misconception: 'variable-vs-data' },
        { id: 'd', text: 'Recovery period', why: 'That is the variable — the characteristic being measured.', misconception: 'variable-vs-data' },
      ] }, explain: 'Parameter ↔ population: *all* her heart-attack patients. The mean of the 40 records is the statistic that estimates it.' },
      { kind: 'worked', title: 'Exam #1 Review — Federal contractors', problem: 'A study looks at the **mean yearly salary of all Federal contractors in D.C.** by collecting salaries from selected contractors.', steps: [
        { label: 'Population', body: 'All Federal contractors in D.C.' },
        { label: 'Sample', body: 'The selected Federal contractors in D.C.' },
        { label: 'Parameter', body: 'Mean yearly salary of **all** Federal contractors in D.C.' },
        { label: 'Statistic', body: 'Mean yearly salary of the **selected** Federal contractors.' },
        { label: 'Variable', body: 'Possible yearly salaries of Federal contractors in D.C.' },
        { label: 'Data', body: 'The individual yearly salaries of the selected contractors.' },
      ], answer: 'Notice the pattern: parameter and statistic are the *same calculation* applied to different groups.', source: { pages: [1], section: 'Exam #1 Review KEY #1a' } },
      { kind: 'check', prompt: 'A Lake Tahoe Community College instructor finds that her sample of math students was absent a mean of **3.5 days**. The 3.5 days is a…', input: { type: 'mc', options: [
        { id: 'a', text: 'Statistic', correct: true, why: 'It was computed from a sample.' },
        { id: 'b', text: 'Parameter', why: 'It came from a sample, not all LTCC math students.', misconception: 'param-vs-stat' },
        { id: 'c', text: 'Variable', why: 'The variable is "number of days absent"; 3.5 is a computed number.', misconception: 'variable-vs-data' },
      ] }, explain: 'The sample mean of 3.5 days is a **statistic**. It estimates the parameter: the mean days absent for **all** LTCC math students.' },
      { kind: 'recall', prompt: 'Without looking: what is the difference between a parameter and a statistic? Give the memory trick.', answer: 'A **parameter** describes a **population**; a **statistic** is computed from a **sample** (and estimates the parameter). P ↔ P, S ↔ S.' },
      { kind: 'summary', points: ['Population = everyone you care about; sample = who you actually measured.', 'Statistic (sample) estimates parameter (population).', 'Variable = the characteristic; data = the recorded values.'] },
    ],
    recall: [
      { prompt: 'Define population and sample, then give an example of each from the Knoll Academy study.', answer: 'Population: all families with children at Knoll Academy. Sample: the 100 surveyed families.' },
      { prompt: 'Is the proportion of 500 surveyed voters who support a law a statistic or a parameter? Why?', answer: 'A statistic — it is computed from a sample (the 500 voters) and estimates the population proportion.' },
    ],
    teach: {
      prompt: 'Explain the difference between a population, a sample, a parameter, and a statistic — as if teaching a classmate. Use an example.',
      items: [
        { id: 'pop', idea: 'Population is the entire group of interest', patterns: ['entire|whole|all (the )?(people|members|group|families|students)', 'everyone'], weight: 1 },
        { id: 'samp', idea: 'Sample is a subset that is actually studied', patterns: ['subset|part of|portion|smaller group|selected|some of'], weight: 1 },
        { id: 'stat', idea: 'A statistic is computed from the sample', patterns: ['statistic.{0,60}sample|sample.{0,60}statistic'], weight: 1 },
        { id: 'param', idea: 'A parameter describes the population', patterns: ['parameter.{0,60}population|population.{0,60}parameter'], weight: 1 },
        { id: 'estimate', idea: 'Statistics are used to estimate parameters', patterns: ['estimat|approximat|guess|infer'], weight: 1 },
        { id: 'example', idea: 'Gives a concrete example', patterns: ['for example|e\\.g\\.|such as|like |imagine|suppose'], weight: 0.5 },
      ],
      misconceptions: [
        { patterns: ['parameter.{0,40}(from|of) (the )?sample', 'statistic.{0,40}(of|describes) (the )?(whole|entire) population'], message: 'Parameters belong to populations and statistics to samples — it sounds reversed here.' },
      ],
      model: 'A **population** is the entire group we want to learn about, like all families at Knoll Academy. Because asking everyone is too costly, we study a **sample** — a smaller subset, like 100 randomly chosen families. A number computed from the sample (their average spending) is a **statistic**; the same number for the whole population is a **parameter**, which is usually unknown. We use the statistic to estimate the parameter.',
    },
    formulas: [], glossary: ['statistics', 'data', 'variable', 'population', 'sample', 'statistic', 'parameter'],
  },
  {
    id: 'data-types', unit: 'u1', section: '1.1–1.2', title: 'Types of Data',
    short: 'Categorical vs. quantitative; discrete vs. continuous.',
    source: { ...S11, pages: [64, 66, 1] },
    prereqs: ['pop-sample'], related: ['cat-displays', 'quant-graphs', 'prob-dist'],
    confusedWith: [{ id: 'prob-dist', why: 'Discrete vs. continuous returns for random variables in Unit 5.' }],
    difficulty: 1, importance: 4, minutes: 8, dims: ['recognize', 'apply', 'explain'],
    know: ['Categorical (qualitative) vs. quantitative', 'Discrete vs. continuous'],
    understand: ['The type of data decides which graphs and summaries make sense'],
    calculate: [], interpret: ['Classify a variable and give example data'],
    misconceptions: ['numbers-are-quantitative', 'discrete-vs-continuous'],
    why: {
      analogy: 'Think of a video game character sheet: **Class** = Wizard (categorical — a label). **Level** = 12 (discrete — you can count levels). **Height** = 1.83 m (continuous — any value in between is possible).',
      body: 'The type of data decides everything that comes next: you can average heights but not favorite teams; you draw bar graphs for categories and histograms for numbers. Classifying first prevents using the wrong tool.',
    },
    memoryTrick: '**Count it → discrete. Measure it → continuous. Label it → categorical.**',
    lesson: [
      { kind: 'hook', title: 'Can you average a jersey number?', body: 'A basketball team\'s players wear jersey numbers 3, 11, 23, and 30. The average jersey number is 16.75.\n\nDoes "16.75" tell you anything about the team?' },
      { kind: 'predict', prompt: 'Jersey numbers are written with digits. What type of data are they?', input: { type: 'mc', options: [
        { id: 'a', text: 'Quantitative — they are numbers', why: 'They are digits, but they act as **labels**. Averaging them is meaningless.', misconception: 'numbers-are-quantitative' },
        { id: 'b', text: 'Categorical — they are labels', correct: true, why: 'Exactly. The test: does arithmetic on them make sense? No → categorical.' },
      ] }, reveal: 'Digits don\'t make data quantitative. **Quantitative** data measure or count something, so arithmetic makes sense.' },
      { kind: 'explain', title: 'Two families of data', body: '**Categorical (qualitative)** data place individuals into groups or labels: favorite team, toothpaste brand, most-watched TV show.\n\n**Quantitative** data are numbers that count or measure:\n- **Discrete**: countable values, usually "number of…" → tickets sold, students enrolled.\n- **Continuous**: any value in an interval, usually measurements → time in line, percent body fat, distance, age.', source: { pages: [64], section: S11.section } },
      { kind: 'check', prompt: '**Percent of body fat** is…', input: { type: 'mc', options: [
        { id: 'a', text: 'Quantitative continuous', correct: true, why: 'It is measured and can be any value like 18.37%.' },
        { id: 'b', text: 'Quantitative discrete', why: 'Body fat is measured, not counted.', misconception: 'discrete-vs-continuous' },
        { id: 'c', text: 'Categorical', why: 'Averaging body-fat percentages makes sense, so it is quantitative.' },
      ] }, explain: 'Measurement → continuous.' },
      { kind: 'check', prompt: '**Number of students enrolled** at Evergreen Valley College is…', input: { type: 'mc', options: [
        { id: 'a', text: 'Quantitative discrete', correct: true, why: 'It is a count — you can\'t have 4,512.6 students.' },
        { id: 'b', text: 'Quantitative continuous', why: 'Counts are discrete.', misconception: 'discrete-vs-continuous' },
        { id: 'c', text: 'Categorical', why: 'It is a number you can do arithmetic with.' },
      ] }, explain: '"Number of…" → discrete.' },
      { kind: 'worked', title: 'Practice 1.1–1.2 #3 — classify each', problem: 'Identify the type of data.', steps: [
        { label: 'Tickets sold to a concert', body: 'Quantitative discrete (a count).' },
        { label: 'Favorite baseball team', body: 'Categorical (a label).' },
        { label: 'Time in line to buy groceries', body: 'Quantitative continuous (a measurement).' },
        { label: 'Brand of toothpaste', body: 'Categorical.' },
        { label: 'Distance to the closest movie theatre', body: 'Quantitative continuous.' },
        { label: 'Age of executives in Fortune 500 companies', body: 'Quantitative continuous — age is a measurement of time.' },
      ], answer: 'Ask: label? count? or measurement?', source: { pages: [66, 1], section: '1.1–1.2 Practice #3; Exam #1 Review #2' } },
      { kind: 'recall', prompt: 'Give one example each of categorical, discrete, and continuous data about yourself.', answer: 'Example: favorite food (categorical), number of siblings (discrete), height (continuous).' },
      { kind: 'summary', points: ['Categorical = labels (even if written with digits).', 'Discrete = counts. Continuous = measurements.', 'Type of data → which graphs and statistics are allowed.'] },
    ],
    recall: [{ prompt: 'What test tells you whether numeric-looking data are actually categorical?', answer: 'Ask whether arithmetic (like averaging) makes sense. If not, the data are categorical labels.' }],
    teach: {
      prompt: 'Explain how to tell categorical, discrete, and continuous data apart. Include an example of each.',
      items: [
        { id: 'cat', idea: 'Categorical data are labels/groups', patterns: ['categor.{0,40}(label|group|categor|name|quality)', 'qualitative'], weight: 1 },
        { id: 'quant', idea: 'Quantitative data are numbers that count or measure', patterns: ['quantitative.{0,60}(number|count|measur)'], weight: 1 },
        { id: 'disc', idea: 'Discrete = countable values', patterns: ['discrete.{0,60}(count|whole|integer|list)'], weight: 1 },
        { id: 'cont', idea: 'Continuous = any value in an interval (measurements)', patterns: ['continuous.{0,60}(any value|measur|decimal|in between|interval|infinite)'], weight: 1 },
        { id: 'trap', idea: 'Numbers used as labels are categorical', patterns: ['zip|jersey|phone number|label.{0,30}number|average.{0,30}(meaningless|make sense|doesn.t)'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['continuous.{0,40}count', 'discrete.{0,40}(measur|any value)'], message: 'Counts are discrete and measurements are continuous — this seems swapped.' }],
      model: 'Categorical data are labels that put individuals in groups, like favorite team — even numbers like jersey numbers count if averaging them makes no sense. Quantitative data are numbers that count or measure. Discrete data are counts with listable values, like number of tickets sold. Continuous data are measurements that can take any value in an interval, like time in line or height.',
    },
    formulas: [], glossary: ['categorical', 'quantitative', 'discrete', 'continuous'],
  },
  {
    id: 'cat-displays', unit: 'u1', section: '1.1–1.2', title: 'Displaying Categorical Data',
    short: 'Frequency tables, pie charts, bar graphs, and Pareto charts.',
    source: { ...S11, pages: [64] },
    prereqs: ['data-types'], related: ['freq-tables', 'quant-graphs'],
    confusedWith: [{ id: 'quant-graphs', why: 'Bar graphs (categories) look like histograms (numbers) but are different tools.' }],
    difficulty: 1, importance: 2, minutes: 6, dims: ['recognize', 'interpret', 'apply'],
    know: ['Frequency tables, pie charts, bar graphs, Pareto charts'], understand: ['Pareto charts sort bars from largest to smallest; pie charts need parts of one whole'],
    calculate: ['Percent = count ÷ total'], interpret: ['Read a categorical display'],
    misconceptions: ['histogram-vs-bar'],
    why: { analogy: 'A Pareto chart is a leaderboard: biggest score first, so you see who is winning instantly.', body: 'Categories have no natural numeric order, so we can arrange them however helps the reader. Sorting (Pareto) highlights the most common categories; a pie chart emphasizes parts of a whole.' },
    memoryTrick: '**P**areto = **P**odium order (1st, 2nd, 3rd…).',
    lesson: [
      { kind: 'hook', title: 'Who are the students?', body: 'A college reported the ethnicity of its students. The same numbers can be shown as a table, a pie chart, a bar graph, or a Pareto chart. Which is easiest to read?', visual: { type: 'table', headers: ['Ethnicity', 'Frequency', 'Percent'], rows: [['Asian', '8,794', '36.1%'], ['Black', '1,412', '5.8%'], ['Filipino', '1,298', '5.3%'], ['Hispanic', '4,180', '17.1%'], ['Native American', '146', '0.6%'], ['Pacific Islander', '236', '1.0%'], ['White', '5,978', '24.5%']], caption: 'p.64 — Ethnicity of Students' } },
      { kind: 'explain', title: 'Bar graph vs. Pareto chart', body: 'A **bar graph** draws a separate bar for each category. A **Pareto chart** is a bar graph with the bars **sorted from tallest to shortest**, so the most common categories come first.', visual: { type: 'bar', percent: true, yLabel: 'Percent', categories: [{ label: 'Asian', value: 36.1 }, { label: 'White', value: 24.5 }, { label: 'Hispanic', value: 17.1 }, { label: 'Other', value: 9.6 }, { label: 'Black', value: 5.8 }, { label: 'Filipino', value: 5.3 }, { label: 'Pac. Isl.', value: 1.0 }, { label: 'Native Am.', value: 0.6 }] }, source: { pages: [64], section: S11.section } },
      { kind: 'check', prompt: 'The chart above sorts categories from most to least common. It is a…', input: { type: 'mc', options: [
        { id: 'a', text: 'Pareto chart', correct: true, why: 'Sorted bars = Pareto.' },
        { id: 'b', text: 'Histogram', why: 'Histograms show quantitative data in touching intervals; these are categories.', misconception: 'histogram-vs-bar' },
        { id: 'c', text: 'Pie chart', why: 'A pie chart is a circle divided into slices.' },
      ] }, explain: 'A Pareto chart is a sorted bar graph for categorical data.' },
      { kind: 'check', prompt: 'The table accounts for 22,044 of 24,382 students (90.4%). Why does the pie chart need an "Other/Unknown" slice of 9.6%?', input: { type: 'mc', options: [
        { id: 'a', text: 'A pie chart must show parts of one whole that add to 100%', correct: true, why: 'Exactly — slices must add up to the whole.' },
        { id: 'b', text: 'To make the chart more colorful', why: 'The slice is required so the percentages total 100%.' },
        { id: 'c', text: 'Because 9.6% is an outlier', why: 'Outliers are a quantitative-data idea.' },
      ] }, explain: '90.4% + 9.6% = 100%.' },
      { kind: 'summary', points: ['Categorical data: frequency tables, pie charts, bar graphs, Pareto charts.', 'Pareto = bars sorted largest to smallest.', 'Pie slices must total 100%.'] },
    ],
    recall: [{ prompt: 'What makes a Pareto chart different from an ordinary bar graph?', answer: 'Its bars are sorted from the most frequent category to the least.' }],
    teach: {
      prompt: 'Explain when you would use a bar graph, a Pareto chart, and a pie chart.',
      items: [
        { id: 'cat', idea: 'They display categorical data', patterns: ['categor|qualitative'], weight: 1 },
        { id: 'pareto', idea: 'Pareto chart sorts bars largest to smallest', patterns: ['pareto.{0,80}(order|sort|largest|biggest|descend|most)'], weight: 1 },
        { id: 'pie', idea: 'Pie chart shows parts of a whole (100%)', patterns: ['pie.{0,80}(whole|100|part|proportion|percent)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['bar graph.{0,40}quantitative', 'histogram.{0,40}categor'], message: 'Bar graphs are for categories; histograms are for quantitative data.' }],
      model: 'All three display categorical data. A bar graph shows each category\'s count or percent as a separate bar. A Pareto chart is a bar graph sorted from the most common category to the least, which highlights what matters most. A pie chart shows how parts make up one whole, so its slices must total 100%.',
    },
    formulas: [], glossary: ['frequency-table-cat', 'pie-chart', 'bar-graph', 'pareto'],
  },
  {
    id: 'sampling', unit: 'u1', section: '1.1–1.2', title: 'Sampling Methods & Sampling Bias',
    short: 'Simple random, systematic, stratified, cluster — and why convenience fails.',
    source: { ...S11, pages: [65, 66, 1, 20] },
    prereqs: ['pop-sample'], related: ['bias', 'investigative'],
    confusedWith: [{ id: 'bias', why: 'Sampling bias comes from *how* you pick; survey biases (Unit 1.4) come from responses and coverage.' }],
    difficulty: 2, importance: 5, minutes: 14, dims: ['recognize', 'apply', 'explain'],
    know: ['Simple random, systematic, stratified, cluster, convenience sampling'], understand: ['Random sampling minimizes sampling bias'],
    calculate: [], interpret: ['Name the method used; design each method for a scenario'],
    misconceptions: ['stratified-vs-cluster', 'convenience-is-random', 'systematic-vs-srs'],
    why: {
      analogy: 'Picking a pizza topping survey at a party: asking only the people standing next to you (convenience) gets the pepperoni fans by the snack table. Drawing names from a hat (SRS) gives every guest a fair chance.',
      body: 'When *you* choose who is in the sample, your choices (often unconsciously) favor certain people, and the statistic drifts away from the truth — that is **sampling bias**. Letting chance choose removes that favoritism, so on average the sample looks like the population.',
    },
    memoryTrick: '**S**tratified = **S**ome from **S**every group. **C**luster = **C**hoose whole **C**lusters.',
    lesson: [
      { kind: 'hook', title: 'Counting wood ducks', body: 'Researchers want to estimate how many wood ducks live in a regional park. The park is divided into a grid of numbered squares — forest around a central lake. They can only survey some squares.\n\nWhich squares should they pick?' },
      { kind: 'predict', prompt: 'A researcher starts at the park entrance (square #124) and surveys the 15 squares right next to it. Is that a good sample?', input: { type: 'mc', options: [
        { id: 'a', text: 'Yes — it is quick and covers 15 squares', why: 'Quick, but squares near the entrance may not resemble the rest of the park.', misconception: 'convenience-is-random' },
        { id: 'b', text: 'No — it is a convenience sample and likely biased', correct: true, why: 'Squares near the entrance (people, paths, no lake) probably have different duck counts than the rest of the park.' },
      ] }, reveal: 'Choosing what is easy to reach is **convenience sampling**. It produces **sampling bias**: estimates that systematically over- or underestimate the truth.' },
      { kind: 'interact', title: 'Try four random methods', widget: 'sampling', prompt: 'Pick each method and draw a sample of park squares. Watch which squares get chosen and compare the estimate to the true total.', takeaway: 'Random methods give estimates that bounce around the truth; convenience samples are consistently off.' },
      { kind: 'explain', title: 'The four random sampling methods', body: '- **Simple random sample (SRS)**: every group of n has the same chance → number all squares, use a random number generator.\n- **Systematic**: random start, then every k-th item → every 10th square.\n- **Stratified**: split into groups (strata), random sample **from each** → some forest squares *and* some lake squares.\n- **Cluster**: split into groups, randomly choose **entire groups** and survey everything in them → pick 3 whole rows of the grid.\n\n**Convenience** sampling (whoever is easy to reach) is **not random**.', source: { pages: [65], section: S11.section } },
      { kind: 'check', prompt: 'The marketing manager of an electronics chain gives questionnaires to **100 randomly selected customers at each store location**. Which method?', input: { type: 'mc', options: [
        { id: 'a', text: 'Stratified', correct: true, why: 'Each store is a group, and a random sample is taken from **every** group.' },
        { id: 'b', text: 'Cluster', why: 'Cluster sampling picks whole groups and surveys everyone in them — here every store is used and only some customers in each.', misconception: 'stratified-vs-cluster' },
        { id: 'c', text: 'Simple random', why: 'An SRS wouldn\'t guarantee exactly 100 from each store.' },
      ] }, explain: 'Random sample within **every** group = stratified.' },
      { kind: 'check', prompt: 'A teacher randomly selects **rows two and five** and calls on **all** students in those rows. Which method?', input: { type: 'mc', options: [
        { id: 'a', text: 'Cluster', correct: true, why: 'Rows are groups; whole groups were randomly chosen.' },
        { id: 'b', text: 'Stratified', why: 'Stratified would take some students from every row.', misconception: 'stratified-vs-cluster' },
        { id: 'c', text: 'Systematic', why: 'Systematic means every k-th individual from a list.', misconception: 'systematic-vs-srs' },
      ] }, explain: 'Randomly choosing whole groups = cluster.' },
      { kind: 'worked', title: 'Practice 1.1–1.2 #6 — name the method', problem: 'Identify the sampling method in each situation.', steps: [
        { label: 'Airport questionnaires to travelers sitting near gates, not hurrying', body: '**Convenience** — she chose people who were easy to approach.' },
        { label: 'Rows two and five, all students', body: '**Cluster**.' },
        { label: '100 random customers at each store', body: '**Stratified**.' },
        { label: 'Every fourth library patron', body: '**Systematic**.' },
        { label: '1,200 randomly selected phone numbers', body: '**Simple random** (though nonresponse could still cause bias).' },
      ], answer: 'Look for: "each group" → stratified; "whole groups" → cluster; "every k-th" → systematic; "randomly selected" with no groups → SRS; "easy/available" → convenience.', source: { pages: [66, 1], section: '1.1–1.2 Practice #6; Exam #1 Review #3' } },
      { kind: 'recall', prompt: 'Explain the difference between stratified and cluster sampling in one sentence each.', answer: 'Stratified: divide into groups and randomly sample **from every group**. Cluster: divide into groups and randomly select **whole groups**, using everyone in them.' },
      { kind: 'summary', points: ['Random sampling minimizes sampling bias.', 'SRS, systematic, stratified, cluster are random; convenience is not.', 'Stratified samples within every group; cluster samples whole groups.'] },
    ],
    recall: [{ prompt: 'Name the four random sampling methods and the one non-random method from the course.', answer: 'Simple random, systematic, stratified, cluster; convenience is non-random.' }],
    teach: {
      prompt: 'Teach a classmate the four random sampling methods and explain why random sampling matters.',
      items: [
        { id: 'srs', idea: 'SRS: every group of individuals equally likely', patterns: ['simple random.{0,80}(equal|same chance|random number|hat|every)'], weight: 1 },
        { id: 'sys', idea: 'Systematic: every k-th individual', patterns: ['systematic.{0,80}(every|k-?th|nth|\\d+(st|nd|rd|th))'], weight: 1 },
        { id: 'strat', idea: 'Stratified: random sample from each group', patterns: ['stratif.{0,80}(each|every|all) (group|strat)'], weight: 1 },
        { id: 'clus', idea: 'Cluster: randomly choose entire groups', patterns: ['cluster.{0,80}(whole|entire|all of|everyone)'], weight: 1 },
        { id: 'bias', idea: 'Randomness reduces sampling bias', patterns: ['bias'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['cluster.{0,60}(each|every) group', 'stratif.{0,60}(whole|entire) group'], message: 'Stratified and cluster appear swapped: stratified samples within every group; cluster takes whole groups.' }],
      model: 'In a simple random sample every group of individuals has the same chance of being chosen, like drawing names from a hat. Systematic sampling picks a random start and then every k-th person. Stratified sampling splits the population into groups and takes a random sample from each group. Cluster sampling splits into groups, randomly picks entire groups, and uses everyone in them. Random selection matters because it prevents sampling bias — estimates that systematically miss the true value, like a convenience sample of whoever is nearby.',
    },
    formulas: [], glossary: ['sampling-bias', 'random-sampling', 'srs', 'systematic', 'stratified', 'cluster', 'convenience'],
  },
  {
    id: 'freq-tables', unit: 'u1', section: '1.3–1.4', title: 'Frequency Tables',
    short: 'Frequency, relative frequency, and cumulative frequency.',
    source: { ...S13, pages: [60, 63, 1] },
    prereqs: ['data-types'], related: ['quant-graphs', 'prob-dist'],
    confusedWith: [{ id: 'prob-dist', why: 'A probability distribution is a relative-frequency table for a random variable.' }],
    difficulty: 2, importance: 3, minutes: 10, dims: ['recognize', 'calculate', 'interpret', 'apply'],
    know: ['Frequency, relative frequency, cumulative frequency, cumulative relative frequency'], understand: ['Grouping data into classes makes large data sets readable'],
    calculate: ['Build a frequency table from raw data'], interpret: ['Answer "at most / less than" questions from cumulative columns'],
    misconceptions: ['relfreq-not-sum-1', 'cumulative-confusion'],
    why: { analogy: 'A cumulative frequency column is a running score in a game: after each round you add the new points to the total so far.', body: 'Raw lists of 40+ numbers are unreadable. Grouping into classes shows where data pile up. Relative frequency lets you compare groups of different sizes, and cumulative frequency answers "how many are at or below this?" in one look.' },
    memoryTrick: '**Relative** = part ÷ whole. **Cumulative** = running total. Last cumulative relative frequency is always **1**.',
    lesson: [
      { kind: 'hook', title: 'Phone-number sums', body: 'Add up the digits of your phone number. In a class of 30, you get 30 different-looking sums. How could you summarize them so you can *see* the pattern?' },
      { kind: 'explain', title: 'The columns of a frequency table', body: '- **Frequency (f)**: how many values fall in each class.\n- **Relative frequency** = f ÷ n (the proportion).\n- **Cumulative frequency**: running total of f.\n- **Cumulative relative frequency**: running total of relative frequency — ends at **1**.', source: { pages: [60], section: S13.section } },
      { kind: 'worked', title: 'Exam #1 Review #5 — days missed', problem: 'Days missed by 60 people, grouped into classes.', visual: { type: 'table', headers: ['Class', 'Freq.', 'Rel. Freq.', 'Cum. Freq.', 'Cum. Rel. Freq.'], rows: [['0–4', 36, '0.6', 36, '0.6'], ['5–9', 4, '0.067', 40, '0.667'], ['10–14', 8, '0.133', 48, '0.8'], ['15–19', 5, '0.083', 53, '0.883'], ['20–24', 6, '0.1', 59, '0.983'], ['25–29', 1, '0.017', 60, '1']] }, steps: [
        { label: 'Total', body: 'Σf = 60, and the relative frequencies add to 1.' },
        { label: 'Relative frequency', body: '36 ÷ 60 = 0.6, 4 ÷ 60 ≈ 0.067, …' },
        { label: 'Cumulative', body: '36, 36 + 4 = 40, 40 + 8 = 48, …' },
        { label: 'Reading it', body: '60% of people missed 0–4 days. 80% missed 14 or fewer days (cumulative 0.8).' },
      ], answer: 'Cumulative relative frequency 0.8 at "10–14" means **80% of people missed at most 14 days**.', source: { pages: [1], section: 'Exam #1 Review KEY #5' } },
      { kind: 'interact', title: 'Build one yourself', widget: 'freq-table', props: { dataset: 'lyme-a' }, prompt: 'Using Researcher A\'s Lyme disease data, change the class width and watch every column update.', takeaway: 'The relative frequencies always add to 1, and the last cumulative relative frequency is always 1.' },
      { kind: 'check', prompt: 'A class has frequency 5 out of n = 60. What is its relative frequency? (decimal)', input: { type: 'number', answer: 5 / 60, tol: 0.002 }, explain: '5 ÷ 60 ≈ 0.083.' },
      { kind: 'check', prompt: 'Using the Exam #1 table, what proportion of people missed **fewer than 20 days**?', input: { type: 'mc', options: [
        { id: 'a', text: '0.883', correct: true, why: 'Cumulative relative frequency through 15–19.' },
        { id: 'b', text: '0.083', why: 'That is only the 15–19 class. "Fewer than 20" needs everything up to 19.', misconception: 'cumulative-confusion' },
        { id: 'c', text: '0.983', why: 'That includes 20–24.' },
      ] }, explain: 'Read the cumulative relative frequency at the last class below 20: 0.883.' },
      { kind: 'summary', points: ['Relative frequency = f ÷ n; they sum to 1.', 'Cumulative columns answer "at most / fewer than" questions.', 'Final cumulative relative frequency = 1.'] },
    ],
    recall: [{ prompt: 'How do you get a cumulative relative frequency, and what must the last one be?', answer: 'Add relative frequencies as you go down the table; the last one must be 1.' }],
    teach: {
      prompt: 'Explain frequency, relative frequency, and cumulative relative frequency, and when you would use each.',
      items: [
        { id: 'f', idea: 'Frequency is a count per class', patterns: ['frequency.{0,40}(count|how many|number of)'], weight: 1 },
        { id: 'rel', idea: 'Relative frequency = frequency ÷ total', patterns: ['relative.{0,80}(divid|÷|\\/|out of|over|proportion|percent|total)'], weight: 1 },
        { id: 'cum', idea: 'Cumulative = running total', patterns: ['cumulative.{0,80}(running|add(ing)? up|total so far|sum|up to|accumulat)'], weight: 1 },
        { id: 'one', idea: 'Relative frequencies sum to 1; last cumulative is 1', patterns: ['(add|sum|total).{0,30}(to )?(1|one|100)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['relative frequency.{0,40}(running|cumulative)'], message: 'Relative frequency is a single class proportion; the running total is the cumulative column.' }],
      model: 'Frequency is how many data values fall in a class. Relative frequency divides that count by the total n, giving a proportion — useful for comparing groups of different sizes; they add to 1. Cumulative relative frequency is the running total of relative frequencies, so it tells you the proportion at or below a class (it ends at 1) and answers "at most" questions.',
    },
    formulas: ['rel-freq'], glossary: ['frequency', 'relative-frequency', 'cumulative-frequency'],
  },
  {
    id: 'experiments', unit: 'u1', section: '1.3–1.4', title: 'Experimental Design',
    short: 'Explanatory vs. response variables, treatments, controls, blinding, and confounding.',
    source: { ...S13, pages: [60, 62, 1] },
    prereqs: ['pop-sample'], related: ['bias', 'investigative', 'scatter', 'correlation'],
    confusedWith: [{ id: 'correlation', why: 'Only randomized experiments support cause-and-effect; correlation alone does not.' }],
    difficulty: 3, importance: 4, minutes: 14, dims: ['recognize', 'interpret', 'apply', 'explain'],
    know: ['Explanatory, response, treatment, experimental units, lurking, confounding, randomization, control group, blinding, placebo'],
    understand: ['Randomized experiments can show cause and effect; observational studies cannot rule out confounding'],
    calculate: [], interpret: ['Identify variables and possible confounders in a study'],
    misconceptions: ['explanatory-vs-response', 'correlation-causation-study'],
    why: { analogy: 'Ice-cream sales and sunburns rise together — not because ice cream burns you, but because **summer heat** (a lurking variable) drives both.', body: 'If people choose their own "treatment", the groups may differ in other ways (income, habits, age). **Random assignment** makes the groups alike on average in everything except the treatment, so a difference in the response can be blamed on the treatment.' },
    memoryTrick: '**E**xplanatory **E**xplains; **R**esponse **R**esults.',
    lesson: [
      { kind: 'hook', title: 'The Marshmallow Test', body: 'In the 1960s–70s, Stanford researchers offered young children one marshmallow now — or two if they waited. Years later, kids who waited had "more favorable outcomes" (described as more academically and socially competent).\n\nDoes learning to wait **cause** success later in life?' },
      { kind: 'predict', prompt: 'What else might explain both waiting longer *and* later success?', input: { type: 'mc', options: [
        { id: 'a', text: 'Nothing — waiting must cause success', why: 'This was not a randomized experiment, so other factors could explain both.', misconception: 'correlation-causation-study' },
        { id: 'b', text: 'Home environment / family resources', correct: true, why: 'Kids from stable, well-resourced homes may trust the adult will return *and* have more support later — a confounding variable.' },
      ] }, reveal: 'A **confounding variable** is associated with the explanatory variable **and** influences the response, so their effects get tangled together.' },
      { kind: 'explain', title: 'Vocabulary of experiments', body: '- **Explanatory variable**: may cause a change (the "input").\n- **Response variable**: the outcome measured.\n- **Treatment**: the manipulation of the explanatory variable.\n- **Experimental units**: who/what gets the treatment.\n- **Lurking variable**: unmeasured factor affecting the variables.\n- **Confounding variable**: known factor tied to the explanatory variable that also affects the response.\n- **Randomization**, **control groups**, **blinding** (single or double), and **placebos** help isolate the effect of the explanatory variable.', source: { pages: [60], section: S13.section } },
      { kind: 'interact', title: 'Label the study', widget: 'experiment-design', prompt: 'Assign each piece of the Spotify study to the right role.', takeaway: 'Premium access (explanatory) is randomly assigned; daily listening time (response) is measured.' },
      { kind: 'check', prompt: 'A streaming company randomly assigns 155 users to **premium** or **free** access and records daily listening time. The **response variable** is…', input: { type: 'mc', options: [
        { id: 'a', text: 'Daily listening time (quantitative)', correct: true, why: 'It is the outcome measured.' },
        { id: 'b', text: 'Type of access (categorical)', why: 'That is the explanatory variable — it is what was assigned.', misconception: 'explanatory-vs-response' },
        { id: 'c', text: 'The 155 users', why: 'Those are the experimental units.' },
      ] }, explain: 'Explanatory = access type (categorical). Response = daily listening time (quantitative).' },
      { kind: 'worked', title: 'Exam #1 Review #4b — video games', problem: 'Students who play video games spend less time on homework, and students who spend less time on homework are more likely to flunk out. Does playing video games make students flunk out?', steps: [
        { label: 'Association ≠ cause', body: 'This does not imply that playing video games *causes* flunking out.' },
        { label: 'Confounding', body: '"Time spent on homework" is a **confounding variable**: it is associated with video gaming and also affects school success.' },
      ], answer: 'Without a randomized experiment, we can\'t separate the effect of video games from homework time.', source: { pages: [1], section: 'Exam #1 Review KEY #4' } },
      { kind: 'check', prompt: 'A psychologist tells subjects about the "placebo effect" before the study. Why is that a problem?', input: { type: 'mc', options: [
        { id: 'a', text: 'Subjects aware of the bias can change how they respond, skewing results', correct: true, why: 'Exactly — that is why blinding matters.' },
        { id: 'b', text: 'It isn\'t a problem — more information is always better', why: 'Expectations change behavior; that is the placebo effect.' },
      ] }, explain: 'Informing subjects defeats blinding; their expectations can skew the response.' },
      { kind: 'recall', prompt: 'Why can a randomized experiment show cause and effect when an observational study cannot?', answer: 'Random assignment balances confounding variables between groups, so the only systematic difference is the treatment.' },
      { kind: 'summary', points: ['Explanatory → response.', 'Confounders tangle effects; randomization untangles them.', 'Control groups, blinding, and placebos isolate the treatment effect.'] },
    ],
    recall: [{ prompt: 'Define a confounding variable and give the Marshmallow Test example.', answer: 'A factor associated with the explanatory variable that also affects the response — e.g., home environment affecting both a child\'s waiting and later success.' }],
    teach: {
      prompt: 'Explain the difference between explanatory and response variables, what a confounding variable is, and why randomization matters.',
      items: [
        { id: 'exp', idea: 'Explanatory variable may cause/explain change', patterns: ['explanatory.{0,80}(cause|explain|input|change|manipulat|independent)'], weight: 1 },
        { id: 'resp', idea: 'Response variable is the measured outcome', patterns: ['response.{0,80}(outcome|measur|result|effect|dependent)'], weight: 1 },
        { id: 'conf', idea: 'Confounder is related to both / tangles effects', patterns: ['confound.{0,120}(both|related|associat|also affect|influenc|separate)'], weight: 1 },
        { id: 'rand', idea: 'Randomization balances groups so cause can be inferred', patterns: ['random.{0,120}(balance|equal|similar|cause|fair|even out)'], weight: 1 },
        { id: 'control', idea: 'Mentions control group / blinding / placebo', patterns: ['control group|blind|placebo'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['correlat.{0,40}(proves|means) (it )?caus', 'observational.{0,40}prove'], message: 'Observational associations do not prove causation.' }],
      model: 'The explanatory variable is the one that might cause a change — like premium vs. free access — and the response variable is the outcome we measure, like daily listening time. A confounding variable is related to the explanatory variable and also affects the response, so we can\'t tell which one caused the change (home environment in the Marshmallow Test). Randomly assigning treatments balances confounders across groups, so a difference in the response can be attributed to the treatment. Control groups, blinding, and placebos further isolate the effect.',
    },
    formulas: [], glossary: ['explanatory', 'response', 'treatment', 'experimental-units', 'lurking', 'confounding', 'randomization', 'control-group', 'blinding', 'placebo'],
  },
  {
    id: 'bias', unit: 'u1', section: '1.3–1.4', title: 'Bias in Surveys',
    short: 'Response, undercoverage, nonresponse, and voluntary response bias.',
    source: { ...S13, pages: [60, 61, 63, 1] },
    prereqs: ['sampling'], related: ['sampling', 'experiments'],
    confusedWith: [{ id: 'sampling', why: 'A random sample can still suffer nonresponse or response bias.' }],
    difficulty: 2, importance: 4, minutes: 12, dims: ['recognize', 'apply', 'explain'],
    know: ['Response bias, undercoverage, nonresponse bias, voluntary response bias'], understand: ['Bias makes estimates systematically wrong, and a bigger sample does not fix it'],
    calculate: [], interpret: ['Identify the bias present in a scenario'],
    misconceptions: ['nonresponse-vs-voluntary', 'undercoverage-vs-nonresponse', 'response-bias'],
    why: { analogy: 'Rating a restaurant from online reviews: mostly the furious and the delighted bother to post (voluntary response). Asking "You loved the food, right?" (response bias) pushes the answer.', body: 'Bias is a **systematic** error — it pushes the estimate the same direction every time. Collecting more data from a biased process just gives you a more precise wrong answer.' },
    memoryTrick: '**Under**coverage = **under** the radar (never asked). **Non**response = asked, **no** answer. **Voluntary** = **volunteered** themselves. **Response** bias = the **question** pushed them.',
    lesson: [
      { kind: 'hook', title: 'The poll that couldn\'t lose', body: 'YouPolls lets anyone create and answer polls. One asked: *"Do you feel happy paying your taxes when members of the US Government are allowed to ignore their tax liabilities?"* — 11 people responded, every one answering **"NO!"**\n\nHow many problems can you spot?' },
      { kind: 'explain', title: 'Four kinds of bias (p.60)', body: '- **Response bias**: collecting data or asking questions in a way that influences the response (leading wording, threats, intimidation).\n- **Undercoverage**: survey participants are **left out of the selection process** — they never had a chance to be chosen.\n- **Nonresponse bias**: participants were selected but are **unable or refuse** to respond.\n- **Voluntary response bias**: individuals **decide for themselves** whether they are in the sample.', source: { pages: [60], section: S13.section } },
      { kind: 'interact', title: 'Bias spotter', widget: 'bias-spotter', prompt: 'Classify each real scenario from the course. You get an explanation after each one.', takeaway: 'Ask: who was left out of selection? who chose themselves? who was chosen but didn\'t answer? did the wording push?' },
      { kind: 'check', prompt: 'A teacher **emails** a survey to a **random sample** of all students about funding a gym renovation. Only some reply. Which bias is most likely?', input: { type: 'mc', options: [
        { id: 'a', text: 'Nonresponse bias', correct: true, why: 'Students were randomly selected, but many may not respond — and those who do may feel more strongly.' },
        { id: 'b', text: 'Voluntary response bias', why: 'Students were selected by the teacher; they didn\'t sign themselves up.', misconception: 'nonresponse-vs-voluntary' },
        { id: 'c', text: 'Undercoverage', why: 'Every student had a chance to be selected.', misconception: 'undercoverage-vs-nonresponse' },
      ] }, explain: 'Selected but didn\'t respond → **nonresponse**.' },
      { kind: 'check', prompt: 'Whole Foods surveys a random sample of **its customers** about how often per month they shop at Whole Foods, to learn about all shoppers. Which bias?', input: { type: 'mc', options: [
        { id: 'a', text: 'Undercoverage', correct: true, why: 'People who don\'t shop at Whole Foods were never part of the selection process.' },
        { id: 'b', text: 'Response bias', why: 'The wording isn\'t leading; the problem is who could be selected.' },
        { id: 'c', text: 'Nonresponse bias', why: 'The issue is who was left out of selection, not who refused.', misconception: 'undercoverage-vs-nonresponse' },
      ] }, explain: 'Left out of the selection process → **undercoverage**.' },
      { kind: 'check', prompt: '"Given that ChatGPT violates the academic honesty policy and can result in discipline that will go on your record, have you ever used ChatGPT to complete an assignment?" Which bias?', input: { type: 'mc', options: [
        { id: 'a', text: 'Response bias', correct: true, why: 'The wording threatens consequences, pushing students to say "no".' },
        { id: 'b', text: 'Voluntary response bias', why: 'Students were randomly sampled.', misconception: 'response-bias' },
      ] }, explain: 'Intimidating wording → **response bias**.' },
      { kind: 'recall', prompt: 'Explain the difference between nonresponse bias and voluntary response bias.', answer: 'Nonresponse: the researcher selected people who then didn\'t respond. Voluntary response: people selected themselves (online polls, call-ins).' },
      { kind: 'summary', points: ['Response bias: wording/pressure.', 'Undercoverage: left out of selection.', 'Nonresponse: selected, didn\'t answer.', 'Voluntary response: self-selected.'] },
    ],
    recall: [{ prompt: 'A city mails a survey to all homeowners near parks about park funding. Name the bias.', answer: 'Undercoverage — residents who don\'t live near parks (or rent) were left out of the selection process.' }],
    teach: {
      prompt: 'Explain the four types of survey bias from the course, with an example of each.',
      items: [
        { id: 'resp', idea: 'Response bias: wording or pressure influences answers', patterns: ['response bias.{0,120}(word|question|influenc|lead|pressure|threat)'], weight: 1 },
        { id: 'under', idea: 'Undercoverage: groups left out of selection', patterns: ['undercover.{0,120}(left out|excluded|not (included|able|part)|never|chance)'], weight: 1 },
        { id: 'non', idea: 'Nonresponse: selected but don\'t respond', patterns: ['nonresponse.{0,120}(refuse|don.t|do not|doesn.t|unable|fail|ignore)'], weight: 1 },
        { id: 'vol', idea: 'Voluntary response: people choose to participate', patterns: ['voluntary.{0,120}(choose|decide|themselves|self|volunteer|strong opinion)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['nonresponse.{0,60}(choose|volunteer|themselves)'], message: 'Choosing to participate is voluntary response; nonresponse is when selected people don\'t answer.' }],
      model: 'Response bias happens when the wording or situation pushes people toward an answer, like a question that threatens discipline. Undercoverage happens when part of the population is left out of the selection process, like surveying only Whole Foods customers. Nonresponse bias happens when selected people don\'t respond, like a random email survey few students answer. Voluntary response bias happens when people choose whether to participate, like a social-media poll — usually only people with strong opinions respond.',
    },
    formulas: [], glossary: ['response-bias', 'undercoverage', 'nonresponse', 'voluntary-response'],
  },
  {
    id: 'investigative', unit: 'u1', section: '1.3–1.4', title: 'Investigative Questions',
    short: 'Variable of interest, inference goal, and scope of inference.',
    source: { ...S13, pages: [60, 61, 62, 63] },
    prereqs: ['pop-sample', 'experiments'], related: ['pop-sample', 'experiments'],
    confusedWith: [{ id: 'pop-sample', why: 'The scope of inference is the population.' }],
    difficulty: 2, importance: 2, minutes: 8, dims: ['recognize', 'apply', 'explain'],
    know: ['Three components: variable of interest, inference goal (estimate or test), scope of inference'], understand: ['Statisticians pose the question before collecting data'],
    calculate: [], interpret: ['Write a complete investigative question; identify a missing component'],
    misconceptions: ['missing-inference-component'],
    why: { analogy: 'An investigative question is a GPS destination: *what* you are looking for (variable), *what you want to do* (estimate or test), and *where* (population). Missing any one and you can\'t navigate.', body: 'Inference means using a sample to say something about a population. Without a clear variable, goal, and population, you can\'t design the sample or know what your statistic estimates.' },
    memoryTrick: '**V-G-S**: **V**ariable, **G**oal, **S**cope. "Very Good Statistics."',
    lesson: [
      { kind: 'hook', title: 'Driving to school', body: 'A transportation research center randomly selects 290 Michigan high school students and asks each whether they drive their own car to school. What exactly are they trying to find out?' },
      { kind: 'explain', title: 'Three components', body: 'A complete **investigative question** includes:\n1. **Variable of interest** — whether a student drives their own car (categorical).\n2. **Inference goal** — **estimate** a value, or **test** a claim.\n3. **Scope of inference** — the population: all Michigan high school students.\n\n*"What proportion of **all Michigan high school students** **drive their own car to school**?"* → an estimate.', source: { pages: [60, 61], section: S13.section } },
      { kind: 'check', prompt: '"Is there convincing statistical evidence that adding more ads to YouTube causes lower average viewing times?" Which component is missing?', input: { type: 'mc', options: [
        { id: 'a', text: 'Scope of inference (which population?)', correct: true, why: 'All YouTube viewers? Teens? It doesn\'t say who.' },
        { id: 'b', text: 'Variable of interest', why: 'The variable (viewing time) is named.' },
        { id: 'c', text: 'Inference goal', why: '"Convincing evidence… causes" signals a test.' },
      ] }, explain: 'No population is named.' },
      { kind: 'check', prompt: '"What is the true proportion for all fans at a University of Michigan football game?" Which component is missing?', input: { type: 'mc', options: [
        { id: 'a', text: 'Variable of interest', correct: true, why: 'The proportion of fans who… what? No variable.' },
        { id: 'b', text: 'Scope of inference', why: '"All fans at a UM football game" is the population.' },
        { id: 'c', text: 'Inference goal', why: '"True proportion" signals an estimate.' },
      ] }, explain: 'A proportion of fans *who do what*?' },
      { kind: 'recall', prompt: 'Write an investigative question for the Spotify study (premium vs. free, daily listening time).', answer: 'Example: "Does premium access cause app users to listen to more hours of music per day, on average, than free access?" (variable: daily listening time; goal: test; scope: the company\'s app users).' },
      { kind: 'summary', points: ['Variable of interest + inference goal (estimate/test) + scope (population).', 'Inference generalizes from sample to population.'] },
    ],
    recall: [{ prompt: 'List the three components of an investigative question.', answer: 'Variable of interest, inference goal (estimate or test), scope of inference (population).' }],
    teach: {
      prompt: 'Explain what makes an investigative question complete, and write an example.',
      items: [
        { id: 'var', idea: 'Names a variable of interest', patterns: ['variable'], weight: 1 },
        { id: 'goal', idea: 'States an inference goal: estimate or test', patterns: ['estimat|test|goal'], weight: 1 },
        { id: 'scope', idea: 'States the scope / population', patterns: ['scope|population|all '], weight: 1 },
        { id: 'ex', idea: 'Includes a question example', patterns: ['\\?'], weight: 0.5 },
      ],
      misconceptions: [],
      model: 'A complete investigative question names the variable of interest (what is measured), the inference goal (do we want to estimate a value or test a claim?), and the scope of inference (which population we are generalizing to). Example: "What proportion of all Michigan high school students drive their own car to school?"',
    },
    formulas: [], glossary: ['inference', 'investigative-question'],
  },
];
