import type { Concept } from '../../engine/types';

const S41 = { pages: [28, 29, 30, 3, 4], section: '4.1–4.2 Probability Distributions' };
const S43 = { pages: [24, 25, 26, 27], section: '4.3 Binomial Distributions' };

export const UNIT5: Concept[] = [
  {
    id: 'prob-dist', unit: 'u5', section: '4.1–4.2', title: 'Probability Distributions',
    short: 'Discrete random variables, valid distributions, and the uniform distribution.',
    source: { ...S41, pages: [28, 30, 3] }, prereqs: ['prob-rules', 'freq-tables'], related: ['expected-value', 'binomial', 'data-types'],
    confusedWith: [{ id: 'freq-tables', why: 'A probability distribution is like a relative-frequency table for chance outcomes.' }],
    difficulty: 2, importance: 4, minutes: 12, dims: ['recognize', 'calculate', 'interpret', 'apply'],
    know: ['Random variable X; discrete vs. continuous', 'Every P(x) between 0 and 1; ΣP(x) = 1'], understand: ['A distribution lists every value with its probability'],
    calculate: ['Missing probability; P(X > k), P(X ≥ k); uniform probabilities'], interpret: ['Explain P(X ≥ 3) in context; describe the shape'],
    misconceptions: ['dist-sum-1', 'strict-vs-inclusive', 'discrete-vs-continuous'],
    why: { analogy: 'A probability distribution is a game\'s loot table: every possible drop with its drop rate — and the drop rates must add to 100%.', body: 'Because the outcomes listed cover every possibility exactly once, their probabilities must add to 1. That fact lets you find a missing probability, and "more than / at least" questions are just sums of rows.' },
    memoryTrick: '"**Every row 0 to 1, all rows add to 1.**" And: "**more than** excludes, **at least** includes."',
    lesson: [
      { kind: 'hook', title: 'Snow days', body: 'Maryland students sometimes get snow days. X = number of snow days at a certain high school in a random school year. The school year is extended if there are **more than 5**. How likely is that?', visual: { type: 'table', headers: ['X', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], rows: [['P(X)', '???', '0.19', '0.14', '0.10', '0.07', '0.05', '0.04', '0.04', '0.02', '0.01', '0.01']], caption: 'p.3 Practice #1' } },
      { kind: 'explain', title: 'Discrete probability distributions', body: 'A **random variable** X is a numerical outcome of a chance process. A **discrete** random variable has countable values. Its **probability distribution (PDF)** lists each value with its probability.\n\nTwo rules: each probability is between **0 and 1**, and all probabilities **sum to 1**.', source: { pages: [28], section: S41.section } },
      { kind: 'check', prompt: 'Find the missing P(X = 0) for the snow days.', input: { type: 'number', answer: 0.33, tol: 0.001 }, explain: '1 − (0.19 + 0.14 + … + 0.01) = 1 − 0.67 = **0.33**. P(X = 0) is the probability of no snow days in a random year.' },
      { kind: 'check', prompt: 'P(X > 5) — the school year gets extended?', input: { type: 'number', answer: 0.12, tol: 0.001 }, explain: '"More than 5" = 6, 7, 8, 9, 10 → 0.04 + 0.04 + 0.02 + 0.01 + 0.01 = **0.12**.' },
      { kind: 'check', prompt: 'Which values are included in P(X ≥ 3)?', input: { type: 'mc', options: [
        { id: 'a', text: '3, 4, 5, …', correct: true, why: '"At least 3" includes 3.' },
        { id: 'b', text: '4, 5, 6, …', why: 'That is X > 3.', misconception: 'strict-vs-inclusive' },
        { id: 'c', text: '0, 1, 2, 3', why: 'That is X ≤ 3.' },
      ] }, explain: '≥ includes the boundary; > excludes it.' },
      { kind: 'explain', title: 'Shape of the distribution', body: 'A histogram of the snow-day distribution shows a long tail to the right → **skewed right**: most years have few snow days, a few have many.', visual: { type: 'probdist', x: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], p: [0.33, 0.19, 0.14, 0.1, 0.07, 0.05, 0.04, 0.04, 0.02, 0.01, 0.01], xLabel: 'Number of snow days' }, source: { pages: [3], section: '4.1–4.2 Practice #1d' } },
      { kind: 'explain', title: 'A continuous example: the uniform distribution', body: 'Y = minutes after 10 am that school ends on an early-dismissal day, **uniform from 0 to 180**. Every time is equally likely, so probability = fraction of the interval.\n\n"School ends before 11:15 am" → Y < 75 → $P(Y < 75) = \\frac{75}{180} = \\frac{5}{12} \\approx 0.4167$.', source: { pages: [3], section: '4.1–4.2 Practice #1f' } },
      { kind: 'summary', points: ['Discrete distribution: each P(x) in [0, 1], ΣP(x) = 1.', '> excludes the boundary, ≥ includes it.', 'Uniform: probability = length of interval ÷ total length.'] },
    ],
    recall: [{ prompt: 'What two conditions make a probability distribution valid?', answer: 'Every probability is between 0 and 1, and all probabilities add to 1.' }],
    teach: {
      prompt: 'Explain what a discrete probability distribution is and the rules it must follow. Show how you would find a missing probability.',
      items: [
        { id: 'rv', idea: 'Lists each value of a random variable with its probability', patterns: ['(each|every|all) (value|outcome).{0,60}probabilit'], weight: 1 },
        { id: 'range', idea: 'Each probability between 0 and 1', patterns: ['(between|from) 0 (and|to) 1|zero and one'], weight: 1 },
        { id: 'sum', idea: 'Probabilities sum to 1', patterns: ['(add|sum|total).{0,30}(to |up to )?(1|one|100)'], weight: 1.5 },
        { id: 'missing', idea: 'Missing probability = 1 − sum of others', patterns: ['1 ?(-|−|minus)|one minus|subtract'], weight: 1 },
      ],
      misconceptions: [],
      model: 'A discrete probability distribution lists every possible value of a discrete random variable together with its probability. Each probability must be between 0 and 1, and all the probabilities must add to 1. To find a missing probability, add up the known probabilities and subtract the total from 1 — for the snow days, 1 − 0.67 = 0.33.',
    },
    formulas: ['uniform'], glossary: ['random-variable', 'discrete-rv', 'probability-distribution', 'continuous-uniform'],
  },
  {
    id: 'expected-value', unit: 'u5', section: '4.1–4.2', title: 'Expected Value & Standard Deviation',
    short: 'The long-run average of a random variable — and its risk.',
    source: { ...S41, pages: [28, 29, 3, 4] }, prereqs: ['prob-dist', 'center'], related: ['transform', 'binomial', 'std-dev'],
    confusedWith: [{ id: 'center', why: 'E(X) is a *weighted* mean.' }, { id: 'std-dev', why: 'σ for a random variable uses Σx²P(x) − μ².' }],
    difficulty: 3, importance: 5, minutes: 16, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['μ = E(X) = Σ x·P(x)', 'σ² = Σx²P(x) − μ², σ = √σ²', 'Fair game: E(X) = 0'], understand: ['E(X) is a long-run average and need not be a possible value'],
    calculate: ['Expected value and SD from a table; solve for a prize that makes a game fair'], interpret: ['"In the long run, we expect … on average"'],
    misconceptions: ['ev-plain-average', 'ev-must-occur', 'var-forget-mu2'],
    why: { analogy: 'A casino doesn\'t know who will win tonight, but it knows each $100 roulette bet earns it about $5.26 on average. Over millions of bets, that expected value is practically guaranteed income.', body: 'Weighting each outcome by its probability is the same as averaging over a huge number of plays: outcomes that happen more often count more. The SD measures how wildly individual results swing around that average — the risk.' },
    memoryTrick: '"**Multiply across, add down**" for E(X). "**Mean of the squares minus square of the mean**" for σ².',
    lesson: [
      { kind: 'hook', title: 'Roulette', body: 'An American roulette wheel has 18 red, 18 black, and 2 green numbers. You bet **$100 on black**: win $100 if black, lose $100 otherwise. Should you play 1,000 times?' },
      { kind: 'predict', prompt: 'Predict your average result per bet in the long run.', input: { type: 'slider', min: -20, max: 20, step: 0.5, answer: -5.26, tol: 2.5, unit: '$', label: 'average winnings per bet' }, reveal: 'E(X) = 100(18/38) + (−100)(20/38) ≈ **−$5.26** per bet. Over 1,000 bets: about −$5,263.' },
      { kind: 'explain', title: 'Expected value', body: 'The **expected value** (mean of the probability distribution) is a **weighted average**:\n$$\\mu = E(X) = \\sum x \\cdot P(x)$$\nInterpretation: "In the long run, we expect an average of … per …"\n\nThe **variance** and **standard deviation** measure variability:\n$$\\sigma^2 = \\sum x^2 P(x) - \\mu^2, \\qquad \\sigma = \\sqrt{\\sigma^2}$$', source: { pages: [28, 29, 3], section: S41.section } },
      { kind: 'interact', title: 'Play it many times', widget: 'expected-value', props: { preset: 'roulette' }, prompt: 'Simulate 10, 100, then 10,000 bets. Watch your average winnings per bet approach E(X).', takeaway: 'Individual results swing by about ±$100 (σ ≈ $99.86), but the long-run average converges to −$5.26.' },
      { kind: 'worked', title: 'Practice #1e — snow days', problem: 'X = snow days with P(X): .33, .19, .14, .10, .07, .05, .04, .04, .02, .01, .01 for x = 0…10.', steps: [
        { label: 'Mean', body: 'μ = 0(.33) + 1(.19) + 2(.14) + … + 10(.01) = **2.17** snow days.' },
        { label: 'Interpret', body: 'In a randomly selected school year, we expect about 2.17 snow days on average.' },
        { label: 'Variance', body: 'Σx²P(x) = 10.51 → σ² = 10.51 − 2.17² ≈ 5.801.' },
        { label: 'SD', body: 'σ = √5.801 ≈ **2.409** days: in the long run, the number of snow days varies from the mean by about 2.409 days.' },
      ], answer: 'μ = 2.17, σ ≈ 2.409 (you can\'t have 2.17 days — the mean is a long-run average).', source: { pages: [3], section: '4.1–4.2 Practice #1e', note: 'The key prints σ² = 5.803; exact is 5.8011.' } },
      { kind: 'check', prompt: 'Slot machine Z: −$40 (0.56), $0 (0.38), $40 (0.06). Find E(Z).', input: { type: 'number', answer: -20, tol: 0.01, unit: '$' }, explain: '−40(0.56) + 0(0.38) + 40(0.06) = −22.4 + 2.4 = **−$20**.' },
      { kind: 'worked', title: 'Practice #2 — making a game fair', problem: 'Spinner with 16 equal sections: 3 win $0, 8 win $1, 4 win $5, 1 grand prize $x. It costs $3 to play.', steps: [
        { label: 'Net winnings', body: '−$3 (3/16), −$2 (8/16), +$2 (4/16), $x − 3 (1/16).' },
        { label: 'Fair → E = 0', body: '0 = −3(3/16) − 2(8/16) + 2(4/16) + (x − 3)(1/16).' },
        { label: 'Solve', body: '0 = −1.0625 + (x − 3)/16 → x − 3 = 17 → **x = $20**.' },
      ], answer: 'A $20 grand prize makes E(X) = 0: neither player nor house has an advantage.', source: { pages: [4], section: '4.1–4.2 Practice #2' } },
      { kind: 'summary', points: ['E(X) = Σx·P(x): long-run average (needn\'t be possible).', 'σ² = Σx²P(x) − μ²; σ = risk/variability.', 'Fair game: E(X) = 0.'] },
    ],
    recall: [{ prompt: 'Interpret E(X) = −$5.26 for a $100 roulette bet.', answer: 'In the long run, a player loses about $5.26 per $100 bet on average.' }],
    teach: {
      prompt: 'Explain what the expected value of a random variable is, how to compute it, and how to interpret it.',
      items: [
        { id: 'formula', idea: 'Multiply each value by its probability and add', patterns: ['(multipl|times|×).{0,60}probabilit.{0,60}(add|sum)|sum.{0,30}x ?(·|\\*|times)? ?p'], weight: 1.5 },
        { id: 'weighted', idea: 'Weighted average', patterns: ['weight'], weight: 1 },
        { id: 'long', idea: 'Long-run average outcome', patterns: ['long.?(run|term)|over many|on average'], weight: 1.5 },
        { id: 'notneed', idea: 'Need not be a possible value', patterns: ['(not|doesn.t|need not).{0,40}(possible|actual|happen)'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['add (up )?(the )?(values|x).{0,30}divid'], message: 'Expected value weights each value by its probability — not a plain average of the x-values.' }],
      model: 'The expected value E(X) is the mean of a random variable — the long-run average outcome. To compute it, multiply each possible value by its probability and add the products, so it is a weighted average where likelier values count more. For a $100 roulette bet, E(X) ≈ −$5.26, meaning that over many bets a player loses about $5.26 per bet on average. It does not have to be a value that can actually occur.',
    },
    formulas: ['expected-value', 'rv-variance'], glossary: ['expected-value-term', 'rv-sd', 'fair-game'],
  },
  {
    id: 'transform', unit: 'u5', section: '4.1–4.2', title: 'Transforming & Combining Random Variables',
    short: 'Adding or multiplying by constants, and sums of independent random variables.',
    source: { ...S41, pages: [29, 30, 4] }, prereqs: ['expected-value'], related: ['expected-value', 'binomial'],
    confusedWith: [{ id: 'expected-value', why: 'Uses E(X) and σ but asks how they change.' }],
    difficulty: 3, importance: 3, minutes: 12, dims: ['recognize', 'calculate', 'interpret', 'apply'],
    know: ['Add/subtract constant: center shifts, spread & shape unchanged', 'Multiply/divide: center and SD scale, shape unchanged'], understand: ['Combining independent X + Y builds a new distribution'],
    calculate: ['New E and σ after a transformation; distribution of X + Y'], interpret: ['Explain why a fee changes E but not σ'],
    misconceptions: ['add-const-sd', 'mult-const-var'],
    why: { analogy: 'Adding a $5 fee to every bet is like sliding the whole distribution $5 to the left — the shape and spread don\'t change. Halving every bet is like shrinking a photo: everything, including the spread, gets half as big.', body: 'Spread measures distances between outcomes. Adding a constant moves every outcome equally, so distances don\'t change. Multiplying stretches every distance by the same factor, so the SD scales by that factor (and the variance by its square).' },
    memoryTrick: '"**Add slides, multiply stretches.**" Shape never changes.',
    lesson: [
      { kind: 'hook', title: 'Changing your betting strategy', body: 'The $100 roulette bet has E(X) = −$5.26 and σ ≈ $99.86. What happens if you bet **half as much**? What if the casino charges a **$5 fee** per bet?' },
      { kind: 'interact', title: 'Slide and stretch', widget: 'transform', props: { preset: 'roulette' }, prompt: 'Use the "add" and "multiply" sliders. Watch the mean, the SD, and the shape.', takeaway: 'Adding shifts the mean only. Multiplying scales both the mean and SD.' },
      { kind: 'explain', title: 'The transformation table (p.30)', body: '| | Center | Spread | Shape |\n|---|---|---|---|\n| Add/subtract constant | shifts by the constant | **unchanged** | unchanged |\n| Multiply/divide by constant | multiplied/divided | SD multiplied/divided (variance by the square) | unchanged |\n\nHalf bet: E = −$2.63, σ ≈ $49.93. $5 fee: E = −$10.26, σ ≈ $99.86.', source: { pages: [30, 29], section: S41.section } },
      { kind: 'check', prompt: 'A casino adds a $5 fee to the $100 roulette bet (σ ≈ $99.86). The new SD is…', input: { type: 'mc', options: [
        { id: 'a', text: 'About $99.86 (unchanged)', correct: true, why: 'Subtracting a constant shifts every outcome equally.' },
        { id: 'b', text: 'About $94.86', why: 'Adding/subtracting a constant does not change spread.', misconception: 'add-const-sd' },
        { id: 'c', text: 'About $104.86', why: 'Spread is unchanged by a shift.', misconception: 'add-const-sd' },
      ] }, explain: 'Shifts don\'t change spread.' },
      { kind: 'check', prompt: 'If X has variance 9, what is the variance of 2X?', input: { type: 'number', answer: 36, tol: 0.01 }, explain: 'SD goes 3 → 6, so variance goes 9 → 36 (multiplied by 2² = 4).' },
      { kind: 'worked', title: 'Practice #3 — two slot machines', problem: 'Machine 1: −$20 (0.80), +$20 (0.20). Machine 2: −$20 (0.70), +$20 (0.30). Independent. Z = X + Y.', steps: [
        { label: 'Lose both', body: 'Z = −40: (0.80)(0.70) = 0.56.' },
        { label: 'Win one, lose one', body: 'Z = 0: (0.80)(0.30) + (0.20)(0.70) = 0.38.' },
        { label: 'Win both', body: 'Z = 40: (0.20)(0.30) = 0.06.' },
        { label: 'E and σ', body: 'E(Z) = −20; σ² = 1600(0.56) + 0 + 1600(0.06) − (−20)² = 592 → σ ≈ $24.33.' },
      ], answer: 'Build the new distribution with the multiplication rule, then compute E and σ.', source: { pages: [4], section: '4.1–4.2 Practice #3' } },
      { kind: 'summary', points: ['Add/subtract: center shifts; spread and shape stay.', 'Multiply/divide: center and SD scale; variance by c².', 'X + Y (independent): multiply probabilities to build the new table.'] },
    ],
    recall: [{ prompt: 'Fill in: multiplying a random variable by 3 multiplies its mean by __, its SD by __, and its variance by __.', answer: '3, 3, and 9.' }],
    teach: {
      prompt: 'Explain how adding a constant and multiplying by a constant change the center, spread, and shape of a probability distribution.',
      items: [
        { id: 'addc', idea: 'Adding shifts the center', patterns: ['add.{0,80}(shift|center|mean).{0,40}(change|shift|move|by)'], weight: 1 },
        { id: 'adds', idea: 'Adding doesn\'t change spread', patterns: ['add.{0,120}(spread|sd|standard deviation|variance).{0,40}(same|unchanged|doesn.t|does not|no change)'], weight: 1.5 },
        { id: 'mult', idea: 'Multiplying scales center and SD', patterns: ['multipl.{0,120}(sd|standard deviation|spread)'], weight: 1 },
        { id: 'shape', idea: 'Shape unchanged', patterns: ['shape.{0,40}(same|unchanged|doesn.t|does not|no change)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['add.{0,60}(increase|change)s? the (sd|standard deviation|spread)'], message: 'Adding a constant does not change the spread.' }],
      model: 'Adding or subtracting a constant slides the whole distribution: the mean shifts by that constant, but the spread (SD) and shape stay the same, because every outcome moves the same amount. Multiplying or dividing by a constant stretches or shrinks it: the mean and the SD are multiplied by the constant (the variance by its square), and the shape still doesn\'t change.',
    },
    formulas: ['expected-value', 'rv-variance'], glossary: ['linear-transformation'],
  },
  {
    id: 'binomial', unit: 'u5', section: '4.3', title: 'Binomial Distributions',
    short: 'Counting successes in n independent yes/no trials.',
    source: S43, prereqs: ['independence', 'expected-value'], related: ['trees-venn', 'prob-dist'],
    confusedWith: [{ id: 'trees-venn', why: 'Small binomial problems can be solved with a tree.' }],
    difficulty: 4, importance: 5, minutes: 20, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['Conditions: two outcomes, fixed n, independent trials, same p', 'X ~ B(n, p); μ = np, σ = √(npq)'], understand: ['Why technology (Stapplet) is used; why "≤ 10" instead of "= 10" when judging surprise'],
    calculate: ['Binomial probabilities (exact, at most, at least); mean and SD'], interpret: ['Mean and SD in context; was a result surprising?'],
    misconceptions: ['binom-conditions', 'binom-sd-np', 'binom-p-vs-q', 'strict-vs-inclusive', 'at-least-one'],
    why: { analogy: 'Guessing on a 10-question, 4-choice pop quiz is like flipping a lopsided coin (25% heads) ten times. The binomial distribution tells you how often you\'d get 0, 1, 2, … heads.', body: 'When every trial is an identical, independent yes/no gamble, the number of successes follows a predictable pattern. Each specific sequence with k successes has probability pᵏqⁿ⁻ᵏ, and there are "n choose k" such sequences — technology adds it all up for you.' },
    memoryTrick: '**BINS**: **B**inary outcomes, **I**ndependent trials, **N**umber of trials fixed, **S**ame p.',
    lesson: [
      { kind: 'hook', title: 'Darius Washington at the line', body: '2005 Conference USA final: Memphis trails Louisville **75–73**. Freshman Darius Washington is fouled on a three-point shot with **no time left**. He gets **three free throws**. He\'s a **72%** free-throw shooter.\n\nMake all 3 → Memphis wins. Make 2 → overtime. Make 0 or 1 → Memphis loses.' },
      { kind: 'predict', prompt: 'Guess the probability Memphis wins outright (all 3 made).', input: { type: 'slider', min: 0, max: 1, step: 0.01, answer: 0.373, tol: 0.1, label: 'P(win)' }, reveal: '0.72 × 0.72 × 0.72 ≈ **0.373**. Overtime (exactly 2 made) is even more likely: 3(0.72²)(0.28) ≈ **0.435**. Lose: ≈ **0.191**.' },
      { kind: 'interact', title: 'Shoot the free throws', widget: 'free-throws', prompt: 'Shoot one at a time (or simulate 1,000 games). Watch the win/overtime/lose probabilities update after each shot.', takeaway: 'Each shot is an independent trial with the same p = 0.72 — the setting for a binomial distribution.' },
      { kind: 'explain', title: 'Binomial experiments', body: 'A **binomial experiment** has:\n1. Two outcomes per trial ("success"/"failure").\n2. A **fixed number of trials n**.\n3. **Independent** trials.\n4. The **same probability of success p** each trial.\n\nThen X = number of successes follows a **binomial distribution**: "X follows a binomial distribution with n trials and probability of success p", written **X ~ B(n, p)**.\n\n$$\\mu = np, \\quad \\sigma^2 = npq, \\quad \\sigma = \\sqrt{npq}, \\quad q = 1 - p$$\n\nThe formal probability formula is beyond the course — we use **technology (Stapplet)**.', source: { pages: [25], section: S43.section, note: 'Condition wording supplied; the PDF leaves blanks for students to fill in.' } },
      { kind: 'interact', title: 'Binomial explorer', widget: 'binomial', props: { n: 10, p: 0.25 }, prompt: 'This is the pop quiz: X ~ B(10, 0.25). Find P(X = 6), then the chance of passing (6 or more). Then switch to Mr. Athey\'s 3-choice quiz (p = 1/3).', takeaway: 'With p = 1/3, the mean rises (3.33 vs. 2.5), the SD grows (1.49 vs. 1.37), and passing becomes more likely.' },
      { kind: 'check', prompt: 'Pop quiz: X ~ B(10, 0.25). Find the standard deviation σ.', input: { type: 'number', answer: Math.sqrt(10 * 0.25 * 0.75), tol: 0.005 }, explain: 'σ = √(10 · 0.25 · 0.75) = √1.875 ≈ **1.369** questions.' },
      { kind: 'check', prompt: 'Four traffic lights each turn red with probability 0.30. Why must they **not** run on a pre-programmed cycle for this to be binomial?', input: { type: 'mc', options: [
        { id: 'a', text: 'A pre-programmed cycle would make the lights dependent, breaking independence', correct: true, why: 'If one red light predicts the next, trials are not independent.' },
        { id: 'b', text: 'It would change the number of lights', why: 'n stays 4; the issue is independence.', misconception: 'binom-conditions' },
      ] }, explain: 'Independence is a binomial condition.' },
      { kind: 'worked', title: 'Practice #3 — "Draw a three, get it free"', problem: '250 customers each draw a card; a 3 (p = 4/52 = 1/13) wins free lunch. Only 10 people won. Surprised?', steps: [
        { label: 'Model', body: 'X ~ B(250, 1/13): two outcomes, fixed n = 250, independent draws, same p.' },
        { label: 'Mean & SD', body: 'μ = 250/13 ≈ 19.23 winners; σ = √(250 · (1/13)(12/13)) ≈ 4.21.' },
        { label: 'Why P(X ≤ 10)?', body: 'Any single exact value is unlikely with n = 250, so we ask how likely a result **this low or lower** is.' },
        { label: 'Technology', body: 'P(X ≤ 10) ≈ 0.013.' },
        { label: 'Conclusion', body: 'Only about a 1.3% chance → the customer has reason to be surprised (maybe the program isn\'t fair).' },
      ], answer: 'P(X ≤ 10) ≈ 0.013 — surprising.', source: { pages: [27], section: '4.3 Practice #3' } },
      { kind: 'summary', points: ['BINS conditions → X ~ B(n, p).', 'μ = np, σ = √(npq).', 'Use technology for probabilities; "this extreme or more" judges surprise.'] },
    ],
    recall: [{ prompt: 'List the four binomial conditions.', answer: 'Two outcomes (success/failure), fixed number of trials n, independent trials, same probability of success p.' }, { prompt: 'Write the binomial mean and SD formulas.', answer: 'μ = np; σ = √(npq), q = 1 − p.' }],
    teach: {
      prompt: 'Explain when a random variable follows a binomial distribution, and how to find and interpret its mean and standard deviation.',
      items: [
        { id: 'two', idea: 'Two outcomes per trial', patterns: ['two outcomes|success.{0,30}fail|binary|yes.{0,10}no'], weight: 1 },
        { id: 'n', idea: 'Fixed number of trials', patterns: ['fixed.{0,30}(number|n)|set number'], weight: 1 },
        { id: 'ind', idea: 'Independent trials', patterns: ['independen'], weight: 1 },
        { id: 'p', idea: 'Same probability of success', patterns: ['same (probability|p|chance)|constant p'], weight: 1 },
        { id: 'mean', idea: 'μ = np', patterns: ['n ?(·|\\*|times|×)? ?p\\b|np'], weight: 1 },
        { id: 'sd', idea: 'σ = √(npq)', patterns: ['npq|sqrt|square root'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['standard deviation.{0,20}(is|=) ?np\\b'], message: 'The binomial SD is √(npq), not np.' }],
      model: 'A random variable is binomial when it counts successes in a binomial experiment: each trial has two outcomes (success or failure), there is a fixed number of trials n, the trials are independent, and the probability of success p is the same every time. Then X ~ B(n, p). Its mean is μ = np, the expected number of successes in the long run, and its standard deviation is σ = √(npq) with q = 1 − p, the typical amount the number of successes varies from the mean. For the pop quiz, μ = 2.5 correct and σ ≈ 1.37.',
    },
    formulas: ['binom-mean-sd', 'binom-prob'], glossary: ['binomial-experiment', 'binomial-distribution', 'success'],
  },
];
