import type { Concept } from '../../engine/types';

const S21 = { pages: [57, 58, 59, 22, 23], section: '2.1–2.2, 2.5 Graphs & Measures of Center' };
const S24 = { pages: [53, 54, 55, 56, 20, 21], section: '2.4, 2.6 Shape, Position & Boxplots' };
const S27 = { pages: [50, 51, 52, 17, 18, 19], section: '2.7 Measures of Spread' };
const S28 = { pages: [48, 49, 15, 16], section: '2.8 Comparing Distributions' };

export const UNIT2: Concept[] = [
  {
    id: 'quant-graphs', unit: 'u2', section: '2.1–2.2', title: 'Graphing Quantitative Data',
    short: 'Stem-and-leaf plots, dotplots, and histograms.',
    source: S21, prereqs: ['data-types', 'freq-tables'], related: ['center', 'shape', 'cat-displays'],
    confusedWith: [{ id: 'cat-displays', why: 'Histograms (quantitative) vs. bar graphs (categorical).' }],
    difficulty: 2, importance: 3, minutes: 12, dims: ['recognize', 'calculate', 'interpret', 'apply'],
    know: ['Stem-and-leaf (with key), side-by-side stem plots, dotplots, histograms'], understand: ['Each display trades detail for readability; histograms suit large data sets'],
    calculate: ['Build a stem plot; read counts/percents from a (relative frequency) histogram'], interpret: ['Read percentages from a histogram'],
    misconceptions: ['histogram-vs-bar', 'cumulative-confusion'],
    why: { analogy: 'A dotplot is a class photo (everyone visible). A stem plot is a yearbook page organized by homeroom. A histogram is the school population chart by grade — great for big groups, but you lose individual faces.', body: 'As data sets grow, showing every value becomes cluttered, so we group values into intervals (histograms). Smaller sets can keep every value (dotplots, stem plots), which makes exact calculations easy.' },
    memoryTrick: 'Stem = everything but the last digit; leaf = the last digit. Always include a **key** (7|7 = 77).',
    lesson: [
      { kind: 'hook', title: 'Moneyball', body: 'In 2002, the Oakland A\'s had one of the **lowest payrolls** in baseball — about $40 million — yet competed with teams spending $126 million. How can we *see* how payrolls were spread across all 30 teams?' },
      { kind: 'explain', title: 'Stem-and-leaf plots', body: 'Split each number into a **stem** (leading digits) and a **leaf** (last digit). List stems in order — including empty ones — and leaves in increasing order. A **key** tells the reader how to read it.\n\nA **side-by-side** stem plot shares the stems between two data sets (2003 payroll leaves on the left, 2002 on the right).', visual: { type: 'stemleaf', keyText: '7|7 = 77 years', rows: [{ stem: 1, leaves: [8] }, { stem: 2, leaves: [1, 2, 5, 6, 7, 9] }, { stem: 3, leaves: [0, 1, 3, 6, 7] }, { stem: 4, leaves: [1, 2, 7] }, { stem: 5, leaves: [2, 5, 7, 8] }, { stem: 6, leaves: [2, 4, 7, 9] }, { stem: 7, leaves: [1, 2, 3, 4, 6, 7] }] }, source: { pages: [57, 22], section: S21.section } },
      { kind: 'interact', title: 'Build a stem plot', widget: 'stemleaf', props: { dataset: 'actors' }, prompt: 'Watch the Academy Award actor ages drop into their stems. Then try the payroll data.', takeaway: 'You can still read every value, and the shape appears sideways.' },
      { kind: 'explain', title: 'Dotplots and histograms', body: 'A **dotplot** shows every value as a dot — easy to compute with, but crowded for large data.\n\nA **histogram** groups values into equal intervals (typically 5–15 bars) with **touching** bars. It is not a bar graph: bar graphs are for categories.', visual: { type: 'histogram', xLabel: '2003 Payroll ($ millions)', bins: [{ lo: 20, hi: 40, count: 1 }, { lo: 40, hi: 60, count: 13 }, { lo: 60, hi: 80, count: 5 }, { lo: 80, hi: 100, count: 5 }, { lo: 100, hi: 120, count: 5 }, { lo: 120, hi: 140, count: 0 }, { lo: 140, hi: 160, count: 1 }] }, source: { pages: [58], section: S21.section } },
      { kind: 'interact', title: 'Change the bins', widget: 'histogram-builder', props: { dataset: 'payroll-2002' }, prompt: 'Drag the bin-width slider. Too few bins hide the shape; too many make it noisy.', takeaway: 'The same data can look different with different bins — choose a width that shows the overall pattern.' },
      { kind: 'check', prompt: 'In the t-shirt survey (111 shoppers), the relative frequencies for owning 1, 2, and 3 shirts are 5/111, 17/111, and 23/111. What **percent** own at most three?', input: { type: 'number', answer: 45 / 111 * 100, tol: 0.3, unit: '%' }, explain: '(5 + 17 + 23)/111 = 45/111 ≈ 0.405 → **40.5%**. "At most three" means add 1, 2, and 3.', visual: { type: 'histogram', relative: true, xLabel: 'T-shirts costing more than $19', bins: [{ lo: 0.5, hi: 1.5, count: 5 / 111 }, { lo: 1.5, hi: 2.5, count: 17 / 111 }, { lo: 2.5, hi: 3.5, count: 23 / 111 }, { lo: 3.5, hi: 4.5, count: 39 / 111 }, { lo: 4.5, hi: 5.5, count: 25 / 111 }, { lo: 5.5, hi: 6.5, count: 2 / 111 }] } },
      { kind: 'worked', title: 'Practice 2.1 #4 — AP Statistics scores', problem: 'A histogram shows AP scores 1–5 with frequencies 3, 4, 2, 7, 4.', visual: { type: 'histogram', xLabel: 'AP score', bins: [{ lo: 0.5, hi: 1.5, count: 3 }, { lo: 1.5, hi: 2.5, count: 4 }, { lo: 2.5, hi: 3.5, count: 2 }, { lo: 3.5, hi: 4.5, count: 7 }, { lo: 4.5, hi: 5.5, count: 4 }] }, steps: [
        { label: 'Sample size', body: 'Σf = 3 + 4 + 2 + 7 + 4 = 20 students.' },
        { label: 'Scored a 4', body: '7/20 = 0.35 → 35%.' },
        { label: 'Passed (3 or higher)', body: '(2 + 7 + 4)/20 = 13/20 = 65%.' },
      ], answer: 'n = 20; 35% scored a 4; 65% passed.', source: { pages: [23], section: '2.1–2.2 Practice #4' } },
      { kind: 'summary', points: ['Stem plots and dotplots keep every value (small data).', 'Histograms group values into touching intervals (large data).', 'Histograms ≠ bar graphs.'] },
    ],
    recall: [{ prompt: 'Name one advantage and one disadvantage of a dotplot.', answer: 'Advantage: shows every value and is easy to compute from. Disadvantage: becomes crowded/impractical for large data sets.' }],
    teach: {
      prompt: 'Compare stem-and-leaf plots, dotplots, and histograms. When is each most useful?',
      items: [
        { id: 'stem', idea: 'Stem plots split values into stems/leaves and keep data values', patterns: ['stem.{0,80}(leaf|digit|key)'], weight: 1 },
        { id: 'dot', idea: 'Dotplots show each value; best for small data', patterns: ['dot.{0,80}(each|every|individual|small)'], weight: 1 },
        { id: 'hist', idea: 'Histograms group into intervals; best for large data', patterns: ['histogram.{0,100}(interval|bin|group|class|range|large)'], weight: 1 },
        { id: 'bar', idea: 'Histograms are not bar graphs (touching bars, quantitative)', patterns: ['touch|no gaps|quantitative|not a bar'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['histogram.{0,40}categor'], message: 'Histograms display quantitative data, not categories.' }],
      model: 'A stem-and-leaf plot splits each value into a stem and a leaf (with a key), so you see the shape while keeping every value — good for small to medium data. A dotplot puts a dot for each value on a number line — also best for small data and easy to calculate from. A histogram groups values into equal intervals with touching bars; it handles large data sets but hides individual values. Histograms are for quantitative data, unlike bar graphs.',
    },
    formulas: [], glossary: ['stem-leaf', 'dotplot', 'histogram'],
  },
  {
    id: 'center', unit: 'u2', section: '2.1–2.2, 2.5', title: 'Measures of Center',
    short: 'Mean, median, mode, and midrange — and which one is "typical".',
    source: { ...S21, pages: [58, 59, 22, 23, 1, 2] }, prereqs: ['quant-graphs'], related: ['shape', 'outliers', 'compare', 'expected-value'],
    confusedWith: [{ id: 'expected-value', why: 'E(X) is a weighted mean for probability distributions.' }, { id: 'shape', why: 'Mean vs. median reveals skew.' }],
    difficulty: 2, importance: 5, minutes: 14, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['x̄ vs. μ, n vs. N, median (MD), mode, midrange'], understand: ['The median is resistant; the mean is pulled toward outliers and tails'],
    calculate: ['Mean, median (odd and even n), mode, midrange', 'Estimate mean/median from a histogram using midpoints'],
    interpret: ['"The average … is …"; "Half of the … are above and half below …"'],
    misconceptions: ['median-unsorted', 'median-even-n', 'mean-resistant', 'wrong-measure-skew'],
    why: { analogy: 'Ten people are in a coffee shop earning ~$50k. A billionaire walks in. The **mean** income rockets to $90 million — but the **median** barely moves. Which better describes the typical customer?', body: 'The mean uses the actual size of every value, so one extreme value drags it. The median only cares about *order*, so it stays put. That is why skewed data (incomes, payrolls, hurricane deaths) are described with the median.' },
    memoryTrick: '**Median** = middle of the road (like a highway median). **Mean** = "mean" bully who gets pushed around by outliers.',
    lesson: [
      { kind: 'hook', title: 'Two players, same average', body: 'Player A scores 19, 20, 21, 20, 20. Player B scores 5, 35, 8, 40, 12.\n\nBoth "average 20 points" … do they? And what number best describes a *typical* game?' },
      { kind: 'predict', prompt: 'Player B\'s scores: 5, 35, 8, 40, 12. Predict the **median** (middle value).', input: { type: 'number', answer: 12, tol: 0.01, placeholder: 'median' }, reveal: 'Sorted: 5, 8, **12**, 35, 40 → median = 12, while the mean is 100 ÷ 5 = **20**. The two big games pull the mean up but not the median.' },
      { kind: 'explain', title: 'Mean and median', body: '- **Mean**: add the values and divide by how many. Sample mean $\\bar{x} = \\frac{\\sum x}{n}$; population mean $\\mu = \\frac{\\sum x}{N}$.\n- **Median (MD)**: the middle of the **sorted** data. With an even n, average the two middle values.\n- **Mode**: most frequent value. **Midrange**: (min + max)/2 — these two often fail to represent the "typical" value.', source: { pages: [58], section: S21.section } },
      { kind: 'formula', formulaId: 'mean' },
      { kind: 'interact', title: 'Drag the data', widget: 'drag-mean', props: { data: [46, 59, 48, 19, 47, 41, 39, 45, 28, 50, 50, 41, 49, 34], label: 'Air in chip bags (%)' }, prompt: 'These are the chip-bag air percentages. Drag one dot far to the right (like adding "Helium Chips" at 78%). Watch which marker moves more.', takeaway: 'The mean chases outliers; the median barely moves. The median is **resistant**.' },
      { kind: 'check', prompt: 'Chip air %: x̄ = 42.571 and MD = 45.5. Why is the mean **less** than the median?', input: { type: 'mc', options: [
        { id: 'a', text: 'A few bags with unusually low air (like Fritos at 19%) pull the mean down', correct: true, why: 'Low values drag the mean but not the median.' },
        { id: 'b', text: 'The median is always larger than the mean', why: 'It depends on the shape; for right-skewed data the mean is larger.', misconception: 'mean-median-skew' },
        { id: 'c', text: 'There must be a calculation error', why: 'Mean and median are usually different.' },
      ] }, explain: 'Low outliers drag the mean below the median.' },
      { kind: 'worked', title: 'Estimating center from a histogram (Practice 2.1 #2)', problem: '111 shoppers own 1–6 shirts with frequencies 5, 17, 23, 39, 25, 2. Estimate the mean and median.', steps: [
        { label: 'Mean', body: 'Use each bar\'s value as a placeholder: $\\frac{1(5) + 2(17) + 3(23) + 4(39) + 5(25) + 6(2)}{111} = \\frac{401}{111} \\approx 3.613$.' },
        { label: 'Median position', body: 'n = 111 → middle is about the 55.5th value.' },
        { label: 'Find the bar', body: 'Cumulative: 5, 22, 45, **84** — the 55.5th value is in the "4" bar.' },
      ], answer: 'x̄ ≈ 3.613 shirts; MD = 4 shirts.', source: { pages: [22], section: '2.1–2.2 Practice #2' } },
      { kind: 'check', prompt: 'Find the median of the McDonald\'s fat data: 27, 11, 22, 21, 40, 8, 17, 15, 29, 31, 27, 26.', input: { type: 'number', answer: 24, tol: 0.01, unit: 'g' }, explain: 'Sorted: 8, 11, 15, 17, 21, **22, 26**, 27, 27, 29, 31, 40. n = 12 is even → (22 + 26)/2 = **24 g**.' },
      { kind: 'recall', prompt: 'When should you report the median instead of the mean? Why?', answer: 'When data are skewed or have outliers — the median is resistant, while the mean is pulled toward the tail.' },
      { kind: 'summary', points: ['x̄ (sample) and μ (population) = sum ÷ count.', 'Median = middle of sorted data; resistant to outliers.', 'Skewed data → median describes the typical value better.'] },
    ],
    recall: [{ prompt: 'Interpret x̄ = 48.111 for the net worth of 45 sampled corporations ($ billions).', answer: 'The average net worth of the 45 sampled national corporations is about $48.111 billion.' }, { prompt: 'Interpret MD = 45 for the same data.', answer: 'Half of the sampled corporations have a net worth above $45 billion and half below.' }],
    teach: {
      prompt: 'Explain the difference between the mean and the median, and when each is the better measure of center.',
      items: [
        { id: 'mean', idea: 'Mean = sum divided by count', patterns: ['(add|sum|total).{0,60}(divid|÷|by the number|count|how many)'], weight: 1 },
        { id: 'med', idea: 'Median = middle of sorted data', patterns: ['middle|half (above|below)|50'], weight: 1 },
        { id: 'resist', idea: 'Median resistant / mean affected by outliers', patterns: ['outlier|extreme|resistant|pull|skew'], weight: 1 },
        { id: 'when', idea: 'Use mean for symmetric, median for skewed', patterns: ['symmetric.{0,80}mean|skew.{0,80}median|median.{0,80}skew'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['mean.{0,30}(is )?resistant', 'median.{0,40}(affected|pulled) by outlier'], message: 'It\'s the median that is resistant; the mean is pulled by outliers.' }],
      model: 'The mean adds all values and divides by how many there are, so every value — including extreme ones — affects it. The median is the middle value of the sorted data: half the values are above and half below, and it barely changes when an outlier appears (it is resistant). For roughly symmetric data the mean works well; for skewed data or data with outliers, like payrolls or hurricane deaths, the median better represents the typical value.',
    },
    formulas: ['mean', 'median', 'midrange'], glossary: ['mean', 'median', 'mode', 'midrange', 'summary-statistics'],
  },
  {
    id: 'shape', unit: 'u2', section: '2.4, 2.6', title: 'Shape of a Distribution',
    short: 'Symmetric, skewed right/left, uniform, bimodal — and what mean vs. median reveals.',
    source: { ...S24, pages: [53, 20, 21] }, prereqs: ['center'], related: ['center', 'boxplots', 'compare'],
    confusedWith: [{ id: 'center', why: 'Comparing mean and median tells you the shape.' }],
    difficulty: 2, importance: 5, minutes: 12, dims: ['recognize', 'interpret', 'apply', 'explain'],
    know: ['Symmetric, skewed right, skewed left, uniform, bimodal'], understand: ['Skew is named for the tail; mean is pulled toward the tail'],
    calculate: [], interpret: ['Infer shape from mean vs. median; choose the best measure of center'],
    misconceptions: ['skew-direction', 'mean-median-skew'],
    why: { analogy: 'Skew is like a kite: the **tail** tells the direction. A few huge salaries form a tail to the right — the kite flies right — and the mean gets dragged along the string toward the tail.', body: 'In a skewed distribution, the long tail contains a few extreme values. Those extremes pull the mean toward them but don\'t move the median, so the mean ends up on the tail side of the median.' },
    memoryTrick: '"The mean follows the tail." Tail right → mean > median. Tail left → mean < median.',
    lesson: [
      { kind: 'hook', title: 'Marine fitness test', body: 'The US Marine Corps tested 268 students in grades 6–12. Scores of 40+ meant "as fit as a new recruit." Students were split into groups, and each group\'s histogram looks different. Can you tell which histogram is the youngest students?' },
      { kind: 'explain', title: 'Five shapes', body: '- **Symmetric**: balanced on both sides; mean ≈ median ≈ mode.\n- **Skewed right**: long tail to the right; most values fall **below** the mean; mode < median < mean.\n- **Skewed left**: long tail to the left; mean < median < mode.\n- **Uniform**: evenly spread across the whole range.\n- **Bimodal**: two peaks — usually two groups mixed together that should be **separated**.', visual: { type: 'shape', shape: 'right' }, source: { pages: [53], section: S24.section } },
      { kind: 'interact', title: 'Skew it yourself', widget: 'shape', prompt: 'Drag the skew slider left and right. Watch where the mean and median land.', takeaway: 'The mean always moves toward the tail; the median lags behind.' },
      { kind: 'predict', prompt: 'Professor Delta\'s exam: μ = 75.7, MD = 68. The distribution is probably…', input: { type: 'mc', options: [
        { id: 'a', text: 'Skewed right', correct: true, why: 'Mean > median → a tail of high scores pulls the mean up.' },
        { id: 'b', text: 'Skewed left', why: 'For left skew, the mean would be *below* the median.', misconception: 'mean-median-skew' },
        { id: 'c', text: 'Symmetric', why: 'A 7.7-point gap is too big for symmetric.' },
      ] }, reveal: 'Mean > median → **skewed right**, so the median (68) better represents a typical score. Possible outliers are high scores in the right tail.' },
      { kind: 'worked', title: 'Practice 2.4, 2.6 #1 — Three professors', problem: 'Gamma: μ = 67.3, MD = 72. Delta: μ = 75.7, MD = 68. Epsilon: μ = 66.8, MD = 67.', steps: [
        { label: 'Gamma', body: 'Mean < median → **skewed left**; use the median; possible low outliers.' },
        { label: 'Delta', body: 'Mean > median → **skewed right**; use the median; possible high outliers.' },
        { label: 'Epsilon', body: 'Mean ≈ median → **approximately symmetric**; the mean is a good measure.' },
      ], answer: 'Compare mean and median to read the shape.', source: { pages: [20], section: '2.4, 2.6 Practice #1' } },
      { kind: 'check', prompt: 'A histogram has two clear peaks: one around 15 and one around 45. What should you suspect?', input: { type: 'mc', options: [
        { id: 'a', text: 'Two different groups are mixed together and should be separated', correct: true, why: 'Bimodal data usually signal two groups (e.g., younger and older students).' },
        { id: 'b', text: 'The data are uniform', why: 'Uniform has no peaks.' },
        { id: 'c', text: 'There is an error — data always have one peak', why: 'Bimodal distributions are real and informative.' },
      ] }, explain: 'Bimodal → separate the groups before summarizing.' },
      { kind: 'recall', prompt: 'For a distribution skewed left, order the mean, median, and mode.', answer: 'Mean < median < mode.' },
      { kind: 'summary', points: ['Skew is named for the tail.', 'Mean follows the tail: right skew → mean > median.', 'Bimodal → separate the groups.'] },
    ],
    recall: [{ prompt: 'Why is the median a better measure of center for skewed data?', answer: 'Because the mean is pulled toward the tail by extreme values, while the median is resistant.' }],
    teach: {
      prompt: 'Explain how to tell whether a distribution is skewed right, skewed left, or symmetric — both from a graph and from the mean and median.',
      items: [
        { id: 'tail', idea: 'Skew is named by the direction of the tail', patterns: ['tail'], weight: 1 },
        { id: 'right', idea: 'Right skew: mean > median', patterns: ['right.{0,80}mean.{0,30}(greater|larger|bigger|more|higher|>)|mean.{0,30}(greater|larger|>).{0,40}median.{0,60}right'], weight: 1 },
        { id: 'left', idea: 'Left skew: mean < median', patterns: ['left.{0,80}mean.{0,30}(less|smaller|lower|<)|mean.{0,30}(less|smaller|<).{0,40}median.{0,60}left'], weight: 1 },
        { id: 'sym', idea: 'Symmetric: mean ≈ median', patterns: ['symmetric.{0,80}(equal|same|about|close|similar|≈)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['right.{0,40}peak.{0,20}right', 'skewed right.{0,60}mean.{0,20}(less|smaller)'], message: 'Skew is named for the tail, and in right-skewed data the mean is larger than the median.' }],
      model: 'Skew is named for the side with the long tail. In a right-skewed distribution, a few large values form a tail on the right and pull the mean above the median. In a left-skewed distribution, the tail is on the left and the mean falls below the median. In a symmetric distribution the two sides mirror each other and the mean is about equal to the median.',
    },
    formulas: [], glossary: ['shape-symmetric', 'skewed-right', 'skewed-left', 'uniform-shape', 'bimodal'],
  },
  {
    id: 'position', unit: 'u2', section: '2.4, 2.6', title: 'Percentiles & Quartiles',
    short: 'Measures of position and the five-number summary.',
    source: { ...S24, pages: [54, 19] }, prereqs: ['center'], related: ['boxplots', 'range-iqr', 'z-score'],
    confusedWith: [{ id: 'z-score', why: 'Both describe position — percentiles by rank, z-scores by SDs.' }],
    difficulty: 3, importance: 4, minutes: 12, dims: ['recognize', 'calculate', 'interpret', 'apply'],
    know: ['Percentile = % of data with lesser value', 'Q1 = 25th, median = 50th, Q3 = 75th percentile', 'Five-number summary'],
    understand: ['Quartiles are medians of the lower and upper halves'],
    calculate: ['Five-number summary by hand (Stapplet method)', 'Percentile of a value; value at a percentile'], interpret: ['"Scored better than 80% of test takers"'],
    misconceptions: ['quartile-include-median', 'percentile-vs-percent', 'median-unsorted'],
    why: { analogy: 'Percentile = your place in a race measured by how many runners are behind you. Finishing at the 80th percentile means you beat 80% of the runners — even if your time was slow.', body: 'Raw scores mean little without context (is 1200 on the SAT good?). Position measures compare a value to the rest of the data, and quartiles chop the sorted data into four equal-count chunks.' },
    memoryTrick: 'Quartiles = "**medians of the halves**." Odd n? Leave the median out of both halves.',
    lesson: [
      { kind: 'hook', title: 'The speed trap', body: 'A state trooper clocks 19 northbound cars: 60, 62, 62, 63, 63, 63, 64, 64, 64, 65, 65, 65, 65, 66, 66, 67, 68, 70, 83 mph.\n\nHow could you describe where a car going 66 mph stands compared to the others?' },
      { kind: 'explain', title: 'Percentiles and quartiles', body: 'A **percentile** gives the percent of data values with **lesser value**. Scoring at the 80th percentile on the SAT means scoring **better than 80%** of other test takers.\n\n**Quartiles** split sorted data into four parts:\n- **Q1** (25th percentile) = median of the lower half\n- **Median** (50th percentile)\n- **Q3** (75th percentile) = median of the upper half\n\nThe **five-number summary** is min, Q1, median, Q3, max.', source: { pages: [54], section: S24.section } },
      { kind: 'worked', title: 'Five-number summary by hand (speed trap)', problem: '19 sorted speeds.', steps: [
        { label: 'Median', body: 'n = 19 → 10th value = **65**.' },
        { label: 'Lower half', body: 'The 9 values below the median: 60 62 62 63 **63** 63 64 64 64 → Q1 = 5th = **63**.' },
        { label: 'Upper half', body: 'The 9 values above the median: 65 65 65 66 **66** 67 68 70 83 → Q3 = **66**.' },
        { label: 'Min & max', body: '60 and 83.' },
      ], answer: 'Five-number summary: 60, 63, 65, 66, 83. (Odd n: leave the median out of both halves — the method Stapplet uses.)', source: { pages: [54], section: '2.4, 2.6 Example 2' } },
      { kind: 'interact', title: 'Percentile explorer', widget: 'percentile', props: { dataset: 'speeds-north' }, prompt: 'Click any car on the dotplot. See its percentile and where it falls relative to the quartiles.', takeaway: 'Percentile = (number of values below) ÷ n.' },
      { kind: 'check', prompt: 'Maryland has 8 representatives; **29 of the 50 states** have fewer. Maryland\'s percentile?', input: { type: 'number', answer: 58, tol: 0.5, unit: 'th percentile' }, explain: '29/50 = 0.58 → **58th percentile**.' },
      { kind: 'check', prompt: 'South Carolina is at the 52nd percentile of the 50 states. How many states have fewer representatives than South Carolina?', input: { type: 'number', answer: 26, tol: 0.01 }, explain: '0.52 × 50 = 26 states below — South Carolina is the next one up (it had 6 representatives).' },
      { kind: 'recall', prompt: 'How do you find Q1 and Q3 when n is odd?', answer: 'Find the median, leave it out, then take the median of the lower half (Q1) and of the upper half (Q3).' },
      { kind: 'summary', points: ['Percentile = % of values below.', 'Q1, median, Q3 = 25th, 50th, 75th percentiles.', 'Five-number summary feeds the boxplot.'] },
    ],
    recall: [{ prompt: 'What does it mean to score at the 90th percentile?', answer: 'You scored higher than 90% of the data values (test takers).' }],
    teach: {
      prompt: 'Explain percentiles, quartiles, and how to find the five-number summary.',
      items: [
        { id: 'pct', idea: 'Percentile = % of values below', patterns: ['percent.{0,60}(below|less|lower|behind|beat|better than)'], weight: 1 },
        { id: 'q', idea: 'Q1/Q3 = 25th/75th percentiles or medians of halves', patterns: ['25|75|half|halves'], weight: 1 },
        { id: 'five', idea: 'Five-number summary = min, Q1, median, Q3, max', patterns: ['min.{0,80}max|five.number'], weight: 1 },
        { id: 'sort', idea: 'Sort data first', patterns: ['sort|order|smallest to largest|least to greatest'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['percentile.{0,40}(percent correct|score out of)'], message: 'A percentile is about rank among the data, not percent correct.' }],
      model: 'A percentile tells you the percent of data values that are below a value — the 80th percentile beats 80% of the data. Quartiles split sorted data into four equal-count parts: Q1 is the 25th percentile (median of the lower half), the median is the 50th, and Q3 is the 75th (median of the upper half). The five-number summary lists the minimum, Q1, median, Q3, and maximum, found after sorting the data.',
    },
    formulas: ['percentile'], glossary: ['percentile', 'quartile', 'five-number'],
  },
  {
    id: 'boxplots', unit: 'u2', section: '2.4, 2.6', title: 'Boxplots',
    short: 'Drawing and reading (comparative) boxplots.',
    source: { ...S24, pages: [54, 55, 56, 2, 15, 21] }, prereqs: ['position'], related: ['outliers', 'compare', 'shape'],
    confusedWith: [{ id: 'quant-graphs', why: 'Boxplots summarize; histograms show the full shape.' }],
    difficulty: 3, importance: 4, minutes: 12, dims: ['recognize', 'interpret', 'apply', 'explain'],
    know: ['Box from Q1 to Q3, median line, whiskers to min/max, outliers as dots'], understand: ['Each section holds about 25% of the data; length shows spread, not count'],
    calculate: ['Approximate percentages from a boxplot'], interpret: ['Compare groups with comparative boxplots'],
    misconceptions: ['box-length-count', 'boxplot-sample-size', 'skew-direction'],
    why: { analogy: 'A boxplot is like four equally-sized groups of runners in a race. Each group has the same number of people; a long gap just means that group was strung out over more ground.', body: 'Because quartiles split the data into four equal-count chunks, each piece of a boxplot holds ~25% of the data. Its *length* tells you how spread out that 25% is.' },
    memoryTrick: '"**Four quarters, four pieces**" — whisker, half-box, half-box, whisker: 25% each.',
    lesson: [
      { kind: 'hook', title: 'Are female-named hurricanes deadlier?', body: 'Researchers split deadly hurricanes from 1950–2012 into "male" and "female" names (big outliers like Katrina removed). Female hurricanes have mean 23.758 deaths; male have 14.233. Case closed?', visual: { type: 'boxplot', xLabel: 'Total # of deaths', groups: [{ label: 'Female', min: 0, q1: 2, median: 5, q3: 21, max: 256 }, { label: 'Male', min: 0, q1: 1, median: 5, q3: 15, max: 84 }] } },
      { kind: 'explain', title: 'Anatomy of a boxplot', body: 'A **boxplot** draws the five-number summary: a **box** from Q1 to Q3 with a line at the **median**, and **whiskers** to the min and max. Modified boxplots show outliers as separate dots.\n\nEach of the four sections contains about **25%** of the data. A longer section means more spread — **not** more data. Boxplots do not show the sample size.', source: { pages: [54, 55], section: S24.section } },
      { kind: 'interact', title: 'Build a boxplot', widget: 'boxplot-builder', props: { dataset: 'speeds-north' }, prompt: 'Step through the five-number summary and watch the boxplot assemble. Toggle "show outliers".', takeaway: 'The 83 mph car is far beyond the rest — a modified boxplot shows it as a dot.' },
      { kind: 'check', prompt: 'Hurricanes: female Q1 = 2, median = 5. About what percent of female hurricanes had between 2 and 5 deaths?', input: { type: 'mc', options: [
        { id: 'a', text: 'About 25%', correct: true, why: 'Q1 to median is one quarter of the data.' },
        { id: 'b', text: 'About 50%', why: 'Q1 to Q3 is 50%; Q1 to the median is 25%.' },
        { id: 'c', text: 'It depends on the sample size', why: 'Percentages from quartiles don\'t depend on n.', misconception: 'boxplot-sample-size' },
      ] }, explain: 'Q1 → median = 25% of the data.' },
      { kind: 'check', prompt: 'In the female boxplot, the right whisker is extremely long (21 → 256). What does that mean?', input: { type: 'mc', options: [
        { id: 'a', text: 'The top 25% of values are very spread out — a right skew with likely outliers', correct: true, why: 'Long right whisker = spread-out high values = right skew.' },
        { id: 'b', text: 'Most female hurricanes had over 100 deaths', why: 'Only the top 25% lie on that whisker.', misconception: 'box-length-count' },
        { id: 'c', text: 'There are more female hurricanes', why: 'Boxplots don\'t show sample size.', misconception: 'boxplot-sample-size' },
      ] }, explain: 'A long section = spread, not count.' },
      { kind: 'worked', title: 'Hurricanes — can we conclude female names are deadlier?', problem: 'Male: mean 14.233, SD 21.162, 0/1/5/15/84. Female: mean 23.758, SD 47.466, 0/2/5/21/256.', steps: [
        { label: 'Shape', body: 'Both are strongly **skewed right** (means far above medians).' },
        { label: 'Center', body: 'Because of the skew, compare **medians**: both are **5** deaths.' },
        { label: 'Spread', body: 'IQR female = 21 − 2 = 19; male = 15 − 1 = 14. Female hurricanes vary more, with an extreme high value (256).' },
        { label: 'Conclusion', body: 'The higher female mean is driven by a few extreme storms. The typical (median) hurricane is the same for both.' },
      ], answer: 'No — we can\'t reliably conclude female-named hurricanes are deadlier.', source: { pages: [55], section: '2.4, 2.6 Example 3' } },
      { kind: 'summary', points: ['Five-number summary → boxplot.', 'Each section ≈ 25% of data; length = spread.', 'Skewed data → compare medians and IQRs.'] },
    ],
    recall: [{ prompt: 'What percent of the data lie between Q1 and Q3?', answer: 'About 50% (the box).' }],
    teach: {
      prompt: 'Explain how to read a boxplot, including what each section represents and what a long whisker tells you.',
      items: [
        { id: 'five', idea: 'Shows the five-number summary', patterns: ['five.number|min.{0,60}q1|quartile'], weight: 1 },
        { id: 'quarter', idea: 'Each section ≈ 25% of the data', patterns: ['25'], weight: 1 },
        { id: 'spread', idea: 'Longer section = more spread, not more data', patterns: ['spread|varia|longer.{0,40}(not|doesn.t).{0,20}more'], weight: 1 },
        { id: 'box50', idea: 'The box holds the middle 50% (IQR)', patterns: ['50|middle half|iqr'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['longer.{0,40}more (data|values|points)'], message: 'A longer section shows more spread — every section has about 25% of the data.' }],
      model: 'A boxplot shows the five-number summary. The box runs from Q1 to Q3 and contains the middle 50% of the data (the IQR), with a line at the median; whiskers extend to the minimum and maximum, and outliers may be dots. Each of the four sections holds about 25% of the data, so a long whisker means that quarter of the data is spread out — for example a long right whisker suggests right skew — not that it has more values.',
    },
    formulas: [], glossary: ['boxplot', 'five-number'],
  },
  {
    id: 'range-iqr', unit: 'u2', section: '2.7', title: 'Range & Interquartile Range',
    short: 'Two quick measures of spread — one fragile, one resistant.',
    source: { ...S27, pages: [50, 52, 17, 18] }, prereqs: ['position'], related: ['std-dev', 'outliers', 'boxplots'],
    confusedWith: [{ id: 'std-dev', why: 'All three measure spread, but differently.' }],
    difficulty: 2, importance: 5, minutes: 8, dims: ['recognize', 'calculate', 'interpret', 'apply'],
    know: ['Range = max − min; IQR = Q3 − Q1'], understand: ['IQR is resistant; range is not'],
    calculate: ['Range and IQR'], interpret: ['"All values are within … of each other"; "The middle 50% are within …"'],
    misconceptions: ['range-vs-iqr', 'quartile-include-median'],
    why: { analogy: 'Range is the gap between the tallest and shortest player on a team — add one 7-foot player and it explodes. IQR is the height span of the middle half of the team — the 7-footer barely changes it.', body: 'Range uses only the two most extreme values, so a single outlier changes it a lot. IQR ignores the top and bottom quarters, so it describes the typical spread even when outliers exist.' },
    memoryTrick: 'Range = **R**oof − floor. IQR = **I**nside the box.',
    lesson: [
      { kind: 'hook', title: 'Which paint lasts more consistently?', body: 'A testing lab measured months before fading for 6 cans of two paints:\n\n- Brand A: 10, 60, 55, 22, 48, 15\n- Brand B: 35, 45, 30, 35, 40, 25\n\nBoth have a mean of **35 months**. Which would you buy?' },
      { kind: 'predict', prompt: 'Predict the **range** of Brand A.', input: { type: 'number', answer: 50, tol: 0.01, unit: 'months' }, reveal: 'Range A = 60 − 10 = **50** months. Brand B: 45 − 25 = **20** months. Same mean, very different spread!' },
      { kind: 'explain', title: 'Range and IQR', body: '- **Range** = max − min: the total width of the data.\n- **IQR** = Q3 − Q1: the width of the **middle 50%**.\n\nBrand A sorted: 10, 15, 22, 48, 55, 60 → Q1 = 15, Q3 = 55 → **IQR = 40**.\nBrand B sorted: 25, 30, 35, 35, 40, 45 → Q1 = 30, Q3 = 40 → **IQR = 10**.', source: { pages: [50], section: S27.section } },
      { kind: 'check', prompt: 'OJ prices: Q1 = $3.59 and Q3 = $4.29. Find the IQR.', input: { type: 'number', answer: 0.7, tol: 0.001, unit: '$' }, explain: '4.29 − 3.59 = **$0.70**: the middle 50% of carton prices are within 70¢ of each other.' },
      { kind: 'check', prompt: 'Which interpretation of "IQR = 10" for chip air % is correct?', input: { type: 'mc', options: [
        { id: 'a', text: 'The middle 50% of chip bags have air percentages within 10% of each other', correct: true, why: 'That is exactly what IQR measures.' },
        { id: 'b', text: 'All chip bags are within 10% of each other', why: 'That would describe the range (which is 40).', misconception: 'range-vs-iqr' },
        { id: 'c', text: 'A typical bag is 10% away from the mean', why: 'That describes the standard deviation.' },
      ] }, explain: 'IQR → middle 50%.' },
      { kind: 'formula', formulaId: 'iqr' },
      { kind: 'summary', points: ['Range = max − min (sensitive to outliers).', 'IQR = Q3 − Q1 (middle 50%, resistant).', 'Interpret both in context with units.'] },
    ],
    recall: [{ prompt: 'Interpret a range of $3 for orange juice prices.', answer: 'All the sampled 60 fl. oz. cartons of orange juice are within $3 of each other.' }],
    teach: {
      prompt: 'Explain the range and the IQR, how to compute each, and which is better when there are outliers.',
      items: [
        { id: 'range', idea: 'Range = max − min', patterns: ['max.{0,30}(minus|−|-|subtract).{0,30}min|largest.{0,30}smallest'], weight: 1 },
        { id: 'iqr', idea: 'IQR = Q3 − Q1', patterns: ['q3.{0,30}(minus|−|-|subtract).{0,30}q1|third quartile.{0,40}first'], weight: 1 },
        { id: 'mid', idea: 'IQR covers the middle 50%', patterns: ['middle.{0,20}(50|half)'], weight: 1 },
        { id: 'resist', idea: 'IQR is resistant; range is not', patterns: ['resistant|outlier'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['range.{0,30}resistant'], message: 'The range is not resistant — it depends entirely on the extremes.' }],
      model: 'The range is the maximum minus the minimum — the total width of the data. The IQR is Q3 minus Q1 — the width of the middle 50% of the data. Because the range depends only on the two most extreme values, one outlier can change it a lot; the IQR ignores the top and bottom quarters, so it is resistant and better when there are outliers.',
    },
    formulas: ['range', 'iqr'], glossary: ['range', 'iqr'],
  },
  {
    id: 'std-dev', unit: 'u2', section: '2.7', title: 'Variance & Standard Deviation',
    short: 'The typical distance of data values from the mean.',
    source: S27, prereqs: ['center', 'range-iqr'], related: ['outliers', 'z-score', 'expected-value', 'compare'],
    confusedWith: [{ id: 'range-iqr', why: 'SD uses every value; range and IQR use only a few.' }, { id: 'expected-value', why: 'Random variables have their own σ formula.' }],
    difficulty: 3, importance: 5, minutes: 18, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['Variance = average squared distance from the mean; s = √s²', 'Sample divides by n − 1'], understand: ['Why deviations are squared; why SD returns to original units'],
    calculate: ['Variance and SD by table'], interpret: ['"On average, … is about s away from the mean"; smaller SD = more consistent'],
    misconceptions: ['sd-divide-n', 'sd-no-sqrt', 'sd-no-square', 'sd-meaning'],
    why: { analogy: 'Imagine the mean is the bullseye of a dartboard. The standard deviation is roughly **how far your darts usually land from the bullseye**. A pro (small SD) clusters tightly; a beginner (large SD) sprays all over.', body: 'Deviations from the mean always add to zero (positives cancel negatives), so we square them to make every distance count. Averaging the squares gives the variance — but in squared units ("squared months"), so we take the square root to get back to the original units. Dividing by n − 1 corrects for the fact that a sample tends to underestimate the population\'s spread.' },
    memoryTrick: '**D**eviate → **S**quare → **S**um → **D**ivide (n − 1) → **R**oot. "Dogs Sleep Soundly During Rain."',
    lesson: [
      { kind: 'hook', title: 'Who is more consistent?', body: 'Two basketball players both average **20 points**.\n\n- Player A: 19, 20, 21, 20, 20\n- Player B: 5, 35, 8, 40, 12\n\nYou need someone you can count on every night. Who do you pick — and how would you put a *number* on consistency?' },
      { kind: 'predict', prompt: 'Without calculating: whose typical distance from 20 points is larger?', input: { type: 'mc', options: [
        { id: 'a', text: 'Player A', why: 'Player A is never more than 1 point from 20.' },
        { id: 'b', text: 'Player B', correct: true, why: 'Player B swings 12–20 points from the mean every game.' },
      ] }, reveal: 'Player B\'s games land far from the mean; Player A\'s land right on it. The **standard deviation** measures exactly this "typical distance from the mean".' },
      { kind: 'interact', title: 'See the deviations', widget: 'spread', props: { data: [5, 35, 8, 40, 12], compare: [19, 20, 21, 20, 20] }, prompt: 'Each bar is a deviation (value − mean). Toggle "square them" and watch the squares. Drag points to change the spread.', takeaway: 'Raw deviations always sum to 0 — squaring makes every distance count.' },
      { kind: 'explain', title: 'Variance and standard deviation', body: 'The **variance** is the average **squared** distance of each value from the mean. For a **sample**:\n$$s^2 = \\frac{\\sum (x - \\bar{x})^2}{n - 1}$$\nThe **standard deviation** is its square root, $s = \\sqrt{s^2}$, which returns to the original units. It is the "average distance of a data value from the mean."', source: { pages: [50], section: S27.section } },
      { kind: 'worked', title: 'Example 1 — Paint Brand A', problem: 'Brand A: 10, 60, 15, 22, 48, 55 months, x̄ = 35.', visual: { type: 'table', headers: ['x', 'x − x̄', '(x − x̄)²'], rows: [[10, -25, 625], [60, 25, 625], [15, -20, 400], [22, -13, 169], [48, 13, 169], [55, 20, 400]], caption: 'Deviations sum to 0; squares sum to 2388' }, steps: [
        { label: 'Deviations', body: 'Subtract the mean from each value. They add to 0.' },
        { label: 'Square & sum', body: '625 + 625 + 400 + 169 + 169 + 400 = 2388.' },
        { label: 'Variance', body: '$s^2 = 2388 / (6 - 1) = 477.6$ months².' },
        { label: 'SD', body: '$s = \\sqrt{477.6} \\approx 21.85$ months.' },
      ], answer: 'Brand A: s ≈ 21.85 months. Brand B: s ≈ 7.07 months → Brand B lasts a **more consistent** amount of time; there is less spread in Brand B.', source: { pages: [50, 51], section: '2.7 Example 1' } },
      { kind: 'formula', formulaId: 'sd' },
      { kind: 'check', prompt: 'Data: 2, 4, 9 (mean 5). Compute the **sample standard deviation**.', input: { type: 'number', answer: Math.sqrt(13), tol: 0.01 }, explain: 'Deviations −3, −1, 4 → squares 9, 1, 16 → sum 26 → s² = 26/2 = 13 → s = √13 ≈ **3.606**. (Dividing by 3 would give the population SD 2.944.)' },
      { kind: 'check', prompt: 'OJ prices have s = $0.68. Which interpretation is correct?', input: { type: 'mc', options: [
        { id: 'a', text: 'On average, a carton\'s price is about $0.68 away from the mean price', correct: true, why: 'That is the meaning of SD.' },
        { id: 'b', text: 'All prices are within $0.68 of the mean', why: 'Many prices are farther than one SD away; SD is a typical distance, not a maximum.', misconception: 'sd-meaning' },
        { id: 'c', text: 'Prices vary by 68%', why: 'SD is in the units of the data (dollars), not a percent.', misconception: 'sd-meaning' },
      ] }, explain: 'SD = typical distance from the mean, in the data\'s units.' },
      { kind: 'recall', prompt: 'Why do we square the deviations before averaging them?', answer: 'Because deviations from the mean always add to zero; squaring makes them all positive so every distance counts.' },
      { kind: 'summary', points: ['s² = Σ(x − x̄)² ÷ (n − 1); s = √s².', 'SD = typical distance from the mean (original units).', 'Smaller SD = more consistent.'] },
    ],
    recall: [{ prompt: 'Write the sample variance formula from memory.', answer: '$s^2 = \\frac{\\sum (x - \\bar{x})^2}{n - 1}$' }, { prompt: 'What does a smaller standard deviation tell you about a data set?', answer: 'The values are more consistent — they cluster more tightly around the mean.' }],
    teach: {
      prompt: 'Explain what the standard deviation measures, how it is calculated, and why we square and then square-root.',
      items: [
        { id: 'meaning', idea: 'Typical/average distance from the mean', patterns: ['(typical|average|usual).{0,30}(distance|far|deviat).{0,40}mean|how far.{0,40}mean|spread.{0,40}mean'], weight: 1.5 },
        { id: 'dev', idea: 'Subtract the mean from each value (deviations)', patterns: ['subtract|minus|deviation|x ?− ?x|difference'], weight: 1 },
        { id: 'square', idea: 'Square the deviations because they sum to 0', patterns: ['square.{0,80}(zero|0|cancel|negative|positive)|(zero|cancel|negative).{0,80}square'], weight: 1 },
        { id: 'n1', idea: 'Divide by n − 1 for a sample', patterns: ['n ?- ?1|n ?− ?1|n minus (one|1)'], weight: 1 },
        { id: 'root', idea: 'Square root returns to original units', patterns: ['(square )?root.{0,60}(unit|original|back)'], weight: 1 },
        { id: 'consist', idea: 'Smaller SD = more consistent', patterns: ['consisten|less spread|cluster|small(er)? (sd|standard deviation)'], weight: 0.5 },
      ],
      misconceptions: [
        { patterns: ['divide by n\\b(?! ?[−-])'], message: 'For sample data, divide by n − 1, not n.' },
        { patterns: ['standard deviation.{0,40}(is|=|means).{0,15}(the )?(range|maximum|biggest)', '^\\s*(it|sd|s)\\b.{0,10}(is|=) the (range|maximum|biggest)'], message: 'The SD is a typical distance from the mean, not the range or a maximum.' },
      ],
      model: 'The standard deviation measures the typical distance of data values from the mean. To compute it, subtract the mean from each value to get deviations. Deviations always add to zero, so we square them to make every distance count, add the squares, and divide by n − 1 for a sample — that is the variance. The variance is in squared units, so we take the square root to get back to the original units. A smaller standard deviation means the data are more consistent.',
    },
    formulas: ['variance', 'sd'], glossary: ['variance', 'standard-deviation'],
  },
  {
    id: 'outliers', unit: 'u2', section: '2.7', title: 'Outliers & Resistant Measures',
    short: 'The 1.5 × IQR rule, the 2 SD rule, and which statistics outliers distort.',
    source: { ...S27, pages: [51, 52, 15, 17, 18, 1] }, prereqs: ['range-iqr', 'std-dev'], related: ['compare', 'boxplots', 'center'],
    confusedWith: [{ id: 'z-score', why: 'The 2 SD rule is the same as |z| > 2.' }],
    difficulty: 3, importance: 5, minutes: 14, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['Fences: Q1 − 1.5·IQR, Q3 + 1.5·IQR', '2 SD rule: x̄ ± 2s'], understand: ['Mean, SD, range are not resistant; median and IQR are', 'The two rules can disagree'],
    calculate: ['Fences and 2 SD bounds; recompute statistics without the outlier'], interpret: ['Decide which measure of spread best describes data with outliers'],
    misconceptions: ['fence-wrong-quartile', 'fence-forget-15', 'resistant-measures', 'mean-resistant'],
    why: { analogy: 'A security fence around a house: the box is the house, and the fences sit 1.5 house-widths out on each side. Anything past the fence is an intruder (outlier).', body: 'We need an objective rule so "outlier" isn\'t just a feeling. The IQR rule builds fences from the resistant quartiles, so it works even for skewed data. The 2 SD rule uses mean and SD, which the outlier itself inflates, so it is best for roughly symmetric data.' },
    memoryTrick: '"**Q1 down, Q3 up, 1.5 boxes each way**."',
    lesson: [
      { kind: 'hook', title: 'The Big Tasty', body: 'Twelve McDonald\'s beef sandwiches have between 8 and 40 grams of fat. The "Big Tasty" — left off the list — has **54 grams**. Is it an outlier, or just a big sandwich?' },
      { kind: 'explain', title: 'Two outlier rules', body: '**1.5 × IQR rule**: compute IQR = Q3 − Q1. Values below **Q1 − 1.5·IQR** or above **Q3 + 1.5·IQR** are outliers.\n\n**2 SD rule**: "typical" values lie within **two standard deviations of the mean**: from $\\bar{x} - 2s$ to $\\bar{x} + 2s$.', source: { pages: [51], section: S27.section } },
      { kind: 'formula', formulaId: 'fences' },
      { kind: 'worked', title: 'Is 54 g an outlier?', problem: 'McDonald\'s: 8, 11, 15, 17, 21, 22, 26, 27, 27, 29, 31, 40 (x̄ = 22.833, s ≈ 9.064).', steps: [
        { label: 'Quartiles', body: 'Lower half 8 11 15 17 21 22 → Q1 = 16. Upper half 26 27 27 29 31 40 → Q3 = 28. IQR = 12.' },
        { label: 'Fences', body: '1.5 × 12 = 18 → lower 16 − 18 = −2, upper 28 + 18 = **46**.' },
        { label: 'IQR rule', body: '54 > 46 → **outlier**.' },
        { label: '2 SD rule', body: '22.833 + 2(9.064) = 40.96 → 54 > 40.96 → **outlier** too.' },
      ], answer: 'Both rules flag 54 g. Adding it raises the range (32 → 46) and SD (9.06 → 12.25) a lot, but the IQR only moves 12 → 14.', source: { pages: [51], section: '2.7 Example 2' } },
      { kind: 'interact', title: 'Drag an outlier', widget: 'outliers', props: { dataset: 'mcd' }, prompt: 'Drag the highlighted sandwich to the right. Watch the fences, the 2 SD band, and the five statistics react.', takeaway: 'Mean, SD, and range jump; median and IQR barely move — they are **resistant**.' },
      { kind: 'check', prompt: 'South Branch bank hours: Q1 = 36, Q3 = 42. What is the **upper fence**?', input: { type: 'number', answer: 51, tol: 0.01, unit: 'hours' }, explain: 'IQR = 6 → 1.5 × 6 = 9 → 42 + 9 = **51**. So 70 hours is an outlier, but 45 and 48 are not.' },
      { kind: 'check', prompt: 'If you remove an outlier, which measures change the **most**?', input: { type: 'mc', options: [
        { id: 'a', text: 'Mean, standard deviation, and range', correct: true, why: 'These use the actual size of extreme values.' },
        { id: 'b', text: 'Median and IQR', why: 'These are resistant — they barely change.', misconception: 'resistant-measures' },
      ] }, explain: 'Chips without Fritos: mean 42.571 → 44.385, SD 10.181 → 7.901, range 40 → 31; median 45.5 → 46, IQR 10 → 9.5.' },
      { kind: 'worked', title: 'When the rules disagree (Exam #1 #6)', problem: 'Medical school GPAs: x̄ = 3.724, s = 0.068, min 3.57, Q1 = 3.667, Q3 = 3.775.', steps: [
        { label: 'IQR rule', body: 'IQR = 0.105 → step 0.1575 → fences 3.51 and 3.93 → **no outliers**.' },
        { label: '2 SD rule', body: '3.724 ± 2(0.068) = 3.588 to 3.86 → **3.57 is an outlier**.' },
      ], answer: 'Different rules can give different answers — say which rule you used.', source: { pages: [1], section: 'Exam #1 Review KEY #6c', note: 'The key writes the lower fence as Q3 − 0.1575; it should be Q1 − 0.1575 (conclusion unchanged).' } },
      { kind: 'summary', points: ['IQR rule: Q1 − 1.5·IQR and Q3 + 1.5·IQR.', '2 SD rule: x̄ ± 2s.', 'Resistant: median, IQR. Not resistant: mean, SD, range.'] },
    ],
    recall: [{ prompt: 'State both outlier rules from memory.', answer: 'Outside Q1 − 1.5·IQR or Q3 + 1.5·IQR (IQR rule); outside x̄ ± 2s (2 SD rule).' }],
    teach: {
      prompt: 'Explain how to identify outliers using both course rules, and explain which statistics are affected by outliers.',
      items: [
        { id: 'iqr', idea: 'Fences at Q1 − 1.5·IQR and Q3 + 1.5·IQR', patterns: ['1\\.5'], weight: 1.5 },
        { id: 'quart', idea: 'Lower fence from Q1, upper from Q3', patterns: ['q1.{0,60}q3|first quartile.{0,60}third'], weight: 0.5 },
        { id: 'sd', idea: '2 SD rule: mean ± 2 standard deviations', patterns: ['(2|two) (sd|standard deviation)|2s|± ?2'], weight: 1 },
        { id: 'nonres', idea: 'Mean, SD, range are affected', patterns: ['(mean|standard deviation|range).{0,80}(affect|change|pull|sensitive|not resistant)'], weight: 1 },
        { id: 'res', idea: 'Median and IQR are resistant', patterns: ['(median|iqr).{0,60}(resistant|not (really )?affect|barely|stay)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['median.{0,40}(heavily|greatly) affect', 'standard deviation.{0,30}resistant'], message: 'The median is resistant; the standard deviation is not.' }],
      model: 'With the 1.5×IQR rule, find IQR = Q3 − Q1, multiply by 1.5, subtract that from Q1 and add it to Q3; anything outside those fences is an outlier. With the 2 SD rule, typical values lie within two standard deviations of the mean, so anything outside x̄ ± 2s is an outlier. Outliers strongly affect the mean, standard deviation, and range, while the median and IQR are resistant and barely change.',
    },
    formulas: ['fences', 'two-sd'], glossary: ['outlier', 'iqr-rule', 'two-sd-rule', 'resistant'],
  },
  {
    id: 'z-score', unit: 'u2', section: '2.7', title: 'Standard Deviations from the Mean',
    short: 'Measuring how unusual a value is with an SD ruler (z-score).',
    source: { ...S27, pages: [19, 52], note: 'The PDF performs this calculation in 2.7 Practice #3 without naming it a z-score.' }, prereqs: ['std-dev'], related: ['position', 'outliers'],
    confusedWith: [{ id: 'position', why: 'Percentiles rank by count; z-scores measure distance in SDs.' }],
    difficulty: 3, importance: 3, minutes: 10, dims: ['recognize', 'calculate', 'interpret', 'apply'],
    know: ['(x − x̄)/s = number of SDs from the mean'], understand: ['Lets you compare values from different distributions'],
    calculate: ['Standardized score'], interpret: ['"Maryland is 0.858 SDs below the mean number of counties"'],
    misconceptions: ['z-divide-variance', 'z-sign'],
    why: { analogy: 'Comparing a 90 on an easy test to a 75 on a brutal test is unfair. Measuring each score in "standard deviations above the class average" levels the playing field — like converting currencies before comparing prices.', body: 'Different variables have different units and spreads. Dividing the distance from the mean by the SD turns any value into a unitless "how many SDs away" number, so positions in completely different distributions can be compared.' },
    memoryTrick: '"How far ÷ how spread" — **distance over ruler**.',
    lesson: [
      { kind: 'hook', title: 'Representatives or counties?', body: 'Maryland has **8 representatives** (states average 8.7, SD 9.723) and **23 counties** (states average 62.82, SD 46.421).\n\nIn which is Maryland more unusual?' },
      { kind: 'predict', prompt: 'Maryland is 0.7 representatives below the mean. Is it also "closer" in counties, where it is 39.82 below the mean?', input: { type: 'mc', options: [
        { id: 'a', text: 'Can\'t compare raw differences — the spreads are different', correct: true, why: 'Exactly. 39.82 counties might be small or large depending on how spread out counties are.' },
        { id: 'b', text: 'Representatives — 0.7 is much smaller than 39.82', why: 'Raw differences in different units and spreads can\'t be compared directly.' },
      ] }, reveal: 'Divide each distance by its distribution\'s SD to measure it in standard deviations.' },
      { kind: 'explain', title: 'Standardizing', body: '$$z = \\frac{x - \\bar{x}}{s}$$\nThe result is the number of standard deviations a value is from the mean — **positive above** the mean, **negative below**.\n\n*Supporting note*: statisticians call this a **z-score**. The course computes it in 2.7 Practice #3.', source: { pages: [19], section: '2.7 Practice #3' }, supporting: true },
      { kind: 'worked', title: 'Maryland, two ways', problem: 'Reps: 8 (x̄ = 8.7, s = 9.723). Counties: 23 (x̄ = 62.82, s = 46.421).', steps: [
        { label: 'Representatives', body: '(8 − 8.7)/9.723 = −0.7/9.723 = **−0.072** SDs.' },
        { label: 'Counties', body: '(23 − 62.82)/46.421 = **−0.858** SDs.' },
        { label: 'Compare', body: '|−0.858| > |−0.072|.' },
      ], answer: 'Maryland is farther from the mean (in SDs) in number of counties; it is very close to average in representatives.', source: { pages: [19], section: '2.7 Practice #3c–d' } },
      { kind: 'interact', title: 'Compare across distributions', widget: 'zscore', prompt: 'Move each value and see its standardized score. Find two values from different distributions that are "equally unusual".', takeaway: 'Equal z-scores = equally unusual, regardless of units.' },
      { kind: 'check', prompt: 'A chip bag has 19% air (x̄ = 42.571, s = 10.181). How many SDs from the mean?', input: { type: 'number', answer: (19 - 42.571) / 10.181, tol: 0.01 }, explain: '(19 − 42.571)/10.181 ≈ **−2.315** — more than 2 SDs below the mean, so the 2 SD rule flags it as an outlier.' },
      { kind: 'summary', points: ['z = (x − x̄)/s.', 'Sign shows above/below; size shows how unusual.', '|z| > 2 ↔ outside the 2 SD rule.'] },
    ],
    recall: [{ prompt: 'Interpret a standardized score of −0.858.', answer: 'The value is 0.858 standard deviations below the mean.' }],
    teach: {
      prompt: 'Explain how to measure how many standard deviations a value is from the mean, and why it is useful.',
      items: [
        { id: 'formula', idea: 'Subtract the mean, divide by SD', patterns: ['(subtract|minus).{0,60}(divid|over|÷).{0,40}(sd|standard deviation|s\\b)'], weight: 1.5 },
        { id: 'sign', idea: 'Negative below mean, positive above', patterns: ['negative.{0,60}below|below.{0,60}negative|positive.{0,60}above'], weight: 1 },
        { id: 'compare', idea: 'Compare values from different distributions', patterns: ['compar|different (distribution|data|unit|scale)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['divid.{0,30}variance'], message: 'Divide by the standard deviation, not the variance.' }],
      model: 'To find how many standard deviations a value is from the mean, subtract the mean from the value and divide by the standard deviation. A negative result means the value is below the mean and a positive result means above. Because the answer has no units, you can compare positions in different distributions — like Maryland\'s representatives (−0.072 SDs) versus counties (−0.858 SDs).',
    },
    formulas: ['z'], glossary: ['z-score'],
  },
  {
    id: 'compare', unit: 'u2', section: '2.8', title: 'Comparing Distributions',
    short: 'Center, shape, spread (and outliers) — in context, like with like.',
    source: { ...S28, pages: [48, 49, 15, 16, 1, 2, 21] }, prereqs: ['shape', 'boxplots', 'std-dev', 'outliers'], related: ['center', 'range-iqr', 'experiments'],
    confusedWith: [{ id: 'center', why: 'Choosing mean vs. median depends on shape.' }],
    difficulty: 4, importance: 5, minutes: 16, dims: ['recognize', 'interpret', 'apply', 'explain'],
    know: ['Discuss center, shape, spread, outliers'], understand: ['Symmetric → mean & SD; skewed/outliers → median & IQR; compare like with like'],
    calculate: ['Summary statistics for two groups'], interpret: ['Write a comparison in context and state the scope of the conclusion'],
    misconceptions: ['mix-measures', 'wrong-measure-skew', 'no-context'],
    why: { analogy: 'Comparing two pizza places: "Which is better?" needs center (typical rating), spread (how consistent), and shape (a few disasters?). And you\'d compare stars to stars — not one place\'s stars to the other\'s price.', body: 'Two groups can share a mean but differ wildly in consistency or shape. A complete comparison covers all three features in context, and uses resistant measures when skew or outliers are present.' },
    memoryTrick: '**SOCS**: **S**hape, **O**utliers, **C**enter, **S**pread — always **in context**, always **like with like**.',
    lesson: [
      { kind: 'hook', title: 'Does a dog lower your heart rate?', body: '45 dog-loving women did a stressful task **alone**, with a **friend**, or with their **pet dog** (15 each). Their heart rates (bpm) were recorded. Does a pet or a friend reduce stress?', visual: { type: 'boxplot', xLabel: 'Heart rate (bpm)', groups: [{ label: 'Alone', min: 62.6, q1: 75.5, median: 84.7, q3: 87.8, max: 99 }, { label: 'Friend', min: 76.9, q1: 83.4, median: 91.4, q3: 99.7, max: 102.2 }, { label: 'Pet', min: 58.7, q1: 68.9, median: 70.1, q3: 79.7, max: 86.4, outliers: [97.5] }] } },
      { kind: 'explain', title: 'Choosing measures (p.48)', body: '| | Center | Spread |\n|---|---|---|\n| Symmetric | **mean** | **standard deviation** |\n| Skewed or outliers | **median** | **IQR** |\n\nFor boxplots, you only have the five-number summary, so use the **median** and **range/IQR**.\n\n**Compare means to means, medians to medians, SDs to SDs, IQRs to IQRs — don\'t mix and match!**', source: { pages: [48], section: S28.section } },
      { kind: 'predict', prompt: 'The pet group is skewed right with a high outlier (97.5). Which measures should you use to compare it with the others?', input: { type: 'mc', options: [
        { id: 'a', text: 'Median and IQR for all groups', correct: true, why: 'Skew/outliers → resistant measures, and use the same measures for every group.' },
        { id: 'b', text: 'Median and IQR for the pet group, mean and SD for the others', why: 'Don\'t mix and match — compare like with like.', misconception: 'mix-measures' },
        { id: 'c', text: 'Mean and SD for all groups', why: 'The outlier distorts the mean and SD.', misconception: 'wrong-measure-skew' },
      ] }, reveal: 'Use the same resistant measures (median, IQR) for every group.' },
      { kind: 'worked', title: 'Practice 2.8 #2 — writing the comparison', problem: 'Alone: MD 84.7, IQR 12.3. Friend: MD 91.4, IQR 16.3. Pet: MD 70.1, IQR 10.8 (outlier 97.5).', steps: [
        { label: 'Center', body: 'The median heart rate was highest with a friend (91.4 bpm), lowest with a pet (70.1 bpm), and alone in between (84.7 bpm).' },
        { label: 'Shape', body: 'Alone: slightly skewed left. Friend: roughly symmetric. Pet: skewed right with a high outlier.' },
        { label: 'Spread', body: 'Using IQRs (resistant): pet had the most consistent heart rates; friend the least consistent.' },
        { label: 'Conclusion & scope', body: 'A pet seemed to lower heart rate during stress; a friend seemed to raise it. Only dog-loving women were studied, so we can\'t extrapolate to **any** person or **any** stressful task.' },
      ], answer: 'Center + shape + spread, in context, plus the scope of the conclusion.', source: { pages: [16], section: '2.8 Practice #2', note: 'IQRs computed from the printed data (Stapplet method); the PDF key reports slightly different pet-group values.' } },
      { kind: 'interact', title: 'Compare two groups', widget: 'histogram-builder', props: { dataset: 'concerts-students', compare: 'concerts-teachers' }, prompt: 'Compare concerts attended by students vs. teachers. Decide which measures to use, then check the summary.', takeaway: 'Students are skewed right with high outliers → compare medians (8.5 vs. 15) and IQRs (9 vs. 10).' },
      { kind: 'check', prompt: 'North Branch: 27, 33, 45, 55, 61 (approx. symmetric). South Branch: 33, 36, 40, 42, 70 (skewed right). Which comparison of spread is appropriate?', input: { type: 'mc', options: [
        { id: 'a', text: 'North IQR = 22 hours vs. South IQR = 6 hours: South is much more consistent', correct: true, why: 'Five-number summaries → IQRs, and the South data are skewed.' },
        { id: 'b', text: 'North range = 34 vs. South IQR = 6', why: 'Compare IQR to IQR, range to range.', misconception: 'mix-measures' },
      ] }, explain: 'IQR to IQR: 22 vs. 6.' },
      { kind: 'recall', prompt: 'List the features you must discuss when comparing distributions, and the measures to use for skewed data.', answer: 'Center, shape, spread (and outliers), in context. For skewed data or outliers, use the median and IQR.' },
      { kind: 'summary', points: ['Discuss center, shape, spread, outliers — in context.', 'Symmetric → mean/SD; skewed → median/IQR.', 'Compare like with like; state the scope.'] },
    ],
    recall: [{ prompt: 'Why can\'t the heart-rate conclusion be extended to all people?', answer: 'Only dog-loving women were studied; other people (or other tasks) might respond differently.' }],
    teach: {
      prompt: 'Explain how to write a complete comparison of two distributions. What must you include, and how do you choose your measures?',
      items: [
        { id: 'three', idea: 'Discuss center, shape, and spread', patterns: ['center.{0,80}(shape|spread)|shape.{0,80}spread'], weight: 1.5 },
        { id: 'choose', idea: 'Symmetric → mean/SD, skewed → median/IQR', patterns: ['skew.{0,80}(median|iqr)|symmetric.{0,80}(mean|standard deviation)'], weight: 1 },
        { id: 'like', idea: 'Compare like with like', patterns: ['same measure|like with like|means to means|medians to medians|don.t mix|mix and match'], weight: 1 },
        { id: 'context', idea: 'Use context / units', patterns: ['context|units?'], weight: 0.5 },
        { id: 'out', idea: 'Mention outliers', patterns: ['outlier'], weight: 0.5 },
      ],
      misconceptions: [{ patterns: ['skew.{0,60}use (the )?mean'], message: 'For skewed data, use the median and IQR.' }],
      model: 'A complete comparison discusses center, shape, and spread, plus any outliers, in the context of the problem. First look at the shape: if both groups are roughly symmetric, compare means and standard deviations; if either is skewed or has outliers, compare medians and IQRs. Always compare the same measure across groups — means to means, IQRs to IQRs — and say what the numbers mean in context, including how far the conclusion can be generalized.',
    },
    formulas: [], glossary: ['center-shape-spread'],
  },
];
