import type { Concept } from '../../engine/types';

const S12 = { pages: [43, 44, 45, 46, 47, 10, 11, 12, 13, 14], section: '12.1–12.3, 12.5 Two Quantitative Variables and Regression' };

export const UNIT3: Concept[] = [
  {
    id: 'scatter', unit: 'u3', section: '12.1', title: 'Scatterplots & Bivariate Data',
    short: 'Explanatory vs. response, direction, strength, and form.',
    source: { ...S12, pages: [43, 46, 10, 11, 13, 2] }, prereqs: ['data-types', 'experiments'], related: ['correlation', 'regression'],
    confusedWith: [{ id: 'experiments', why: 'Explanatory/response roles come from Unit 1.' }],
    difficulty: 2, importance: 4, minutes: 10, dims: ['recognize', 'interpret', 'apply', 'explain'],
    know: ['Bivariate data; explanatory on x-axis, response on y-axis', 'Direction, strength, form, outliers'], understand: ['A scatterplot shows whether a linear model is reasonable'],
    calculate: [], interpret: ['Describe a scatterplot in context'],
    misconceptions: ['explanatory-vs-response', 'r-nonlinear'],
    why: { analogy: 'A scatterplot is like plotting every student\'s study hours (x) against their test score (y). If the dots climb like stairs, more studying tends to go with higher scores.', body: 'With two quantitative variables, a single summary number hides the relationship. Plotting each individual as a point reveals the direction, strength, and shape of the association — and any individuals that break the pattern.' },
    memoryTrick: '**X** e**X**plains, **Y** responds — "x on the floor, y in the sky."',
    lesson: [
      { kind: 'hook', title: 'Diving deeper', body: 'SCUBA divers can\'t exceed a maximum dive time at each depth. At 50 ft it\'s 80 minutes; at 130 ft just 10. What pattern connects depth and time?', visual: { type: 'scatter', points: [[50, 80], [60, 55], [70, 45], [80, 35], [90, 25], [100, 22], [130, 10]], xLabel: 'Depth (ft)', yLabel: 'Max dive time (min)' } },
      { kind: 'explain', title: 'Reading a scatterplot', body: '**Bivariate** data pair two variables per individual. In a **scatterplot**, the **explanatory** variable (x) goes on the horizontal axis and the **response** variable (y) on the vertical axis.\n\nDescribe:\n- **Direction**: positive (uphill) or negative (downhill).\n- **Strength**: how tightly points follow a pattern.\n- **Form**: linear or curved.\n- **Outliers**: points far from the pattern.', source: { pages: [43], section: S12.section } },
      { kind: 'check', prompt: 'Archaeopteryx researchers measure the femur, then use it to study the humerus. Which is the explanatory variable?', input: { type: 'mc', options: [
        { id: 'a', text: 'Length of femur', correct: true, why: 'The femur length is used to explain/predict humerus length.' },
        { id: 'b', text: 'Length of humerus', why: 'The humerus is the response being predicted.', misconception: 'explanatory-vs-response' },
      ] }, explain: 'Explanatory = femur (x); response = humerus (y).' },
      { kind: 'interact', title: 'Make a pattern', widget: 'correlation', props: { mode: 'describe' }, prompt: 'Use the sliders to create strong positive, weak negative, and no-relationship scatterplots.', takeaway: 'Direction = slope of the cloud; strength = how tightly the cloud hugs a line.' },
      { kind: 'check', prompt: 'iPhone sales grow slowly at first, then faster and faster each year. The form is…', input: { type: 'mc', options: [
        { id: 'a', text: 'Curved (nonlinear)', correct: true, why: 'The rate of increase gets larger — a curve.' },
        { id: 'b', text: 'Linear', why: 'A line rises at a constant rate.' },
      ] }, explain: 'Curved form → a linear model may not be the best fit (Practice 12 #6).', visual: { type: 'scatter', points: [[0, 0.5], [1, 1], [2, 1], [3, 1.7], [4, 4], [5, 5], [6, 9], [7, 10], [8, 13]], xLabel: 'Years since 2007', yLabel: 'Units sold (millions)' } },
      { kind: 'summary', points: ['x = explanatory (horizontal), y = response (vertical).', 'Describe direction, strength, form, outliers — in context.'] },
    ],
    recall: [{ prompt: 'Name the four features you describe in a scatterplot.', answer: 'Direction, strength, form, and outliers.' }],
    teach: {
      prompt: 'Explain how to set up and describe a scatterplot.',
      items: [
        { id: 'axes', idea: 'Explanatory on x, response on y', patterns: ['explanatory.{0,60}(x|horizontal)|(x|horizontal).{0,60}explanatory'], weight: 1 },
        { id: 'dir', idea: 'Direction (positive/negative)', patterns: ['direction|positive|negative'], weight: 1 },
        { id: 'str', idea: 'Strength', patterns: ['strength|strong|weak'], weight: 1 },
        { id: 'form', idea: 'Form (linear/curved)', patterns: ['linear|curve|form'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['response.{0,40}(x|horizontal)-?axis'], message: 'The response variable goes on the vertical (y) axis.' }],
      model: 'A scatterplot shows two quantitative variables for each individual: the explanatory variable on the horizontal x-axis and the response variable on the vertical y-axis. Describe its direction (positive if y tends to increase with x, negative if it decreases), its strength (how tightly the points follow the pattern), its form (linear or curved), and any outliers — in context.',
    },
    formulas: [], glossary: ['bivariate', 'scatterplot', 'direction', 'strength'],
  },
  {
    id: 'correlation', unit: 'u3', section: '12.1–12.3', title: 'Correlation Coefficient r',
    short: 'Strength and direction of a linear relationship — and why it isn\'t causation.',
    source: { ...S12, pages: [44, 10, 11, 12, 2] }, prereqs: ['scatter'], related: ['r-squared', 'regression', 'experiments'],
    confusedWith: [{ id: 'r-squared', why: 'r² is interpreted as a percent; r is not.' }, { id: 'regression', why: 'r is not the slope.' }],
    difficulty: 3, importance: 5, minutes: 12, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['−1 ≤ r ≤ 1; sign = direction; |r| near 1 = strong'], understand: ['r only measures linear association; correlation does not imply causation'],
    calculate: ['r with technology'], interpret: ['"Strong, positive, linear correlation between … and …"'],
    misconceptions: ['correlation-causation', 'r-strength-sign', 'r-is-slope', 'r-percent', 'r-nonlinear'],
    why: { analogy: 'Ice cream sales and shark attacks are positively correlated. Does ice cream attract sharks? No — hot summer days bring both more ice cream *and* more swimmers.', body: 'r summarizes how tightly points hug a straight line and whether that line goes up or down. It knows nothing about *why* two variables move together — a lurking variable or plain coincidence (spelling-bee word length vs. spider deaths!) can create a strong r.' },
    memoryTrick: '**Sign = direction, size = strength.** And: "Correlation is a clue, not a confession."',
    lesson: [
      { kind: 'hook', title: 'Does chocolate make you smarter?', body: 'A scatterplot in the *New England Journal of Medicine* plotted chocolate consumption per person against Nobel Prizes per 10 million people for each country. **r = 0.791.**\n\nShould the U.S. start eating more chocolate to win more Nobel Prizes?' },
      { kind: 'predict', prompt: 'Predict: what does r = 0.791 tell you?', input: { type: 'mc', options: [
        { id: 'a', text: 'A strong, positive, linear association', correct: true, why: 'Positive sign, size near 1.' },
        { id: 'b', text: 'Eating chocolate causes Nobel Prizes', why: 'Correlation doesn\'t show cause.', misconception: 'correlation-causation' },
        { id: 'c', text: '79.1% of countries follow the line', why: 'r is not a percent.', misconception: 'r-percent' },
      ] }, reveal: 'r = 0.791 → **strong, positive, linear** correlation. It does **not** mean chocolate causes Nobel Prizes — wealthy countries may have both more chocolate and more research funding.' },
      { kind: 'explain', title: 'The correlation coefficient', body: 'Karl Pearson\'s **correlation coefficient r** measures the strength and direction of a **linear** relationship:\n- r is always between **−1 and 1**.\n- Close to **±1** → strong; close to **0** → weak or no linear relationship.\n- **r > 0**: positive (x tends to increase y). **r < 0**: negative.\n\nThe course finds r with technology (Stapplet).', source: { pages: [44], section: S12.section } },
      { kind: 'interact', title: 'Move the points, watch r', widget: 'correlation', props: { mode: 'drag' }, prompt: 'Drag points around. Try to make r = 0.9, then −0.9, then close to 0. Then drag one point far away and watch r collapse.', takeaway: 'One outlier can change r dramatically; a curve can have r near 0.' },
      { kind: 'check', prompt: 'What does a correlation of **r = −0.85** indicate?', input: { type: 'mc', options: [
        { id: 'a', text: 'A strong negative linear relationship', correct: true, why: '|−0.85| is close to 1 → strong; the negative sign → negative direction.' },
        { id: 'b', text: 'A strong positive relationship', why: 'The negative sign means negative direction.', misconception: 'r-strength-sign' },
        { id: 'c', text: '85% of observations are negative', why: 'r is not a percentage of observations.', misconception: 'r-percent' },
        { id: 'd', text: 'The slope is −0.85', why: 'r and the slope are different numbers (they only share a sign).', misconception: 'r-is-slope' },
      ] }, explain: 'Sign → direction, size → strength. r is not a percent and not the slope.' },
      { kind: 'worked', title: 'Exam #1 #9 — spelling bees and spider bites', problem: 'Letters in the winning Spelling Bee word vs. deaths by spider bite per year: r = .806.', steps: [
        { label: 'Interpret r', body: 'Strong, positive, linear correlation between letters in the winning word and spider-bite deaths.' },
        { label: 'Causation?', body: 'Obviously longer words don\'t cause spider bites — a strong r can arise from coincidence.' },
      ], answer: 'Correlation ≠ causation.', source: { pages: [2], section: 'Exam #1 Review KEY #9d' } },
      { kind: 'recall', prompt: 'Explain why a strong correlation does not prove causation, using an example.', answer: 'A lurking variable or coincidence can make two variables move together. Example: chocolate and Nobel Prizes may both rise with national wealth.' },
      { kind: 'summary', points: ['−1 ≤ r ≤ 1; sign = direction; |r| = strength.', 'Linear only; sensitive to outliers.', 'Correlation does not imply causation.'] },
    ],
    recall: [{ prompt: 'Interpret r = 0.9941 for femur and humerus length.', answer: 'There is a strong, positive, linear correlation between femur length and humerus length.' }],
    teach: {
      prompt: 'Explain what the correlation coefficient r tells you, its possible values, and what it does NOT tell you.',
      items: [
        { id: 'range', idea: 'r is between −1 and 1', patterns: ['-1.{0,20}1|−1.{0,20}1|negative one.{0,20}one'], weight: 1 },
        { id: 'dir', idea: 'Sign gives direction', patterns: ['sign|positive.{0,60}negative'], weight: 1 },
        { id: 'str', idea: 'Closeness to ±1 gives strength', patterns: ['(close|near).{0,30}(1|one).{0,40}strong|strong.{0,60}(close|near)'], weight: 1 },
        { id: 'lin', idea: 'Measures linear relationships only', patterns: ['linear'], weight: 1 },
        { id: 'cause', idea: 'Correlation does not imply causation', patterns: ['caus'], weight: 1.5 },
      ],
      misconceptions: [{ patterns: ['negative.{0,30}(means|is) weak', 'r.{0,20}(is|=) (the )?slope'], message: 'A negative r can be strong; r is not the slope.' }],
      model: 'The correlation coefficient r measures the strength and direction of a linear relationship between two quantitative variables. It is always between −1 and 1: the sign gives the direction (positive or negative), and values close to −1 or 1 mean a strong linear relationship while values near 0 mean a weak one. r only describes linear patterns, is affected by outliers, and does not show causation — chocolate consumption and Nobel Prizes are correlated, but chocolate doesn\'t cause prizes.',
    },
    formulas: [], glossary: ['correlation-coefficient'],
  },
  {
    id: 'regression', unit: 'u3', section: '12.1–12.3', title: 'Least-Squares Regression Line',
    short: 'ŷ = a + bx: slope, intercept, prediction, and extrapolation.',
    source: { ...S12, pages: [43, 44, 45, 10, 11, 12, 2] }, prereqs: ['scatter', 'correlation'], related: ['residuals', 'r-squared'],
    confusedWith: [{ id: 'correlation', why: 'The slope b and r are different numbers.' }],
    difficulty: 3, importance: 5, minutes: 16, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['ŷ = a + bx; a = intercept, b = slope'], understand: ['The line minimizes the sum of squared residuals; extrapolation is unreliable'],
    calculate: ['Predict ŷ for a given x; solve for x given ŷ'], interpret: ['Slope and intercept in context'],
    misconceptions: ['slope-wording', 'intercept-literal', 'extrapolation', 'r-is-slope'],
    why: { analogy: 'A regression line is like a GPS estimate of arrival time from distance: "Every extra mile adds about 1.2 minutes" (slope). It is great for trips like the ones it learned from — but don\'t trust it for a cross-country flight (extrapolation).', body: 'Out of all possible lines, least squares picks the one whose squared vertical misses are smallest in total. It summarizes the average trend, so predictions are *expected* values, and they\'re only trustworthy within the x-values the line was built from.' },
    memoryTrick: '"For every **1** more **x**, we **predict** **b** more **y**."',
    lesson: [
      { kind: 'hook', title: 'How long can you dive at 115 ft?', body: 'The dive tables stop at specific depths. A diver wants to go to **115 ft**. Can the data predict the maximum dive time?' },
      { kind: 'interact', title: 'Fit the line yourself', widget: 'scatter-fit', props: { dataset: 'scuba' }, prompt: 'Drag the line\'s two handles to fit the SCUBA data. The squares show each squared residual — make their total area as small as you can. Then reveal the least-squares line.', takeaway: 'The least-squares line is the one with the smallest total squared error.' },
      { kind: 'explain', title: 'ŷ = a + bx', body: 'In statistics, a line is written $\\hat{y} = a + bx$:\n- **a** (y-intercept): the predicted y when x = 0.\n- **b** (slope): the predicted change in y for **every one-unit increase** in x.\n- **ŷ** ("y-hat"): the *predicted* response.\n\n**Linear regression** finds the **least-squares regression line** (technology does this).\n\n**Caution:** only predict for x-values **within the domain** of the sample data. Predicting outside it is **extrapolation**.', source: { pages: [43], section: S12.section } },
      { kind: 'worked', title: 'Example 1b — SCUBA', problem: 'ŷ = 106.3421 − 0.8145x. Predict the max dive time at 115 ft and interpret the slope.', steps: [
        { label: 'Predict', body: 'ŷ = 106.3421 − 0.8145(115) = 106.3421 − 93.6675 ≈ **12.67 minutes**.' },
        { label: 'Within the domain?', body: 'Depths 50–130 ft were observed, so 115 ft is fine. 30 ft would be extrapolation.' },
        { label: 'Slope', body: 'For every 1 additional foot of depth, the predicted maximum dive time **decreases** by 0.8145 minutes.' },
      ], answer: '≈ 12.67 minutes.', source: { pages: [43, 44], section: '12.1 Example 1a–1b' } },
      { kind: 'check', prompt: 'Flowers: ŷ = 180.8 + 15.8x (x = tablespoons of sugar, y = hours fresh). Interpret the **slope**.', input: { type: 'mc', options: [
        { id: 'a', text: 'For every additional tablespoon of sugar, we predict the flower stays fresh 15.8 more hours', correct: true, why: 'Slope = predicted change in y per 1-unit increase in x.' },
        { id: 'b', text: 'For every additional hour fresh, the sugar increases by 15.8 tablespoons', why: 'That reverses x and y.', misconception: 'slope-wording' },
        { id: 'c', text: 'With no sugar, flowers stay fresh 15.8 hours', why: 'That describes an intercept (and the intercept is 180.8).', misconception: 'intercept-literal' },
      ] }, explain: 'Slope: per 1 tbsp of sugar, +15.8 predicted hours. Intercept: with 0 tbsp, predicted 180.8 hours.' },
      { kind: 'check', prompt: 'Archaeopteryx: ŷ = −3.6596 + 1.1969x (femur → humerus). Predict the humerus length (cm) for a 45 cm femur.', input: { type: 'number', answer: -3.6596 + 1.1969 * 45, tol: 0.02, unit: 'cm' }, explain: '−3.6596 + 1.1969(45) = **50.20 cm**.' },
      { kind: 'check', prompt: 'Would you use the flower line to predict freshness with **10 tablespoons** of sugar? (Data used 0–3 tbsp.)', input: { type: 'mc', options: [
        { id: 'a', text: 'No — 10 tbsp is outside the sampled domain (extrapolation)', correct: true, why: 'The line was only built from 0–3 tbsp.' },
        { id: 'b', text: 'Yes — just plug x = 10 into the equation', why: 'You can compute a number, but it isn\'t trustworthy outside the data.', misconception: 'extrapolation' },
      ] }, explain: 'Only predict within 0–3 tablespoons.' },
      { kind: 'worked', title: 'Exam #1 #9 — interpreting the intercept and solving for x', problem: 'ŷ = −5.4141 + 1.2778x (letters → spider deaths).', steps: [
        { label: 'Intercept', body: 'For a 0-letter word we\'d predict −5.4141 deaths — meaningless, since 0 letters is far outside 7–13.' },
        { label: 'Predict x = 10', body: 'ŷ = −5.4141 + 1.2778(10) = 7.3639 → about 7.36 deaths.' },
        { label: 'Solve for x', body: '9 = −5.4141 + 1.2778x → x = 14.4141/1.2778 ≈ 11.28 letters.' },
        { label: 'Domain', body: 'The model is appropriate for words between 7 and 13 letters.' },
      ], answer: 'Interpret in context and respect the domain.', source: { pages: [2], section: 'Exam #1 Review KEY #9c, f, g, h' } },
      { kind: 'summary', points: ['ŷ = a + bx: a = predicted y at x = 0, b = predicted change per unit of x.', 'Least squares minimizes the sum of squared residuals.', 'Don\'t extrapolate beyond the observed x-values.'] },
    ],
    recall: [{ prompt: 'Write the template sentence for interpreting a slope.', answer: '"For every one-unit increase in [x], the predicted [y] increases/decreases by [b] [units]."' }],
    teach: {
      prompt: 'Explain the least-squares regression line: what a and b mean, how to make a prediction, and when predictions are not trustworthy.',
      items: [
        { id: 'eq', idea: 'ŷ = a + bx with ŷ = predicted y', patterns: ['a ?\\+ ?bx|y.?hat|predicted'], weight: 1 },
        { id: 'slope', idea: 'Slope = predicted change in y per 1-unit increase in x', patterns: ['(slope|b).{0,80}(each|every|one|1).{0,30}(unit|increase|more)'], weight: 1.5 },
        { id: 'int', idea: 'Intercept = predicted y when x = 0', patterns: ['(intercept|a).{0,60}(x ?= ?0|zero)'], weight: 1 },
        { id: 'ls', idea: 'Least squares minimizes squared residuals', patterns: ['(minimi|smallest|least).{0,40}(square|residual|error)'], weight: 1 },
        { id: 'extrap', idea: 'Don\'t extrapolate outside the data', patterns: ['extrapolat|outside.{0,30}(range|domain|data)'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['slope.{0,40}change in x'], message: 'The slope is the predicted change in y, per one-unit increase in x.' }],
      model: 'The least-squares regression line ŷ = a + bx is the line that makes the sum of the squared residuals as small as possible. The slope b is the predicted change in y for every one-unit increase in x, and the intercept a is the predicted y when x = 0 (which may be meaningless if x = 0 is outside the data). To predict, substitute an x-value. Predictions are only trustworthy for x-values within the range of the sample data; going outside it is extrapolation.',
    },
    formulas: ['regression-line'], glossary: ['linear-regression', 'regression-line', 'slope', 'y-intercept', 'extrapolation'],
  },
  {
    id: 'r-squared', unit: 'u3', section: '12.1–12.3', title: 'Coefficient of Determination r²',
    short: 'The percent of variation in y explained by x.',
    source: { ...S12, pages: [44, 10, 11, 12, 14, 2] }, prereqs: ['correlation', 'regression'], related: ['residuals', 'correlation'],
    confusedWith: [{ id: 'correlation', why: 'r² is a percent of variation; r is not.' }],
    difficulty: 3, importance: 4, minutes: 10, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['r² = (r)²'], understand: ['r² measures how much of y\'s variation the line accounts for'],
    calculate: ['r² from r; r from r² using the slope\'s sign'], interpret: ['"About __% of the variation in y is explained by the variation in x"'],
    misconceptions: ['r2-meaning', 'r-from-r2-sign', 'r-percent'],
    why: { analogy: 'Test scores vary from student to student. If r² = 0.64 for study hours, it\'s as if 64% of that up-and-down is "accounted for" by how long people studied — the other 36% comes from sleep, luck, prior knowledge…', body: 'Without x, your best prediction for every y is just ȳ, and the total error is the variation in y. Using the regression line shrinks that error; r² is the fraction of the original variation that the line removed.' },
    memoryTrick: 'r² **R**eports **R**eason share (as a percent). r **R**eports **R**elationship strength (not a percent).',
    lesson: [
      { kind: 'hook', title: 'How much does the femur explain?', body: 'Femur length predicts humerus length with r = 0.9941. Humerus lengths still vary from fossil to fossil. How much of that variation can the femur account for?' },
      { kind: 'explain', title: 'r²', body: 'The **coefficient of determination r²** gives the **percent of the variation in the response variable that is explained by the variation in the explanatory variable**, using the regression line.\n\nGoing backward: $r = \\pm\\sqrt{r^2}$ — take the **sign of the slope**.', source: { pages: [44], section: S12.section } },
      { kind: 'check', prompt: 'Femur/humerus: r = 0.9941. Compute r² (as a decimal).', input: { type: 'number', answer: 0.9941 ** 2, tol: 0.001 }, explain: '0.9941² ≈ **0.9883** → about 98.83% of the variation in humerus length is explained by the variation in femur length.' },
      { kind: 'check', prompt: 'Which interpretation of r² = 0.649 (spelling bee → spider deaths) is correct?', input: { type: 'mc', options: [
        { id: 'a', text: 'About 64.9% of the variation in spider-bite deaths is explained by the variation in letters of the winning word', correct: true, why: 'That is the template interpretation.' },
        { id: 'b', text: '64.9% of the points lie on the regression line', why: 'r² is about variation explained, not points on the line.', misconception: 'r2-meaning' },
        { id: 'c', text: 'Longer words cause 64.9% of spider deaths', why: 'r² says nothing about causation.', misconception: 'correlation-causation' },
      ] }, explain: 'Template: "About __% of the variation in **y** is explained by the variation in **x**."' },
      { kind: 'worked', title: 'Practice 12 #5 — from r² back to r', problem: 'Tablets: ŷ = 4.67 + 0.0068x, r² = 0.342.', steps: [
        { label: 'Interpret r²', body: 'About 34.2% of the variation in battery life is explained by the variation in tablet price.' },
        { label: 'Find r', body: '√0.342 ≈ 0.585.' },
        { label: 'Choose the sign', body: 'The slope 0.0068 is **positive**, so r = **+0.585**: a moderate, positive, linear correlation.' },
      ], answer: 'r = 0.585', source: { pages: [12], section: '12.1–12.3 Practice #5c', note: 'The PDF key says the sign can\'t be determined, but r always has the same sign as the slope — here positive.' } },
      { kind: 'check', prompt: 'A regression has r² = 0.81 and slope b = −2.4. What is r?', input: { type: 'number', answer: -0.9, tol: 0.001 }, explain: '√0.81 = 0.9, and the slope is negative → **r = −0.9**.' },
      { kind: 'summary', points: ['r² = % of variation in y explained by x (via the line).', 'r = ±√r², with the slope\'s sign.', 'r² is not % of points on the line, and not causation.'] },
    ],
    recall: [{ prompt: 'Write the r² interpretation template.', answer: '"About __% of the variation in [response] is explained by the variation in [explanatory] (using the regression line)."' }],
    teach: {
      prompt: 'Explain what r² means and how it relates to r.',
      items: [
        { id: 'var', idea: 'Percent of variation in y explained by x', patterns: ['(percent|proportion|%|fraction).{0,60}variation.{0,80}explained|variation.{0,60}explained'], weight: 2 },
        { id: 'sq', idea: 'r² is r squared', patterns: ['square'], weight: 1 },
        { id: 'sign', idea: 'r takes the sign of the slope', patterns: ['sign.{0,40}slope|slope.{0,40}sign'], weight: 1 },
      ],
      misconceptions: [{ patterns: ['(percent|%) of (the )?(points|data) (are |lie )?on'], message: 'r² is the percent of variation explained, not the percent of points on the line.' }],
      model: 'r² is the square of the correlation coefficient. It tells you the percent of the variation in the response variable that is explained by the variation in the explanatory variable using the regression line — e.g. r² = 0.9883 means about 98.83% of the variation in humerus length is explained by femur length. To go from r² back to r, take the square root and give it the same sign as the slope.',
    },
    formulas: ['r2'], glossary: ['r2'],
  },
  {
    id: 'residuals', unit: 'u3', section: '12.3, 12.5', title: 'Residuals & Residual Plots',
    short: 'Observed − predicted, over/under-prediction, and choosing a model.',
    source: { ...S12, pages: [44, 45, 12, 13, 14] }, prereqs: ['regression'], related: ['r-squared', 'regression'],
    confusedWith: [{ id: 'r-squared', why: 'Residual plots and r² together judge a model.' }],
    difficulty: 4, importance: 4, minutes: 16, dims: ['recognize', 'calculate', 'interpret', 'apply', 'explain'],
    know: ['Residual = y − ŷ', 's = standard deviation of the residuals'], understand: ['Random residual plot → linear OK; curved → not; compare models by residuals, s, r²'],
    calculate: ['Residual for a point'], interpret: ['"The line overpredicts/underpredicts … by …"; choose between linear, quadratic, exponential'],
    misconceptions: ['residual-order', 'residual-sign-meaning', 'residual-pattern'],
    why: { analogy: 'Residuals are the leftovers after the line has done its best. If the leftovers look like random crumbs, the line captured the pattern. If the leftovers form a smile or a frown, the line missed a curve.', body: 'A good model leaves only random noise behind. Any systematic pattern in the residuals means the model is consistently wrong in some region — e.g. a straight line through curved data overpredicts in the middle and underpredicts at the ends.' },
    memoryTrick: 'Residual = **A**ctual − **P**redicted (**A.P.**). Positive → point is **above** the line → **under**prediction.',
    lesson: [
      { kind: 'hook', title: 'The sugary flower', body: 'The flower line predicts ŷ = 180.8 + 15.8x hours of freshness. One flower got **2 tablespoons** and stayed fresh **204 hours**. Did the line guess too high or too low?' },
      { kind: 'predict', prompt: 'Predicted: 180.8 + 15.8(2) = 212.4 hours. Actual: 204 hours. The line…', input: { type: 'mc', options: [
        { id: 'a', text: 'Overpredicted by 8.4 hours', correct: true, why: 'Predicted 212.4 > actual 204.' },
        { id: 'b', text: 'Underpredicted by 8.4 hours', why: 'The prediction was higher than what happened.', misconception: 'residual-sign-meaning' },
      ] }, reveal: 'Residual = observed − predicted = 204 − 212.4 = **−8.4 hours**. Negative → the line **overpredicted**.' },
      { kind: 'explain', title: 'Residuals', body: 'A **residual** is the vertical distance from a point to the line:\n$$\\text{residual} = y - \\hat{y} = \\text{observed} - \\text{predicted}$$\n- **Positive** residual → the model **underestimates** (point above the line).\n- **Negative** residual → the model **overestimates** (point below the line).\n\nThe least-squares line minimizes the **sum of the squared residuals**.', source: { pages: [44], section: S12.section } },
      { kind: 'interact', title: 'Residual plots', widget: 'residuals', props: { datasets: ['archaeopteryx', 'iphone', 'yogurt'] }, prompt: 'Click points to see their residuals, then compare the residual plot for each data set.', takeaway: 'Random scatter → linear is appropriate. A curve (iPhone) → linear is not the best model.' },
      { kind: 'explain', title: 'Good vs. poor models', body: 'A good regression model has a roughly **random** arrangement of residuals; poor models show **curves and patterns**.\n\nWhen comparing models (linear, quadratic, exponential), prefer the one with:\n- the most random residual plot,\n- the smallest **s** (standard deviation of the residuals — the typical prediction error),\n- the largest **r²**.', visual: { type: 'residual', xLabel: 'Years since 2007 (linear model)', points: [[0, 1.9], [1, 0.8], [2, -0.8], [3, -1.7], [4, -1.0], [5, -1.6], [6, 0.8], [7, 0.2], [8, 1.6]] }, source: { pages: [44, 13, 14], section: S12.section } },
      { kind: 'worked', title: 'Practice 12 #6 — iPhone sales', problem: 'Linear: s = 1.4429, r² = 0.9138. Quadratic: s = 0.6761, r² = 0.9838. Exponential: s = 1.5587, r² = 0.97.', steps: [
        { label: 'Linear residuals', body: 'Curved pattern → linear is not the best fit.' },
        { label: 'Interpret s', body: 'Quadratic: predictions are typically off by about 0.6761 million units.' },
        { label: 'Interpret r²', body: 'Quadratic: about 98.38% of the variation in units sold is explained by release year.' },
        { label: 'Choose', body: 'Quadratic has the most random residuals, the smallest s, and the largest r².' },
      ], answer: 'The quadratic model is most appropriate.', source: { pages: [13, 14], section: '12.5 Practice #6' } },
      { kind: 'check', prompt: 'Tablets: at price $800 the residual is about −1.3 hours. The model…', input: { type: 'mc', options: [
        { id: 'a', text: 'Overpredicts battery life at $800', correct: true, why: 'Negative residual → prediction higher than actual.' },
        { id: 'b', text: 'Underpredicts battery life at $800', why: 'That would be a positive residual.', misconception: 'residual-sign-meaning' },
      ] }, explain: 'Negative residual = overprediction.' },
      { kind: 'check', prompt: 'A flower with **1 tablespoon** lasted 205 hours. Compute its residual.', input: { type: 'number', answer: 205 - 196.6, tol: 0.01, unit: 'hours' }, explain: 'ŷ = 180.8 + 15.8 = 196.6 → residual = 205 − 196.6 = **8.4 hours** (underpredicted).' },
      { kind: 'summary', points: ['Residual = observed − predicted.', 'Positive → underprediction; negative → overprediction.', 'Random residual plot → linear OK; pattern → try another model.', 's = typical prediction error.'] },
    ],
    recall: [{ prompt: 'What does a curved residual plot tell you?', answer: 'A linear model is not appropriate; a curved model (quadratic/exponential) may fit better.' }],
    teach: {
      prompt: 'Explain what a residual is, what its sign means, and how a residual plot helps you judge a regression model.',
      items: [
        { id: 'def', idea: 'Residual = observed − predicted', patterns: ['(observed|actual).{0,30}(minus|−|-|subtract).{0,30}predict'], weight: 1.5 },
        { id: 'pos', idea: 'Positive → underpredicted (above line)', patterns: ['positive.{0,80}(under|above)'], weight: 1 },
        { id: 'neg', idea: 'Negative → overpredicted (below line)', patterns: ['negative.{0,80}(over|below)'], weight: 1 },
        { id: 'plot', idea: 'Random residual plot → linear appropriate; pattern → not', patterns: ['random|no pattern|pattern|curve'], weight: 1.5 },
      ],
      misconceptions: [{ patterns: ['predicted.{0,20}(minus|−|-).{0,20}(observed|actual)', 'positive.{0,40}over(predict|estimat)'], message: 'Residual = observed − predicted; a positive residual means the model underpredicted.' }],
      model: 'A residual is the observed value minus the predicted value, y − ŷ: the vertical distance from a point to the regression line. A positive residual means the point is above the line, so the model underpredicted; a negative residual means it overpredicted. A residual plot graphs residuals against x. If the residuals are randomly scattered with no pattern, a linear model is appropriate; a curve or pattern means the line systematically misses and another model (like quadratic) may fit better.',
    },
    formulas: ['residual'], glossary: ['residual', 'residual-plot', 's-residuals'],
  },
];
